const D=SkinmateData,L=SkinmateLogic;
let state=SkinmateStorage.load(localStorage,D), screen='home', routeId='', toastTimer;
D.reviews.push(...(state.userReviews||[]).filter(r=>!D.reviews.some(x=>x.id===r.id)));
state.auth=state.auth&&typeof state.auth==='object'?{loggedIn:state.auth.loggedIn===true,email:state.auth.email||''}:{loggedIn:false,email:''};
function hasLoginSession(){try{return sessionStorage.getItem('skinmate-login-session')==='active'}catch{return false}}
function setLoginSession(active){try{if(active)sessionStorage.setItem('skinmate-login-session','active');else sessionStorage.removeItem('skinmate-login-session')}catch{}}
if(!hasLoginSession())state.auth.loggedIn=false;
let exploreQuery='',exploreCategory='all';
let profileDraft=null,saveTab='병원',communityFilter='all',budgetMode='all',compareSource='hospitals';
const routes=['login','onboarding','home','concern','subconcern','hospital-reviews','priority','treatments','treatment','hospitals','detail','completion','compare','explore','article','event','community','saved','my','profile','checklist','activity','settings'];
const treatment=id=>D.treatments.find(t=>t.id===id),hospital=id=>D.hospitals.find(h=>h.id===id);
const criterion=k=>D.criteria.find(c=>c.id===k), selected=()=>treatment(state.selectedTreatment);
const money=r=>`${r[0]}~${r[1]}만원`, distance=h=>`${h.location}역 ${h.distance<1?Math.round(h.distance*1000)+'m':h.distance+'km'}`;
function toast(s){const e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3000);}
function openLogin(){const d=document.createElement('dialog');d.innerHTML='<h2>Skinmate 로그인 체험</h2><div class="dialog-body"><p>서버 인증 없이 로그인 화면을 체험해요. 정보는 이 브라우저에만 저장됩니다.</p><form id="login-form"><label class="field">이메일<input name="email" type="email" placeholder="you@example.com" required></label><button class="primary" type="submit">로그인</button></form></div><div class="split-buttons"><button class="secondary" data-close>나중에</button></div>';document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.querySelector('#login-form').addEventListener('submit',e=>{e.preventDefault();const email=new FormData(e.target).get('email');if(update(()=>{state.auth={loggedIn:true,email:String(email).slice(0,120)};})){setLoginSession(true);d.close();go(state.onboarded?'home':'onboarding');toast('로그인했어요.');}});d.showModal();}
function hospitalAction(value){const [id,fixedTreatment]=value.split(':'),h=hospital(id);if(!h)return;const current=h.treatments.includes(fixedTreatment)?fixedTreatment:h.treatments.includes(state.selectedTreatment)?state.selectedTreatment:h.treatments[0],offer=L.getOffer(id,current);const d=document.createElement('dialog');d.className='hospital-action-dialog';d.innerHTML=`<h2>결제하기</h2><p class="tiny">${esc(h.name)} · 가상 병원 체험</p><form class="hospital-action-form"><label class="field">시술<select name="treatment" required>${(fixedTreatment?[current]:h.treatments).map(tid=>`<option value="${esc(tid)}" ${tid===current?'selected':''}>${esc(treatment(tid).name)}</option>`).join('')}</select></label><p class="hospital-checkout-price">예상 금액 ${offerPrice(offer)}</p><p class="tiny">실제 결제와 병원 예약은 진행되지 않습니다. 카드 정보는 입력받지 않아요.</p><div class="split-buttons"><button type="button" class="secondary" data-close>취소</button><button type="submit" class="primary">체험 결제 완료</button></div></form>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.querySelector('select[name=treatment]').addEventListener('change',e=>{d.querySelector('.hospital-checkout-price').innerHTML=`예상 금액 ${offerPrice(L.getOffer(id,e.target.value))}`;});d.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const tid=String(new FormData(e.currentTarget).get('treatment'));if(!h.treatments.includes(tid))return;const record={hospitalId:id,treatmentId:tid,createdAt:new Date().toISOString(),price:L.getOffer(id,tid)?.price||0};if(update(()=>{state.payments=[record,...(state.payments||[])].slice(0,20)})){d.close();go('completion','payment');}});d.showModal();}
function update(fn){const old=structuredClone(state);fn();try{localStorage.setItem('skinmate-v2',JSON.stringify(state));return true;}catch{state=old;toast('저장하지 못했어요. 브라우저 저장 공간을 확인해 주세요.');return false;}}
function repaint(){const y=document.getElementById('main')?.scrollTop||0;render();document.getElementById('main').scrollTop=y;}
function go(s,id=''){if(!routes.includes(s))return;history.replaceState({skinmate:true,scroll:document.getElementById('main')?.scrollTop||0,saveTab,communityFilter,budgetMode,compareSource},'');screen=s;routeId=id;history.pushState({skinmate:true,scroll:0,saveTab,communityFilter,budgetMode,compareSource},'',`#/${s}${id?'/'+encodeURIComponent(id):''}`);render();document.getElementById('main')?.focus({preventScroll:true});}
function restore(){const savedRoute=history.state||{};saveTab=savedRoute.saveTab==='이벤트'?'이벤트':'병원';communityFilter=savedRoute.communityFilter||'all';budgetMode=savedRoute.budgetMode==='alternatives'?'alternatives':'all';compareSource=savedRoute.compareSource==='saved'?'saved':'hospitals';const [s,id]=location.hash.replace(/^#\//,'').split('/');screen=routes.includes(s)?s:'home';try{routeId=decodeURIComponent(id||'');}catch{routeId='';}if(!state.auth?.loggedIn||!hasLoginSession())screen='login';else if(!state.onboarded)screen='onboarding';render();document.getElementById('main').scrollTop=history.state?.scroll||0;}
window.addEventListener('popstate',restore);window.addEventListener('hashchange',restore);
let profileCategory='',profileTreatmentQuery='';
function profileTreatmentResults(){const q=profileTreatmentQuery.trim().replace(/\s/g,'').toLocaleLowerCase();if(!q)return '<p class="tiny">시술 이름을 입력하면 선택할 수 있는 목록이 나타나요.</p>';const matches=D.treatments.filter(t=>[t.name,...(t.aliases||[])].some(name=>name.replace(/\s/g,'').toLocaleLowerCase().includes(q)));return matches.length?matches.map(t=>button(`<span>${esc(t.name)}</span>${icon(profileDraft.fields.includes(t.id)?'check':'plus')}`,'profile-field',t.id,'treatment-search-option',`aria-pressed="${profileDraft.fields.includes(t.id)}"`)).join(''):'<p class="tiny">일치하는 시술이 없어요. 다른 이름으로 검색해보세요.</p>';}
function profilePage(first){if(!profileDraft)profileDraft=structuredClone(state.profile);const p=profileDraft;const cat=D.concerns.find(c=>c.id===profileCategory);return `${heading(first?'WELCOME, SKINMATE':'MY SKIN PROFILE',first?'평소의 관심사를<br>알려주세요.':'나를 알아가는<br>피부 프로필','관심 있는 분야부터 가볍게 골라보세요.<br>관심사는 언제든 바꿀 수 있어요.')}${section('관심 있는 피부 고민')}<div class="profile-category-grid">${D.concerns.map(c=>{const count=c.items.filter(x=>p.concerns.includes(x)).length;return button(`${icon(c.icon)}<span>${c.name}</span>${count?`<small>${count}</small>`:''}`,'profile-category',c.id,`profile-category ${cat?.id===c.id?'active':''}`,`aria-expanded="${cat?.id===c.id}" aria-controls="profile-concern-details"`);}).join('')}</div><div id="profile-concern-details">${cat?`<fieldset class="profile-details"><legend>${cat.name} 세부 고민</legend><p class="tiny">관심 있는 고민을 여러 개 선택할 수 있어요.</p><div class="chip-row">${cat.items.map(x=>button(x,'profile-concern',x,`chip ${p.concerns.includes(x)?'active':''}`,`aria-pressed="${p.concerns.includes(x)}"`)).join('')}</div></fieldset>`:''}</div>${p.concerns.length?`<div class="profile-selected"><p class="tiny">선택한 고민 · ${p.concerns.length}개</p><div class="chip-row">${p.concerns.map(x=>button(esc(x)+' ×','profile-concern',x,'chip active',`aria-label="${esc(x)} 선택 해제"`)).join('')}</div></div>`:''}${section('관심 시술 · 선택 사항')}<label class="sr-only" for="profile-treatment-search">관심 시술 검색</label><div class="profile-search">${icon('search')}<input id="profile-treatment-search" type="search" value="${esc(profileTreatmentQuery)}" placeholder="시술 이름 검색" autocomplete="off" aria-controls="profile-treatment-results"></div><div id="profile-treatment-results" aria-live="polite">${profileTreatmentResults()}</div>${p.fields.length?`<div class="profile-selected"><p class="tiny">선택한 시술 · ${p.fields.length}개</p><div class="chip-row">${p.fields.map(id=>button(esc(treatment(id).name)+' ×','profile-field',id,'chip active',`aria-label="${esc(treatment(id).name)} 선택 해제"`)).join('')}</div></div>`:''}<label class="field" for="profile-skin-type">피부 타입</label><select id="profile-skin-type">${['','건성','지성','복합성','중성','민감성','잘 모르겠어요'].map(x=>`<option value="${x}" ${p.skinType===x?'selected':''}>${x||'선택 안 함'}</option>`).join('')}</select><label class="field" for="profile-region">선호 지역</label><select id="profile-region">${D.regions.map(r=>`<option ${r===p.region?'selected':''}>${r}</option>`).join('')}</select>${first?button('나중에 설정할게요','skip-onboarding','','text-button'):''}`;}
function render(){
 if(!state.auth?.loggedIn||!hasLoginSession())screen='login';else if(!state.onboarded)screen='onboarding';
 document.getElementById('app').setAttribute('data-screen',screen);
 if(screen==='login'){renderLogin();return;}
 if(screen==='onboarding'){renderOnboarding();return;}
 if(renderDecisionScreen())return;
 if(screen==='home'){renderHome();return;}
 if(screen==='community'){renderCommunity();return;}
 if(['hospitals','compare'].includes(screen)&&!selected())screen='treatments';
 if(screen==='onboarding'||screen==='profile'){shell(profilePage(screen==='onboarding'),{title:screen==='profile'?'내 피부 프로필':'',bottom:false,footer:foot(screen==='onboarding'?'관심사 저장하고 시작하기':'피부 프로필 저장하기','save-profile')});return;}
 renderSecondary();
}
function explain(item,type){if(type==='hospital')openReasonSheet(item.id,state.selectedTreatment);else dialog('관련 시술 안내','<p>선택한 세부 고민과 연결된 시술이에요. 병원별 추천 근거는 해당 시술의 평가 후기에서 확인할 수 있어요.</p>');}
function track(key,id){return update(()=>{state[key]=[id,...state[key].filter(x=>x!==id)].slice(0,20);});}
function chooseTreatment(id){if(!treatment(id))return;if(update(()=>{state.selectedTreatment=id;state.compare=[];state.recentTreatments=[id,...state.recentTreatments.filter(x=>x!==id)].slice(0,20);}))go('hospitals');}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,v=el.dataset.value;
 if(a==='navigate'){if(v==='saved'){compareSource='saved';update(()=>{state.compare=state.compare.filter(id=>state.saved.includes(id));});}go(v);}
 else if(a==='back'){if(history.state?.skinmate&&location.hash!=='#/home')history.back();else go('home');}
 else if(a==='about')dialog('안녕하세요, Skinmate예요.','<p>개인맞춤 의사결정을 돕는 포트폴리오 체험 앱입니다. 모든 병원·가격·시술 점수·후기는 가상 정보예요. 원본 브랜드 로고와 심볼을 사용합니다.</p>');
 else if(a==='notifications')dialog('알림','<p>새로운 맞춤 콘텐츠와 상담 준비 소식을 여기에서 확인해요.</p>');
 else if(a==='login'){if(state.auth?.loggedIn)go('my');else go('login');}
 else if(a==='login-provider'){if(!['Apple','카카오','네이버','이메일'].includes(v))return;if(update(()=>{state.auth={loggedIn:true,email:v+' 체험'};state.onboarded=false;})){profileDraft=null;onboardCategories=[];onboardingStep=0;profileCategory='';setLoginSession(true);go('onboarding');}}
 else if(a==='logout'){if(update(()=>{state.auth={loggedIn:false,email:''};})) {setLoginSession(false);go('my');toast('로그아웃했어요.');}}
 else if(a==='explore-category'){exploreCategory=v;repaint();}
 else if(a==='clear-search'){exploreQuery='';exploreCategory='all';repaint();}
 else if(a==='start'){if(update(()=>{state.draft={...structuredClone(SkinmateStorage.initial.draft),region:state.profile.region};state.selectedTreatment='';state.compare=[];}))go('concern');}
 else if(a==='quick'){const c=D.concerns.find(c=>c.items.includes(v));if(!c)return go('concern');if(update(()=>{state.draft={...structuredClone(SkinmateStorage.initial.draft),category:c.id,concern:v,region:state.profile.region};state.selectedTreatment='';state.compare=[];}))go('concern');}
 else if(a==='resume'){budgetMode='all';go(state.draft.priorities.length?'treatments':'concern');}
 else if(a==='history'){if(update(()=>{const h=state.history[Number(v)];state.draft={...h};state.selectedTreatment='';state.compare=[];})){budgetMode='all';go('treatments');}}
 else if(a==='category'){update(()=>{state.draft.category=v;state.draft.concern=v==='other'?'기타 고민':'';state.draft.custom='';state.selectedTreatment='';});repaint();document.getElementById('sub-concerns')?.scrollIntoView({block:'start',behavior:'smooth'});}
 else if(a==='concern'){update(()=>{state.draft.concern=v;state.selectedTreatment='';});repaint();}
 else if(a==='to-priority')go('priority');
 else if(a==='priority'){if(!state.draft.priorities.includes(v)&&state.draft.priorities.length>=3)return toast('최대 3개까지 선택할 수 있어요. 하나를 해제해주세요.');update(()=>{const ps=state.draft.priorities;state.draft.priorities=ps.includes(v)?ps.filter(k=>k!==v):[...ps,v];});repaint();}
 else if(a==='up'){update(()=>{const ps=state.draft.priorities,n=ps.indexOf(v);if(n>0)[ps[n-1],ps[n]]=[ps[n],ps[n-1]];});repaint();}
 else if(a==='find'){if(!state.draft.priorities.length||!state.draft.concern)return;budgetMode='all';if(update(()=>{state.activeConcern=L.resolveConcern(state.draft)?.id||null;state.activeConcernCategory=state.draft.category;state.recommendation=structuredClone(state.draft);state.history=[{...structuredClone(state.draft),date:new Date().toLocaleDateString('ko-KR')},...state.history].slice(0,10);state.selectedTreatment='';state.compare=[];}))go('treatments');}
 else if(a==='treatment'){track('recentTreatments',v);go('treatment',v);}
 else if(a==='hospital-treatment'){const [hid,tid]=v.split(':');if(L.getOffer(hid,tid)){track('recentTreatments',tid);go('treatment',v);}}
 else if(a==='select-treatment')chooseTreatment(v);
 else if(a==='select-current-treatment')chooseTreatment(routeId);
 else if(a==='detail'){track('recentHospitals',v);go('detail',v);}
 else if(a==='hospital-pay')hospitalAction(v);
 else if(a==='hospital-book'||a==='hospital-online'){const [hid,fixedTreatment]=v.split(':'),h=hospital(hid);if(!h)return;const tid=h.treatments.includes(fixedTreatment)?fixedTreatment:h.treatments.includes(state.selectedTreatment)?state.selectedTreatment:h.treatments[0];if(update(()=>{state.bookings=[{hospitalId:h.id,treatmentId:tid,createdAt:new Date().toISOString(),type:'online',date:'',time:''},...(state.bookings||[])].slice(0,20)}))go('completion','booking');}
 else if(a==='event')go('event',v);
 else if(a==='article')go('article',v);
 else if(a==='why-treatment'){const t=L.rankTreatments(D.treatments,D.hospitals,state.draft).find(t=>t.id===v);if(t)explain(t,'treatment');}
 else if(a==='why-hospital'){const h=L.rankHospitals(D.hospitals,state.selectedTreatment,state.draft).find(h=>h.id===v);if(h)explain(h,'hospital');}
 else if(a==='save'||a==='save-event'){const key=a==='save'?'saved':'savedEvents';if(update(()=>{if(a==='save'&&!state.saved.includes(v)){state.savedTreatments=state.savedTreatments||{};state.savedTreatments[v]=hospital(v).treatments.includes(state.selectedTreatment)?state.selectedTreatment:hospital(v).treatments[0];}state[key]=state[key].includes(v)?state[key].filter(x=>x!==v):[...state[key],v];})){repaint();toast(state[key].includes(v)?'찜에 저장했어요.':'찜을 취소했어요.');}}
 else if(a==='compare-toggle'){if(!state.compare.includes(v)&&state.compare.length>=3)return toast('최대 3곳까지 비교할 수 있어요.');update(()=>{state.compare=state.compare.includes(v)?state.compare.filter(x=>x!==v):[...state.compare,v];});repaint();}
 else if(a==='compare'){if(state.compare.length<2)return;compareSource=screen;if(!selected()){const common=D.treatments.find(t=>state.compare.every(id=>hospital(id).treatments.includes(t.id)));if(!update(()=>{state.selectedTreatment=common?.id||'consult';}))return;}go('compare');}
 else if(a==='save-tab'){saveTab=v;history.replaceState({...history.state,saveTab},'');repaint();}
 else if(a==='budget-alternatives'){budgetMode='alternatives';go('treatments');}
 else if(a==='budget-all'){budgetMode='all';history.replaceState({...history.state,budgetMode},'');repaint();toast('예산을 초과하는 후보도 함께 표시하고 있어요.');}
 else if(a==='edit-profile'){profileDraft=structuredClone(state.profile);profileCategory='';profileTreatmentQuery='';go('profile');}
 else if(a==='profile-category'){profileCategory=profileCategory===v?'':v;repaint();}
 else if(a==='profile-concern'||a==='profile-field'){const k=a==='profile-concern'?'concerns':'fields';profileDraft[k]=profileDraft[k].includes(v)?profileDraft[k].filter(x=>x!==v):[...profileDraft[k],v];repaint();}
 else if(a==='save-profile'||a==='skip-onboarding'){const first=!state.onboarded;if(update(()=>{if(a==='save-profile')state.profile=structuredClone(profileDraft);state.onboarded=true;})){profileDraft=null;communityFilter='all';go(first?'home':'my');}}
 else if(a==='community-filter'){communityFilter=v;history.replaceState({...history.state,communityFilter},'');repaint();}
 else if(a==='cancel-booking'||a==='cancel-payment'){const key=a==='cancel-booking'?'bookings':'payments',index=Number(v),record=state[key]?.[index];if(!Number.isInteger(index)||index<0||!record||record.status==='canceled')return;if(update(()=>{state[key][index]={...record,status:'canceled',canceledAt:new Date().toISOString()};})){repaint();toast(a==='cancel-booking'?'예약을 취소했어요. 지난 예약에서 확인할 수 있어요.':'체험 결제를 취소했어요.');}}
 else if(a==='activity'||a==='settings')go(a,v);
 else if(a==='checklist'||a==='open-checklist'){const id=a==='checklist'?routeId:v;if(!hospital(id))return;go('checklist',id);update(()=>{state.checklists[id]=getList();});}
 else if(a==='delete-question'){update(()=>{const l=getList();l.questions.splice(Number(v),1);state.checklists[routeId]=l;});repaint();}
 else if(a==='save-checklist'){if(update(()=>{const l=getList();l.saved=true;state.checklists[routeId]=l;}))toast('상담 기록에 저장했어요.');}
 else if(a==='reset')dialog('이 기기 데이터를 삭제할까요?','<p>관심사·찜·상담 질문을 삭제합니다. 복구할 수 없어요.</p>',()=>{if(update(()=>{state=structuredClone(SkinmateStorage.initial);})){profileDraft=null;go('onboarding');}},'삭제하기');
});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='profile-skin-type'){profileDraft.skinType=t.value;return;}if(t.id==='profile-region'){profileDraft.region=t.value;profileDraft.regions=[t.value,...(profileDraft.regions||[]).filter(r=>r!==t.value)];return;}if(t.id==='region'||t.id==='budget'){update(()=>{state.draft[t.id]=t.value;});return;}if(t.id==='compare-treatment'){update(()=>{state.selectedTreatment=t.value;});repaint();}if(t.id==='notifications')update(()=>{state.notifications=t.checked;});if(t.dataset.question!==undefined){update(()=>{const l=getList();l.questions[Number(t.dataset.question)].done=t.checked;state.checklists[routeId]=l;});repaint();}});
document.addEventListener('input',e=>{if(e.target.id==='profile-treatment-search'){profileTreatmentQuery=e.target.value;document.getElementById('profile-treatment-results').innerHTML=profileTreatmentResults();}if(e.target.id==='custom-concern')update(()=>{state.draft.custom=e.target.value.slice(0,100);});});
document.addEventListener('submit',e=>{if(e.target.id==='explore-search'){e.preventDefault();exploreQuery=String(new FormData(e.target).get('query')||'').trim();repaint();return;}if(e.target.id!=='question-form')return;e.preventDefault();const value=new FormData(e.target).get('question').trim();if(!value)return;if(getList().questions.length>=100)return toast('질문은 최대 100개까지 저장할 수 있어요.');if(update(()=>{const l=getList();l.questions.push({text:value.slice(0,200),done:false});state.checklists[routeId]=l;}))repaint();});
// Initial render runs after all view definitions have loaded.
restore();
// Retain the existing browser integration with the shared comparison route.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({name:'open_hospital_comparison',title:'병원 비교 열기',description:'가상 병원 2~3개를 같은 시술 기준으로 비교합니다. 예약은 접수하지 않습니다.',inputSchema:{type:'object',properties:{hospitalIds:{type:'array',items:{type:'string',enum:D.hospitals.map(h=>h.id)},minItems:2,maxItems:3,uniqueItems:true}},required:['hospitalIds'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const ids=input?.hospitalIds;if(!Array.isArray(ids)||ids.length<2||ids.length>3||new Set(ids).size!==ids.length||ids.some(id=>!hospital(id)))throw Error('유효한 병원을 2~3개 선택해주세요.');const common=D.treatments.find(t=>ids.every(id=>hospital(id).treatments.includes(t.id)));if(!common)throw Error('공통 시술이 없어요.');if(!update(()=>{state.compare=[...ids];state.selectedTreatment=selected()&&ids.every(id=>hospital(id).treatments.includes(selected().id))?selected().id:common.id;}))throw Error('비교 후보를 저장하지 못했어요.');go('compare');return {screen:'compare',hospitalIds:ids,sampleData:true};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

function renderLogin(){
 document.getElementById('app').innerHTML=`<main id="main" class="login-page" tabindex="-1"><div class="login-brand">${brand()}<p class="login-entry-label">로그인 · 회원가입</p><p class="login-kicker">내 피부를 이해하는 가장 가까운 메이트</p><h1>나를 위한 피부 선택,<br>Skinmate와 함께.</h1><p>피부 고민부터 시술과 병원 비교까지<br>내 기준에 맞는 선택을 시작해요.</p></div><div class="login-actions">${[['Apple','apple'],['카카오','kakao'],['네이버','naver'],['이메일','email']].map(([label,key])=>button(`<span class="provider-icon" aria-hidden="true">${key==='apple'?'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M17 12c0-2 1-3 2-4-1-2-3-2-4-2-2 0-3 1-4 1S9 6 7 6C3 6 2 10 3 14c1 4 3 7 5 7 1 0 2-1 3-1s2 1 4 1 4-4 5-6c-2-1-3-2-3-3ZM15 2c-2 0-4 2-4 4 2 0 4-2 4-4Z"/></svg>':key==='kakao'?'<img src="assets/kakao-login.png" alt="">':key==='naver'?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 3h5.5l7 10V3H21v18h-5.5l-7-10v10H3z"/></svg>':'✉'}</span>${label}로 로그인`,'login-provider',label,'provider-button '+key)).join('')}<p class="login-disclosure">포트폴리오 로그인 체험입니다.<br>실제 계정 연결 없이 온보딩으로 이동해요.</p></div></main>`;
 document.title='로그인 · Skinmate';
}
