const D=SkinmateData,L=SkinmateLogic;
let state=SkinmateStorage.load(localStorage,D), screen='home', routeId='', toastTimer;
state.auth=state.auth&&typeof state.auth==='object'?{loggedIn:state.auth.loggedIn===true,email:state.auth.email||''}:{loggedIn:false,email:''};
let exploreQuery='',exploreCategory='all';
let profileDraft=null,saveTab='병원',communityFilter='all',budgetMode='all',compareSource='hospitals';
const routes=['login','onboarding','home','concern','priority','treatments','treatment','hospitals','detail','compare','explore','article','event','community','saved','my','profile','checklist','activity','settings'];
const treatment=id=>D.treatments.find(t=>t.id===id),hospital=id=>D.hospitals.find(h=>h.id===id);
const criterion=k=>D.criteria.find(c=>c.id===k), selected=()=>treatment(state.selectedTreatment);
const money=r=>`${r[0]}~${r[1]}만원`, distance=h=>`${h.location}역 ${h.distance<1?Math.round(h.distance*1000)+'m':h.distance+'km'}`;
function toast(s){const e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3000);}
function openLogin(){const d=document.createElement('dialog');d.innerHTML='<h2>Skinmate 로그인 체험</h2><div class="dialog-body"><p>서버 인증 없이 로그인 화면을 체험해요. 정보는 이 브라우저에만 저장됩니다.</p><form id="login-form"><label class="field">이메일<input name="email" type="email" placeholder="you@example.com" required></label><button class="primary" type="submit">로그인</button></form></div><div class="split-buttons"><button class="secondary" data-close>나중에</button></div>';document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.querySelector('#login-form').addEventListener('submit',e=>{e.preventDefault();const email=new FormData(e.target).get('email');if(update(()=>{state.auth={loggedIn:true,email:String(email).slice(0,120)};})){d.close();repaint();toast('로그인했어요.');}});d.showModal();}
function update(fn){const old=structuredClone(state);fn();try{localStorage.setItem('skinmate-v2',JSON.stringify(state));return true;}catch{state=old;toast('저장하지 못했어요. 브라우저 저장 공간을 확인해 주세요.');return false;}}
function repaint(){const y=document.getElementById('main')?.scrollTop||0;render();document.getElementById('main').scrollTop=y;}
function go(s,id=''){if(!routes.includes(s))return;history.replaceState({skinmate:true,scroll:document.getElementById('main')?.scrollTop||0,saveTab,communityFilter,budgetMode,compareSource},'');screen=s;routeId=id;history.pushState({skinmate:true,scroll:0,saveTab,communityFilter,budgetMode,compareSource},'',`#/${s}${id?'/'+encodeURIComponent(id):''}`);render();document.getElementById('main')?.focus({preventScroll:true});}
function restore(){const savedRoute=history.state||{};saveTab=savedRoute.saveTab==='이벤트'?'이벤트':'병원';communityFilter=savedRoute.communityFilter||'all';budgetMode=savedRoute.budgetMode==='alternatives'?'alternatives':'all';compareSource=savedRoute.compareSource==='saved'?'saved':'hospitals';const [s,id]=location.hash.replace(/^#\//,'').split('/');screen=routes.includes(s)?s:'home';try{routeId=decodeURIComponent(id||'');}catch{routeId='';}if(!state.auth?.loggedIn)screen='login';else if(!state.onboarded)screen='onboarding';render();document.getElementById('main').scrollTop=history.state?.scroll||0;}
window.addEventListener('popstate',restore);window.addEventListener('hashchange',restore);
let profileCategory='',profileTreatmentQuery='';
function profileTreatmentResults(){const q=profileTreatmentQuery.trim().replace(/\s/g,'').toLocaleLowerCase();if(!q)return '<p class="tiny">시술 이름을 입력하면 선택할 수 있는 목록이 나타나요.</p>';const matches=D.treatments.filter(t=>t.name.replace(/\s/g,'').toLocaleLowerCase().includes(q));return matches.length?matches.map(t=>button(`<span>${esc(t.name)}</span>${icon(profileDraft.fields.includes(t.id)?'check':'plus')}`,'profile-field',t.id,'treatment-search-option',`aria-pressed="${profileDraft.fields.includes(t.id)}"`)).join(''):'<p class="tiny">일치하는 시술이 없어요. 다른 이름으로 검색해보세요.</p>';}
function profilePage(first){if(!profileDraft)profileDraft=structuredClone(state.profile);const p=profileDraft;const cat=D.concerns.find(c=>c.id===profileCategory);return `${heading(first?'WELCOME, SKINMATE':'MY SKIN PROFILE',first?'평소의 관심사를<br>알려주세요.':'나를 알아가는<br>피부 프로필','관심 있는 분야부터 가볍게 골라보세요.<br>관심사는 언제든 바꿀 수 있어요.')}${section('관심 있는 피부 고민')}<div class="profile-category-grid">${D.concerns.map(c=>{const count=c.items.filter(x=>p.concerns.includes(x)).length;return button(`${icon(c.icon)}<span>${c.name}</span>${count?`<small>${count}</small>`:''}`,'profile-category',c.id,`profile-category ${cat?.id===c.id?'active':''}`,`aria-expanded="${cat?.id===c.id}" aria-controls="profile-concern-details"`);}).join('')}</div><div id="profile-concern-details">${cat?`<fieldset class="profile-details"><legend>${cat.name} 세부 고민</legend><p class="tiny">관심 있는 고민을 여러 개 선택할 수 있어요.</p><div class="chip-row">${cat.items.map(x=>button(x,'profile-concern',x,`chip ${p.concerns.includes(x)?'active':''}`,`aria-pressed="${p.concerns.includes(x)}"`)).join('')}</div></fieldset>`:''}</div>${p.concerns.length?`<div class="profile-selected"><p class="tiny">선택한 고민 · ${p.concerns.length}개</p><div class="chip-row">${p.concerns.map(x=>button(esc(x)+' ×','profile-concern',x,'chip active',`aria-label="${esc(x)} 선택 해제"`)).join('')}</div></div>`:''}${section('관심 시술 · 선택 사항')}<label class="sr-only" for="profile-treatment-search">관심 시술 검색</label><div class="profile-search">${icon('search')}<input id="profile-treatment-search" type="search" value="${esc(profileTreatmentQuery)}" placeholder="시술 이름 검색" autocomplete="off" aria-controls="profile-treatment-results"></div><div id="profile-treatment-results" aria-live="polite">${profileTreatmentResults()}</div>${p.fields.length?`<div class="profile-selected"><p class="tiny">선택한 시술 · ${p.fields.length}개</p><div class="chip-row">${p.fields.map(id=>button(esc(treatment(id).name)+' ×','profile-field',id,'chip active',`aria-label="${esc(treatment(id).name)} 선택 해제"`)).join('')}</div></div>`:''}<label class="field" for="profile-region">선호 지역</label><select id="profile-region">${D.regions.map(r=>`<option ${r===p.region?'selected':''}>${r}</option>`).join('')}</select>${first?button('나중에 설정할게요','skip-onboarding','','text-button'):''}`;}
function render(){
 if(!state.auth?.loggedIn)screen='login';else if(!state.onboarded)screen='onboarding';
 if(screen==='login'){renderLogin();return;}
 if(screen==='onboarding'){renderOnboarding();return;}
 if(screen==='home'){renderHome();return;}
 if(screen==='community'){renderCommunity();return;}
 if(['hospitals','compare'].includes(screen)&&!selected())screen='treatments';
 if(screen==='onboarding'||screen==='profile'){shell(profilePage(screen==='onboarding'),{title:screen==='profile'?'내 피부 프로필':'',bottom:false,footer:foot(screen==='onboarding'?'관심사 저장하고 시작하기':'피부 프로필 저장하기','save-profile')});return;}
 if(screen==='home'){shell(`<section class="decision-hero"><img src="assets/symbol.png" alt=""><h2>내게 맞는<br>시술·병원 찾기</h2><p>내 고민과 선택 기준을 알려주시면<br>나에게 맞는 후보를 빠르게 좁혀드려요.</p>${button('맞춤 추천 시작하기 '+icon('arrow'),'start','','primary')}</section>${state.draft.concern?`${section('지난 고민 이어보기')}<button class="saved-checklist" data-action="resume"><span><b>${esc(state.draft.custom||state.draft.concern)}</b><small>${state.draft.priorities.map(k=>criterion(k).name).join(' → ')||'선택 기준을 정해주세요'}</small></span>${icon('arrow')}</button>`:''}${section('지금, 이런 고민이 많아요','<button class="text-button" data-action="navigate" data-value="concern">전체보기 ›</button>')}<div class="chip-row home-concern-chips">${['여드름','넓은 모공','잡티','얼굴 탄력','잔주름','피부톤','홍조','피부결'].map((c,i)=>button(icon(['dots','pore','sun','wave','wave','spark','sun','pore'][i])+c,'quick',c,'chip')).join('')}</div>${section('피부 고민 콘텐츠')}${homeJournal()}${state.history.length?`${section('최근 추천 결과')}${state.history.slice(0,3).map((h,i)=>button(`<span><b>${esc(h.custom||h.concern)}</b><small>${h.region} · ${esc(h.date)}</small></span>${icon('arrow')}`,'history',i,'saved-checklist')).join('')}`:'<div class="info-box">시술명을 몰라도 괜찮아요.<br>고민에서 시작해 나만의 선택 기준을 찾아보세요.</div>'}`);return;}
 if(screen==='concern'){const cat=D.concerns.find(c=>c.id===state.draft.category);shell(`<p class="step">STEP 01 / 02 · 지금의 고민</p><div class="progress"><i style="width:50%"></i></div>${heading('','지금 가장 신경 쓰이는<br>고민은 무엇인가요?','해결하고 싶은 고민을 선택해주세요.')}<div class="concern-grid">${D.concerns.map(c=>`<button class="concern ${cat?.id===c.id?'selected':''}" data-action="category" data-value="${c.id}" aria-pressed="${cat?.id===c.id}"><span class="pictogram">${icon(c.icon)}</span><b>${c.name}</b>${cat?.id===c.id?`<span class="selected-mark">${icon('check')}</span>`:''}</button>`).join('')}</div>${cat?`<div id="sub-concerns">${section('어떤 부분이 고민인가요?')}</div><div class="chip-row">${cat.items.map(x=>button(x,'concern',x,`chip ${state.draft.concern===x?'active':''}`,`aria-pressed="${state.draft.concern===x}"`)).join('')}</div>${cat.id==='other'?`<label class="field" for="custom-concern">고민 직접 입력 · 선택 사항</label><input id="custom-concern" type="text" maxlength="100" value="${esc(state.draft.custom)}" placeholder="예: 무엇부터 상담해야 할지 모르겠어요">`:''}`:''}`,{title:'고민 선택',footer:foot('선택 기준 정하기','to-priority',!state.draft.concern)});return;}
 if(screen==='priority'){shell(`<p class="step">STEP 02 / 02 · 나의 선택 기준</p><div class="progress"><i style="width:100%"></i></div>${heading('','시술과 병원을 고를 때<br>무엇이 가장 중요하세요?','중요한 순서대로 최대 3개를 선택해주세요.')}<div class="priority-summary">${state.draft.priorities.length?state.draft.priorities.map((k,i)=>`<span>${i+1} ${criterion(k).name}</span>`).join('<i>→</i>'):'아직 선택한 기준이 없어요'}</div>${D.criteria.map(c=>{const n=state.draft.priorities.indexOf(c.id);return `<div class="preference ${n>=0?'chosen':''}">${button(`<span class="rank">${n>=0?n+1:'–'}</span>${icon(c.icon)}<span class="pref-copy"><b>${c.name}</b><small>${c.desc}</small></span>`,'priority',c.id,'pref-main',`aria-pressed="${n>=0}"`)}${n>0?button('↑','up',c.id,'order-button',`aria-label="${c.name} 순위 올리기"`):''}</div>`}).join('')}<label class="field" for="budget">예산 · 1회 기준</label><select id="budget">${D.budgets.map(b=>`<option value="${b.id}" ${state.draft.budget===b.id?'selected':''}>${b.label}</option>`).join('')}</select><label class="field" for="region">방문하고 싶은 지역</label><select id="region">${D.regions.map(r=>`<option ${state.draft.region===r?'selected':''}>${r}</option>`).join('')}</select><div class="info-box">예산을 초과해도 다른 조건이 맞는 후보는 함께 보여드려요. 가격·통증·회복 정보는 가상 예시입니다.</div>`,{title:'선택 기준 설정',footer:foot('내게 맞는 시술·병원 보기','find',!state.draft.priorities.length||!state.draft.concern)});return;}
 if(screen==='treatments'){const ranked=L.rankTreatments(D.treatments,D.hospitals,state.draft);let items=ranked;if(budgetMode==='alternatives')items=D.treatments.filter(t=>!L.budgetInfo(t.priceRange,state.draft.budget).exceeded);shell(`${heading('MY PREFERENCE, MY CHOICE',`${esc(state.draft.custom||state.draft.concern||'피부')} 고민과<br>선택 기준으로 찾아봤어요.`,'시술 후보를 먼저 살펴본 뒤 병원을 비교해요.')}<div class="chip-row">${state.draft.priorities.map((k,i)=>`<span class="chip">${i+1}. ${criterion(k).name}</span>`).join('')}${button('조건 수정','navigate','priority','chip')}</div>${budgetRecovery(ranked)}${budgetMode==='alternatives'?'<div class="info-box"><b>예산 안의 다른 고민·관리 선택지</b><br>원래 고민의 대체 치료를 뜻하지 않아요. 고민에 맞는지는 상담이 필요해요.</div>':''}${items.length?items.map((t,i)=>treatmentCard(t,budgetMode==='all'?i:-1)).join(''):`<div class="info-box">먼저 고민을 알려주시면 후보를 좁혀드릴게요.</div>${button('고민 선택하기','navigate','concern','primary')}`}${mockNote()}`,{title:'맞춤 시술 후보'});return;}
 if(screen==='treatment'){const t=treatment(routeId);if(!t){shell('시술 정보를 찾지 못했어요.',{title:'시술 정보'});return;}shell(`${heading('TREATMENT NOTE',t.name,t.description)}<div class="editorial-art ${t.category}"><span>Know your<br>options.</span><img src="assets/symbol.png" alt=""></div>${tags(t.concerns)}<div class="data-row"><span>예상 가격</span><b>${money(t.priceRange)}</b></div><div class="data-row"><span>통증 수준</span><b>${t.painLevel}</b></div><div class="data-row"><span>회복기간</span><b>${t.recoveryTime}</b></div>${section('상담에서 확인할 것')}<div class="info-box">기대하는 변화와 가능한 대안<br>회차·마취·사후 관리 포함 비용<br>회복 중 주의사항과 부작용 대응<br>현재 피부 상태에서 고려할 점</div><p class="subtitle">시술 범위와 피부 상태에 따라 경험은 달라질 수 있어요. 표시된 정보는 학습용 예시입니다.</p>${mockNote()}`,{title:'시술 정보',active:'explore',footer:foot('이 시술을 제공하는 병원 보기','select-current-treatment')});return;}
 if(screen==='hospitals'){const list=L.rankHospitals(D.hospitals,state.selectedTreatment,state.draft);shell(`${heading('다음은, 병원을 비교할 차례',`${selected().name}을 받을 수 있는<br>내 조건과 가까운 병원`,'선택한 기준으로 정렬했어요. 최종 선택은 비교 후 결정하세요.')}<p class="tiny">거리: 선호 지역의 역 기준 예시 · 현재 위치가 아닙니다.</p>${button('시술 다시 선택','navigate','treatments','text-button')}${budgetRecovery(list)}${list.map(hospitalCard).join('')}${mockNote()}`,{title:'맞춤 병원 후보',footer:compareFooter()});return;}
 renderSecondary();
}
function explain(item,type){const ks=state.draft.priorities,ws=[.5,.3,.2],sum=ks.reduce((n,_,i)=>n+ws[i],0);dialog('왜 추천됐나요?',`<p>선호 조건 일치도 <strong>${item.matchScore??'—'}%</strong></p>${ks.map((k,i)=>`<div class="data-row"><span>${i+1}. ${criterion(k).name}</span><b>${item.scores[k]}점 × ${Math.round(ws[i]/sum*100)}%</b></div>`).join('')}<p>가중 합산 후 반올림해요. 1~2개 기준은 선택한 가중치 합으로 나눠 계산합니다.</p><p>가격은 예산 상한과 예상 가격 중간값의 차이, ${type==='treatment'?'거리는 선호 지역 내 제공 병원 수':'거리는 선호 지역 여부와 역 기준 거리'}를 반영합니다.</p><p>나머지 점수는 학습용 가상 정보입니다. 의료적 적합도·효과·안전을 뜻하지 않으며 광고는 점수에 반영하지 않습니다.</p>`);}
function track(key,id){return update(()=>{state[key]=[id,...state[key].filter(x=>x!==id)].slice(0,20);});}
function chooseTreatment(id){if(!treatment(id))return;if(update(()=>{state.selectedTreatment=id;state.compare=[];state.recentTreatments=[id,...state.recentTreatments.filter(x=>x!==id)].slice(0,20);}))go('hospitals');}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,v=el.dataset.value;
 if(a==='navigate'){if(v==='saved'){compareSource='saved';update(()=>{state.compare=state.compare.filter(id=>state.saved.includes(id));});}go(v);}
 else if(a==='back'){if(history.state?.skinmate&&location.hash!=='#/home')history.back();else go('home');}
 else if(a==='about')dialog('안녕하세요, Skinmate예요.','<p>개인맞춤 의사결정을 돕는 포트폴리오 체험 앱입니다. 모든 병원·가격·시술 점수·후기는 가상 정보예요. 원본 브랜드 로고와 심볼을 사용합니다.</p>');
 else if(a==='notifications')dialog('알림','<p>새로운 맞춤 콘텐츠와 상담 준비 소식을 여기에서 확인해요.</p>');
 else if(a==='login'){if(state.auth?.loggedIn)go('my');else go('login');}
 else if(a==='login-provider'){if(!['Apple','카카오','네이버','이메일'].includes(v))return;if(update(()=>{state.auth={loggedIn:true,email:v+' 체험'};}))go('onboarding');}
 else if(a==='logout'){if(update(()=>{state.auth={loggedIn:false,email:''};})) {go('my');toast('로그아웃했어요.');}}
 else if(a==='explore-category'){exploreCategory=v;repaint();}
 else if(a==='clear-search'){exploreQuery='';exploreCategory='all';repaint();}
 else if(a==='start'){if(update(()=>{state.draft={...structuredClone(SkinmateStorage.initial.draft),region:state.profile.region};state.selectedTreatment='';state.compare=[];}))go('concern');}
 else if(a==='quick'){const c=D.concerns.find(c=>c.items.includes(v));if(!c)return go('concern');if(update(()=>{state.draft={...structuredClone(SkinmateStorage.initial.draft),category:c.id,concern:v,region:state.profile.region};state.selectedTreatment='';state.compare=[];}))go('concern');}
 else if(a==='resume'){budgetMode='all';go(state.draft.priorities.length?'treatments':'concern');}
 else if(a==='history'){if(update(()=>{const h=state.history[Number(v)];state.draft={...h};state.selectedTreatment='';state.compare=[];})){budgetMode='all';go('treatments');}}
 else if(a==='category'){update(()=>{state.draft.category=v;state.draft.concern=v==='other'?'기타 고민':'';state.draft.custom='';state.selectedTreatment='';});repaint();document.getElementById('sub-concerns')?.scrollIntoView({block:'start',behavior:'smooth'});}
 else if(a==='concern'){update(()=>{state.draft.concern=v;state.selectedTreatment='';});repaint();}
 else if(a==='to-priority')go('priority');
 else if(a==='priority'){if(!state.draft.priorities.includes(v)&&state.draft.priorities.length>=3)return toast('최대 3개까지 선택할 수 있어요. 하나를 해제해주세요.');update(()=>{const ps=state.draft.priorities;state.draft.priorities=ps.includes(v)?ps.filter(k=>k!==v):[...ps,v];});repaint();}
 else if(a==='up'){update(()=>{const ps=state.draft.priorities,n=ps.indexOf(v);if(n>0)[ps[n-1],ps[n]]=[ps[n],ps[n-1]];});repaint();}
 else if(a==='find'){if(!state.draft.priorities.length||!state.draft.concern)return;budgetMode='all';if(update(()=>{state.history=[{...structuredClone(state.draft),date:new Date().toLocaleDateString('ko-KR')},...state.history].slice(0,10);state.selectedTreatment='';state.compare=[];}))go('treatments');}
 else if(a==='treatment'){track('recentTreatments',v);go('treatment',v);}
 else if(a==='select-treatment')chooseTreatment(v);
 else if(a==='select-current-treatment')chooseTreatment(routeId);
 else if(a==='detail'){track('recentHospitals',v);go('detail',v);}
 else if(a==='event')go('event',v);
 else if(a==='article')go('article',v);
 else if(a==='why-treatment'){const t=L.rankTreatments(D.treatments,D.hospitals,state.draft).find(t=>t.id===v);if(t)explain(t,'treatment');}
 else if(a==='why-hospital'){const h=L.rankHospitals(D.hospitals,state.selectedTreatment,state.draft).find(h=>h.id===v);if(h)explain(h,'hospital');}
 else if(a==='save'||a==='save-event'){const key=a==='save'?'saved':'savedEvents';if(update(()=>{if(a==='save'&&!state.saved.includes(v)){state.savedTreatments=state.savedTreatments||{};state.savedTreatments[v]=hospital(v).treatments.includes(state.selectedTreatment)?state.selectedTreatment:hospital(v).treatments[0];}state[key]=state[key].includes(v)?state[key].filter(x=>x!==v):[...state[key],v];})){repaint();toast(state[key].includes(v)?'찜에 저장했어요.':'찜을 취소했어요.');}}
 else if(a==='compare-toggle'){if(!state.compare.includes(v)&&state.compare.length>=3)return toast('최대 3곳까지 비교할 수 있어요.');update(()=>{state.compare=state.compare.includes(v)?state.compare.filter(x=>x!==v):[...state.compare,v];});repaint();}
 else if(a==='compare'){if(state.compare.length<2)return;compareSource=screen;if(!selected()){const common=D.treatments.find(t=>state.compare.every(id=>hospital(id).treatments.includes(t.id)));if(!update(()=>{state.selectedTreatment=common?.id||'consult';}))return;}go('compare');}
 else if(a==='save-tab'){saveTab=v;history.replaceState({...history.state,saveTab},'');repaint();}
 else if(a==='budget-alternatives'){budgetMode='alternatives';go('treatments');}
 else if(a==='budget-all'){budgetMode='all';history.replaceState({...history.state,budgetMode},'');repaint();toast('예산을 초과하는 후보도 함께 표시하고 있어요.');}
 else if(a==='edit-profile'){profileDraft=structuredClone(state.profile);profileCategory='';profileTreatmentQuery='';go('profile');}
 else if(a==='profile-category'){profileCategory=profileCategory===v?'':v;repaint();}
 else if(a==='profile-concern'||a==='profile-field'){const k=a==='profile-concern'?'concerns':'fields';profileDraft[k]=profileDraft[k].includes(v)?profileDraft[k].filter(x=>x!==v):[...profileDraft[k],v];repaint();}
 else if(a==='save-profile'||a==='skip-onboarding'){const first=!state.onboarded;if(update(()=>{if(a==='save-profile')state.profile=structuredClone(profileDraft);state.onboarded=true;})){profileDraft=null;communityFilter='all';go(first?'home':'my');}}
 else if(a==='community-filter'){communityFilter=v;history.replaceState({...history.state,communityFilter},'');repaint();}
 else if(a==='activity'||a==='settings')go(a,v);
 else if(a==='checklist'||a==='open-checklist'){const id=a==='checklist'?routeId:v;if(!hospital(id))return;go('checklist',id);update(()=>{state.checklists[id]=getList();});}
 else if(a==='delete-question'){update(()=>{const l=getList();l.questions.splice(Number(v),1);state.checklists[routeId]=l;});repaint();}
 else if(a==='save-checklist'){if(update(()=>{const l=getList();l.saved=true;state.checklists[routeId]=l;}))toast('상담 기록에 저장했어요.');}
 else if(a==='reset')dialog('이 기기 데이터를 삭제할까요?','<p>관심사·찜·상담 질문을 삭제합니다. 복구할 수 없어요.</p>',()=>{if(update(()=>{state=structuredClone(SkinmateStorage.initial);})){profileDraft=null;go('onboarding');}},'삭제하기');
});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='profile-region'){profileDraft.region=t.value;return;}if(t.id==='region'||t.id==='budget'){update(()=>{state.draft[t.id]=t.value;});return;}if(t.id==='compare-treatment'){update(()=>{state.selectedTreatment=t.value;});repaint();}if(t.id==='notifications')update(()=>{state.notifications=t.checked;});if(t.dataset.question!==undefined){update(()=>{const l=getList();l.questions[Number(t.dataset.question)].done=t.checked;state.checklists[routeId]=l;});repaint();}});
document.addEventListener('input',e=>{if(e.target.id==='profile-treatment-search'){profileTreatmentQuery=e.target.value;document.getElementById('profile-treatment-results').innerHTML=profileTreatmentResults();}if(e.target.id==='custom-concern')update(()=>{state.draft.custom=e.target.value.slice(0,100);});});
document.addEventListener('submit',e=>{if(e.target.id==='explore-search'){e.preventDefault();exploreQuery=String(new FormData(e.target).get('query')||'').trim();repaint();return;}if(e.target.id!=='question-form')return;e.preventDefault();const value=new FormData(e.target).get('question').trim();if(!value)return;if(getList().questions.length>=100)return toast('질문은 최대 100개까지 저장할 수 있어요.');if(update(()=>{const l=getList();l.questions.push({text:value.slice(0,200),done:false});state.checklists[routeId]=l;}))repaint();});
// Initial render runs after all view definitions have loaded.
restore();
// Retain the existing browser integration with the shared comparison route.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({name:'open_hospital_comparison',title:'병원 비교 열기',description:'가상 병원 2~3개를 같은 시술 기준으로 비교합니다. 예약은 접수하지 않습니다.',inputSchema:{type:'object',properties:{hospitalIds:{type:'array',items:{type:'string',enum:D.hospitals.map(h=>h.id)},minItems:2,maxItems:3,uniqueItems:true}},required:['hospitalIds'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const ids=input?.hospitalIds;if(!Array.isArray(ids)||ids.length<2||ids.length>3||new Set(ids).size!==ids.length||ids.some(id=>!hospital(id)))throw Error('유효한 병원을 2~3개 선택해주세요.');const common=D.treatments.find(t=>ids.every(id=>hospital(id).treatments.includes(t.id)));if(!common)throw Error('공통 시술이 없어요.');if(!update(()=>{state.compare=[...ids];state.selectedTreatment=selected()&&ids.every(id=>hospital(id).treatments.includes(selected().id))?selected().id:common.id;}))throw Error('비교 후보를 저장하지 못했어요.');go('compare');return {screen:'compare',hospitalIds:ids,sampleData:true};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

function renderLogin(){
 document.getElementById('app').innerHTML=`<main id="main" class="login-page" tabindex="-1"><div class="login-brand"><img src="assets/logo.jpg" alt="Skinmate" class="login-logo"><p class="login-kicker">내 피부를 이해하는 가장 가까운 메이트</p><h1>나를 위한 피부 선택,<br>Skinmate와 함께.</h1><p>피부 고민부터 시술과 병원 비교까지<br>내 기준에 맞는 선택을 시작해요.</p></div><div class="login-actions">${[['Apple','apple'],['카카오','kakao'],['네이버','naver'],['이메일','email']].map(([label,key])=>button(`<span class="provider-icon" aria-hidden="true">${key==='apple'?'<svg viewBox="0 0 24 24" fill="currentColor"><path d="M17 12c0-2 1-3 2-4-1-2-3-2-4-2-2 0-3 1-4 1S9 6 7 6C3 6 2 10 3 14c1 4 3 7 5 7 1 0 2-1 3-1s2 1 4 1 4-4 5-6c-2-1-3-2-3-3ZM15 2c-2 0-4 2-4 4 2 0 4-2 4-4Z"/></svg>':key==='kakao'?'<img src="assets/kakao-login.png" alt="">':key==='naver'?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 3h5.5l7 10V3H21v18h-5.5l-7-10v10H3z"/></svg>':'✉'}</span>${label}로 로그인`,'login-provider',label,'provider-button '+key)).join('')}<p class="login-disclosure">포트폴리오 로그인 체험입니다.<br>실제 계정 연결 없이 온보딩으로 이동해요.</p></div></main>`;
 document.title='로그인 · Skinmate';
}
