const paths={bookmark:'M6 3h12v19l-6-4-6 4Z',home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',user:'M20 21v-2a6 6 0 0 0-6-6h-4a6 6 0 0 0-6 6v2M16 5a4 4 0 1 1-8 0 4 4 0 0 1 8 0',arrow:'M4 12h16m-6-6 6 6-6 6',back:'m15 5-7 7 7 7',check:'m5 12 4 4L19 6',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M18 6 6 18',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z',sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',wave:'M3 7c3-6 6 6 9 0s6 6 9 0M3 12c3-6 6 6 9 0s6 6 9 0M3 17c3-6 6 6 9 0s6 6 9 0',dots:'M7 7h.01M16 5h.01M12 12h.01M5 16h.01M18 17h.01',pore:'M12 3v7m-5-4a8 8 0 1 0 10 0M8 12a4 4 0 0 0 8 0',clock:'M12 7v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',coin:'M21 6c0 2-4 4-9 4S3 8 3 6s4-4 9-4 9 2 9 4ZM3 6v12c0 2 4 4 9 4s9-2 9-4V6M3 12c0 2 4 4 9 4s9-2 9-4',bolt:'m13 2-9 12h7l-1 8 10-13h-7Z',clinic:'M4 22V4h16v18M1 22h22M8 8h2m4 0h2M8 12h2m4 0h2M10 22v-6h4v6',shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6Zm-5 10 3 3 7-7',list:'M9 6h12M9 12h12M9 18h12M3 6h.01M3 12h.01M3 18h.01',sliders:'M4 21v-8m0-5V3m8 18v-5m0-5V3m8 18V11m0-5V3M1 8h6m2 8h6m2-10h6',info:'M12 11v6m0-10h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0'};
paths.bell='M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4';
paths.car='M5 16H3v-5l2-5h14l2 5v5h-2M5 16h14M5 16v2m14-2v2M3 11h18M7 14h.01M17 14h.01';
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true" ${n==='dots'?'style="stroke-width:4;stroke-linecap:round"':''}><path d="${paths[n]||paths.spark}"/></svg>`;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function button(label,action,value='',cls='secondary',extra=''){return `<button class="${cls}" data-action="${action}" data-value="${esc(value)}" ${extra}>${label}</button>`;}
function nav(active){return `<nav class="bottom-nav" aria-label="주요 메뉴">${[['home','home','홈'],['explore','search','탐색'],['community','list','커뮤니티'],['saved','bookmark','찜'],['my','user','마이페이지']].map(([s,i,l])=>button(`${icon(i)}<span>${l}</span>`,'navigate',s,`nav-item ${active===s?'active':''}`,active===s?'aria-current="page"':'')).join('')}</nav>`;}
function header(title){return `<header class="app-header">${title?`<div class="header-back">${button(icon('back'),'back','','icon-button','aria-label="뒤로 가기"')}<span class="header-title">${esc(title)}</span></div>`:'<div class="brand-home"><div class="logo-crop" role="img" aria-label="Skinmate"><img src="assets/logo.jpg" alt=""></div><small>좋은 피부가, 좋은 하루를 만든다</small></div>'}<div class="header-actions">${screen==='my'?button(icon('sliders'),'settings','전체','icon-button','aria-label="설정"'):''}${button(icon('bell'),'notifications','','icon-button','aria-label="알림"')}</div></header>`;}
function foot(label,action,disabled=false){return `<div class="footer-action">${button(label+icon('arrow'),action,'','primary',disabled?'disabled':'')}</div>`;}
function shell(body,{title='',footer='',active='home',bottom=true}={}){document.getElementById('app').innerHTML=(screen==='home'?'':header(title))+`<main class="main route-enter" id="main" tabindex="-1">${body}</main>`+footer+(bottom?nav(active):'');document.title=(title?title+' · ':'')+'Skinmate';}
function heading(kicker,title,desc=''){return `<p class="greeting">${kicker}</p><h1>${title}</h1>${desc?`<p class="subtitle">${desc}</p>`:''}`;}
function section(title,action=''){return `<div class="section-heading"><h2>${title}</h2>${action}</div>`;}
function tags(items){return `<div class="chip-row">${items.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>`;}
function mockNote(){return '<p class="sample-note">학습용 가상 병원·가격·후기입니다.<br>후기는 실제 환자 경험이 아닌 체험용 평가 데이터입니다.</p>';}
function dialog(title,body,onConfirm,label='확인'){const d=document.createElement('dialog');d.innerHTML=`<h2>${esc(title)}</h2><div class="dialog-body">${body}</div><div class="split-buttons"><button class="secondary" data-close>닫기</button>${onConfirm?`<button class="primary" data-confirm>${esc(label)}</button>`:''}</div>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();if(onConfirm)d.querySelector('[data-confirm]').onclick=()=>{onConfirm();d.close();};d.addEventListener('close',()=>d.remove());d.showModal();}
function budgetBadge(range){const b=L.budgetInfo(range,state.draft.budget);return b.exceeded?`<p class="budget-warning">설정한 예산보다 약 ${b.minOver}~${b.maxOver}만원 높아요.</p>`:b.partial?'<p class="budget-warning">시술 범위에 따라 예산을 초과할 수 있어요.</p>':'';}
function promotionCard(p){const saved=state.savedEvents.includes(p.id);return `<article class="promotion-card"><div class="editorial-art ${p.category}"><span>Skinmate<br>Care notes</span><img src="assets/symbol.png" alt=""></div><div class="promotion-body"><span class="ad-label">프로모션 · 가상 광고</span><h2>${p.title}</h2><p>${hospital(p.hospitalId).name} · ${p.region}</p>${offerPrice(p)}<div class="split-buttons">${button('혜택 확인','event',p.id)}${button(icon('bookmark')+(saved?'이벤트 찜 취소':'이벤트 찜'),'save-event',p.id,'secondary',`aria-pressed="${saved}"`)}</div></div></article>`;}
function reviewCard(r){return `<article class="review"><div class="review-meta"><span>메이트 · 가상 후기</span><time>${r.date}</time></div><h2>${treatment(r.treatmentId).name}</h2>${tags([r.concern,`만족도 ${r.satisfaction}/5`])}<div class="mini-facts"><span>가격<b>${r.price}만원</b></span><span>통증 경험<b>${r.pain}</b></span><span>회복기간<b>${r.recovery}</b></span></div><p>${r.text}</p>${button('관련 시술 살펴보기','treatment',r.treatmentId,'text-button')}</article>`;}
function compareFooter(){return foot(`선택한 병원 비교하기 (${state.compare.length}/3)`,'compare',state.compare.length<2);}
function interests(){return D.concerns.filter(c=>c.items.some(x=>state.profile.concerns.includes(x))).map(c=>c.id);}
function budgetRecovery(items){if(!items.length||items.some(t=>!t.budget.exceeded))return '';return `<div class="budget-panel"><b>현재 예산에 꼭 맞는 후보는 많지 않아요.</b><p>다른 조건과 잘 맞는 선택지를 찾아봤어요.</p>${button('예산 범위 넓히기','navigate','priority')}${button('현재 예산으로 가능한 다른 선택 보기','budget-alternatives')}${button('예산을 초과하는 후보도 보기','budget-all')}</div>`;}
function setting(label,action,value){const key=({'알림':'bell','개인정보':'shield','고객센터':'headset','로그아웃':'user','로그인':'user'})[label]||'gear';return button(`<span class="my-row-label">${icon(key)}<span>${label}</span></span>`,action,value,'settings-row');}

function homeJournal(){const list=state.profile.concerns.length?D.concerns.filter(c=>c.items.some(x=>state.profile.concerns.includes(x))):D.concerns;return '<div class="home-journal">'+list.map(c=>button('<small>피부 고민 가이드</small><b>'+c.name+', 상담 전 무엇을 물어볼까요?</b>'+icon('arrow'),'article',c.id,'journal-card')).join('')+'</div>';}
function renderExplore(){const cats=interests();const score=p=>Number(cats.includes(p.category))*4+Number(state.profile.fields.includes(p.treatmentId))*3+Number(p.region===state.profile.region);const all=[...D.promotions].sort((a,b)=>score(b)-score(a));const items=all.filter(p=>(exploreCategory==='all'||p.category===exploreCategory)&&[p.title,p.region,hospital(p.hospitalId).name,treatment(p.treatmentId).name,...treatment(p.treatmentId).concerns].join(' ').includes(exploreQuery));shell(`<form class="explore-search" id="explore-search"><input name="query" type="search" value="${esc(exploreQuery)}" placeholder="이벤트, 병원, 관심 고민 검색" aria-label="이벤트와 병원 검색"><button type="submit" aria-label="검색">${icon('search')}</button></form>${heading('DISCOVER YOUR INTERESTS','관심에 꼭 맞는 혜택을<br>발견해보세요.','이벤트부터 병원 소식까지, 나의 관심사로 둘러보세요.')}${button('관심사 변경','edit-profile','','text-button')}<div class="explore-filters">${button('전체','explore-category','all','chip '+(exploreCategory==='all'?'active':''))}${D.concerns.filter(c=>all.some(p=>p.category===c.id)).map(c=>button(c.name,'explore-category',c.id,'chip '+(exploreCategory===c.id?'active':''))).join('')}</div><p class="tiny">관심 고민 · 관심 시술 · 선호 지역 순으로 모았어요.<br>모든 프로모션과 병원 홍보는 학습용 가상 광고입니다.</p><div class="discovery-grid">${items.map(p=>{const h=hospital(p.hospitalId);return `<article class="discovery-card"><button class="promo-art ${p.category}" data-action="event" data-value="${p.id}"><small>프로모션 · 가상 광고</small><strong>${treatment(p.treatmentId).name}</strong><span>나를 위한 케어 혜택</span><b>${p.price}<small>만원</small></b>${icon('spark')}</button><p>${h.name} · ${p.region}</p><h2>${button(esc(p.title),'event',p.id,'text-button')}</h2><b class="event-price">${offerPrice(p)}</b><small>포함 비용은 상세에서 확인</small>${button(icon('bookmark')+(state.savedEvents.includes(p.id)?'저장됨':'이벤트 찜'),'save-event',p.id,'text-button',`aria-pressed="${state.savedEvents.includes(p.id)}"`)}</article>`;}).join('')}</div>${!items.length?'<div class="info-box">검색한 조건의 이벤트가 아직 없어요. 다른 고민이나 지역도 살펴보세요.'+button('전체 이벤트 보기','clear-search')+'</div>':''}${section('관심 지역의 병원 소식')}<div class="hospital-news">${D.hospitals.filter(h=>h.location===state.profile.region).map(h=>button('<span class="ad-label">병원 홍보 · 가상 광고</span><h2>'+h.name+'</h2><p>'+h.location+' · 상담 전 비용과 관리 안내를 살펴보세요.</p>'+icon('arrow'),'detail',h.id,'news-card')).join('')}</div>`,{active:'explore'});}

function offerPrice(o){const won=n=>(n*10000).toLocaleString('ko-KR')+'원';return `<span class="offer-price">${o.originalPrice>o.price?`<del aria-label="할인 전 가격">${won(o.originalPrice)}</del><strong class="discount" aria-label="할인 가격">${won(o.price)}</strong>`:`<strong>${won(o.price)}</strong>`}</span>`;}
function hospitalPrices(h,id){const ids=id&&h.exactOffers[id]?[id]:h.treatments;return `<div class="hospital-offers">${ids.map(tid=>`<div class="hospital-offer"><span>${treatment(tid).name}<small>${h.exactOffers[tid].unit}</small></span>${offerPrice(h.exactOffers[tid])}</div>`).join('')}</div>`;}
