/* Connected decision views. Reuses shell, routing, persistence and bookmark actions. */
let hospitalTreatmentLimit=5,treatmentLimit=4,exploreLimit=5,reviewLimit=8,showAllHospitalRegions=false;
const concernById=id=>D.subConcerns.find(c=>c.id===id);
function activeConcernRecord(){return concernById(state.activeConcern)||D.subConcerns.find(c=>state.profile.concerns.includes(c.name))||null;}
function activePreferences(){const c=activeConcernRecord();return state.activeConcern&&state.recommendation?{...state.recommendation,concernId:c.id}:{category:c?.categoryId||'',concern:c?.name||'',concernId:c?.id||'',priorities:[],region:state.profile.region,budget:'unknown'};}
function concernPath(c){return c?`${D.concerns.find(x=>x.id===c.categoryId).name} <span aria-hidden="true">/</span> ${c.name}`:'';}
function imageFor(t,concernId){const c=concernById(concernId);const key=c&&t?.concernIds.includes(c.id)?c.imageCategory:t?.imageCategory||'clinic';return ({jawline:'assets/photos/skin.webp',lifting:'assets/photos/skin.webp',pigment:'assets/photos/pigment.webp',texture:'assets/photos/texture.webp',clinic:'assets/photos/clinic.webp'})[key]||`assets/concerns/${key}.svg`;}
function treatmentImage(t,concernId,cls=''){const src=imageFor(t,concernId);return `<img class="${cls}" src="${src}" alt="${esc(t?.name||'병원 공간')} ${src.endsWith('.svg')?'관련 일러스트':'분위기 예시'}" loading="lazy" width="360" height="240">`;}
function header(title){const detail=screen==='detail',h=detail?hospital(routeId):null;const back=!!title||['detail','concern','priority','subconcern','hospital-reviews'].includes(screen);const region=`<label class="region-control">${icon('pin')}<span class="sr-only">탐색 지역</span><select id="explore-region">${['전체',...D.regions].map(r=>`<option ${r===(exploreRegion||state.profile.region)?'selected':''}>${r}</option>`).join('')}</select></label>`;return `<header class="app-header${h?' hospital-detail-header':''}">${back?`<div class="header-back">${button(icon('back'),'back','','icon-button','aria-label="뒤로 가기"')}${h?'':`<span class="header-title">${esc(title)}</span>`}</div>`:screen==='my'?'<strong>마이페이지</strong>':screen==='saved'?'<strong>찜</strong>':brand()}${h?`<strong class="header-title detail-header-name">${esc(h.name)}</strong>`:''}<div class="header-actions">${screen==='explore'?region:''}${h?button(icon('bookmark'),'save',h.id,'icon-button '+(state.saved.includes(h.id)?'is-saved':''),`aria-label="병원 저장" aria-pressed="${state.saved.includes(h.id)}"`):screen==='my'?button(icon('gear'),'settings','전체','icon-button','aria-label="설정"'):button(icon('bell'),'notifications','','icon-button','aria-label="알림"')}</div></header>`;}
function ConcernCategoryCard(c){return button(`<span class="category-illustration">${icon(c.icon)}</span><b>${c.name}</b>`,'decision-category',c.id,'decision-category '+(state.draft.category===c.id?'selected':''),`aria-pressed="${state.draft.category===c.id}"`);}
function SubConcernCard(c){return button(`${esc(c.name)}${state.draft.concern===c.name?icon('check'):''}`,'decision-concern',c.id,'subconcern-card '+(state.draft.concern===c.name?'selected':''),`aria-pressed="${state.draft.concern===c.name}"`);}
function PriorityCard(c){const n=state.draft.priorities.indexOf(c.id);return `<div class="preference ${n>=0?'chosen':''}">${button(`<span class="rank">${n>=0?n+1:'–'}</span>${icon(c.icon)}<b>${c.name}</b>`,'priority',c.id,'pref-main',`aria-pressed="${n>=0}"`)}</div>`;}
function TreatmentRecommendationCard(t){return `<article class="treatment-card connected-treatment">${treatmentImage(t,L.resolveConcern(state.draft)?.id)}<div class="treatment-copy"><h2>${esc(t.name)}</h2><p>${esc(t.summary)}</p><b>${money(t.priceRange)}</b><small class="muted"> · 일반 범위 예시</small>${tags(t.tags.slice(0,2))}<div class="split-buttons">${button('시술 정보','treatment',t.id,'secondary')}${button('이 시술 병원 보기','decision-hospitals',t.id,'primary')}</div></div></article>`;}
function treatmentCard(t){return TreatmentRecommendationCard(t);}
function reviewRating(g){return g.count?`★ ${g.rating.toFixed(1)} · 후기 ${g.count}개`:'아직 평가 후기가 없어요';}
function HospitalRecommendationCard(h,tid,prefs=state.draft,compact=false){const t=treatment(tid);if(!t)return '';const o=L.getOffer(h.id,tid,L.resolveConcern(prefs)?.id);if(!o)return '';const g=L.aggregateReviews(h.id,tid),saved=state.saved.includes(h.id)&&state.savedTreatments[h.id]===tid;return `<article class="hospital-card connected-hospital ${compact?'compact':''}" data-action="offer-detail" data-value="${h.id}:${tid}" role="link" tabindex="0" aria-label="${esc(h.name)} ${esc(t.name)} 상세 보기"><div class="hospital-cover"><img src="assets/photos/clinic.webp" alt="병원 공간 분위기 예시" loading="lazy" width="360" height="240"><span class="stock-label">공간 예시</span>${button(icon('bookmark'),'save-offer',h.id+':'+tid,'bookmark-button '+(saved?'is-saved':''),`aria-label="${esc(h.name)} 저장" aria-pressed="${saved}"`)}</div><div class="hospital-copy"><h3>${esc(h.name)}</h3><p class="rating-line">${reviewRating(g)}</p><p class="muted">${distance(h)} · 역 기준</p><b class="hospital-treatment-name">${esc(t.name)}</b>${offerPrice(o)}<small class="muted">${o.unit}</small>${button('<i aria-hidden="true"></i>왜 추천됐나요?','decision-reason',h.id+':'+tid,'reason-link')}${screen==='saved'?button(icon(state.compare.includes(h.id)?'check':'plus')+' 비교 선택','compare-toggle',h.id,'text-button',`aria-pressed="${state.compare.includes(h.id)}"`):''}</div></article>`;}
function hospitalCard(h){const id=screen==='saved'?state.savedTreatments[h.id]:h.treatments.includes(state.selectedTreatment)?state.selectedTreatment:h.treatments[0];return HospitalRecommendationCard(h,id||h.treatments[0]);}
function HospitalTreatmentRow(h,t){const o=L.getOffer(h.id,t.id,L.resolveConcern(state.draft)?.id);return `<article class="hospital-treatment-row">${treatmentImage(t)}<div><h3>${button(esc(t.name),'hospital-treatment',h.id+':'+t.id,'text-button')}</h3><p>${esc(t.summary)}</p>${offerPrice(o)}<small>${o.unit}</small><span class="row-tag">${esc(t.modality)}</span></div></article>`;}
function ReviewCard(r){const t=treatment(r.treatmentId),h=hospital(r.hospitalId);return `<article class="review connected-review"><div class="review-top"><b>${esc(r.userId||'메이트')}</b><time>${esc(r.createdAt||r.date)}</time></div><p class="rating-line">★ ${Number(r.overallRating).toFixed(1)} · ${esc(t.name)}</p><small class="muted">${esc(h.name)} · ${(r.price*10000).toLocaleString('ko-KR')}원 · 체험 후기</small><p>${esc(r.content)}</p>${r.pros?`<p class="review-comment"><b>좋았던 점</b> ${esc(r.pros)}</p><p class="review-comment"><b>아쉬웠던 점</b> ${esc(r.cons)}</p>`:''}<details class="review-evaluations"><summary>추천에 반영된 평가 보기</summary><div>${D.criteria.map(c=>`<span>${c.name}<b>${r[L.fields[c.id]]} / 5</b></span>`).join('')}</div><small>통증·회복·거리는 부담이 적고 만족할수록 높은 평가예요.</small></details></article>`;}
function reviewCard(r){return ReviewCard(r);}function storyCard(r){return ReviewCard(r);}
function ReasonSheetContent(hid,tid,prefs=state.draft){const t=treatment(tid),g=L.aggregateReviews(hid,tid);return `<p class="muted">${esc(hospital(hid).name)} · ${esc(t.name)}</p><p class="rating-line">${reviewRating(g)}</p><ul class="reason-points">${L.reasonLines(hid,tid,prefs).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="tiny">이 병원의 해당 시술 평가만 집계했어요. 선택한 기준 순서로 비교하며 후기가 적을수록 근거를 보수적으로 반영해요. 실제 의료 적합성 판단이 아닌 가상 후기 기반 비교입니다.</p>${button('관련 후기 보기','decision-reviews',hid+':'+tid,'primary')}`;}
function openReasonSheet(hid,tid){const d=document.createElement('dialog');d.className='recommendation-sheet';d.setAttribute('aria-labelledby','reason-title');d.innerHTML=`<div class="sheet-handle" aria-hidden="true"></div><div class="sheet-heading"><h2 id="reason-title">왜 추천됐나요?</h2><button data-close aria-label="닫기">${icon('close')}</button></div>${ReasonSheetContent(hid,tid,screen==='home'?activePreferences():state.draft)}`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close();});d.addEventListener('close',()=>d.remove());d.showModal();}
const topicKnowledge={
 squareJaw:['근육·지방·뼈, 사각턱 원인은 다를 수 있어요','저작근의 발달 여부를 확인하는 상담과 지방·뼈 윤곽에 대한 상담은 구분해요. 보톡스는 모든 사각턱 원인을 해결하는 방법이 아니에요.','보톡스 상담에서는 무엇을 물어볼까요?','제품명과 용량, 씹는 느낌의 변화 가능성, 반복 시술 계획을 물어보세요.'],
 cheekFat:['볼살과 피부 처짐을 구분해요','지방의 위치와 양, 피부 처짐을 함께 평가한 뒤 후보를 비교해요.','볼살 상담 전에 확인할 점은?','원하는 변화의 범위와 볼 꺼짐 가능성, 적용 핸드피스를 확인하세요.'],
 doubleChin:['이중턱, 턱 밑만 보고 결정하지 않아요','지방·피부 탄력·턱 구조를 함께 살펴보는 상담이 필요해요.','턱 밑 시술 비용은 무엇에 따라 달라지나요?','부위·에너지량·횟수와 마취 및 사후 관리 포함 여부를 확인하세요.'],
 acneScar:['패인 여드름 흉터란?','흉터의 모양과 깊이에 따라 레이저·미세침·박리 등 상담 방법이 달라질 수 있어요. 현재 염증 치료도 함께 확인해요.','흉터 치료는 한 가지 방법만 사용하나요?','흉터 유형에 따라 여러 방법을 함께 고려하기도 해요. 예상 회차와 회복 계획을 상담하세요.'],
 pittedScar:['패인 흉터의 모양부터 살펴봐요','좁고 깊은 흉터와 넓고 완만한 흉터는 상담 방법이 다를 수 있어요.','유착 여부를 왜 확인하나요?','유착 박리 같은 방법을 고려할지 평가하기 위해서예요. 시술 여부는 진료에서 결정해요.'],
 acne:['진행 중인 여드름과 흉터는 구분해요','현재 염증과 면포를 먼저 평가하고 약물·관리·시술 필요성을 상담해요.','압출만 받으면 되나요?','염증과 재발 원인에 따라 추가 치료가 필요할 수 있어요. 기존 치료 이력을 알려주세요.'],
 sebum:['피지와 모공, 같은 고민일까요?','피지 분비와 모공의 크기는 서로 관련될 수 있지만 같은 목표의 관리로 단정하지 않아요.','피지 관리 전에 확인할 점은?','압출·필링 구성과 자극 정도, 집에서 사용하는 제품을 함께 상담하세요.'],
 pores:['모공 크기와 피부결을 함께 살펴봐요','피지·피부 탄력·흉터 여부에 따라 비교하는 방법이 달라질 수 있어요.','모공 시술을 고를 때 무엇이 중요한가요?','원하는 변화, 팁·모드, 회복 일정과 반복 회차를 비교하세요.'],
 melasma:['기미와 잡티는 치료 계획이 다를 수 있어요','기미는 원인 평가와 자외선 관리, 약물 치료 등을 함께 상담해요. 레이저 여부를 먼저 확정하지 않아요.','기미 토닝 전에 무엇을 물어볼까요?','색소가 진해질 가능성과 사후 관리, 약물 병행 필요성을 확인하세요.'],
 redness:['홍조의 원인을 먼저 확인해요','혈관성 붉음과 자극·염증으로 인한 붉음을 구분하는 진료가 우선이에요.','혈관 레이저를 바로 받아도 되나요?','홍조의 원인을 확인한 뒤 치료 방법과 자극 관리부터 상담하세요.']
};
function knowledgeFor(c){if(topicKnowledge[c.id])return topicKnowledge[c.id];const group={contour:['지방·근육·처짐 등 고민의 원인을 구분한 뒤 비교해요.','적용 부위와 방법은 어떻게 정하나요?','원하는 윤곽 변화와 과도한 볼륨 감소 가능성을 상담하세요.'],aging:['초음파·고주파·주사 등은 진행 방식과 목표가 달라요.','리프팅 장비는 어떻게 비교하나요?','적용 깊이·팁·샷 수와 회복 계획을 같은 기준으로 비교하세요.'],trouble:['진행 중인 염증과 남은 자국·흉터를 구분하는 상담이 필요해요.','자국과 흉터는 같은 방식으로 관리하나요?','피부색 변화인지 표면의 함몰인지 확인한 뒤 치료 방법을 상담하세요.'],texture:['클렌징 관리와 미세침·레이저는 목표와 회복 부담이 달라요.','관리와 시술은 어떻게 구분하나요?','피지 관리인지 피부결 변화인지 목표를 정하고 자극 정도를 비교하세요.'],tone:['색소의 종류와 피부 상태를 확인한 후 빛·레이저·관리 방법을 상담해요.','레이저 후 어떤 관리가 필요한가요?','자외선 관리와 자극을 줄이는 방법, 색소 변화 가능성을 물어보세요.'],hair:['털의 굵기·색과 피부 상태, 부위에 따라 장비와 회차를 상담해요.','제모 전에 털을 뽑아도 되나요?','제모 준비 방법과 면도 시점은 방문할 병원의 안내를 확인하세요.'],other:['현재 상태와 이전 치료 경험을 정리하면 상담에 도움이 돼요.','시술 이름을 몰라도 상담할 수 있나요?','신경 쓰이는 변화와 언제 시작됐는지 알려주세요.']}[c.categoryId];return [`${c.name}, 상담에서 확인할 것`,...group];}
function KnowledgeCard(c){const k=knowledgeFor(c);return `<article class="knowledge-card"><small>SKIN KNOWLEDGE</small><h3>${esc(k[0])}</h3><p>${esc(k[1])}</p>${button('자세히 읽기','article',c.id,'text-button')}</article>`;}
function homeContent(){const c=activeConcernRecord(),prefs=activePreferences();if(!c)return {c,prefs,treatments:[],hospitals:[],events:[]};const ts=L.rankTreatments(D.treatments,D.hospitals,prefs);const hs=[];for(const t of ts)for(const h of L.rankHospitals(D.hospitals,t.id,prefs)){if(h.location===prefs.region&&!hs.some(x=>x.h.id===h.id))hs.push({h,t});}return {c,prefs,treatments:ts,hospitals:hs,events:D.promotions.filter(p=>ts.some(t=>t.id===p.treatmentId)&&p.region===prefs.region)};}
function renderHome(){const x=homeContent(),c=x.c,k=c?knowledgeFor(c):null;const headline=c?`${esc(c.name)},<br>지금, 더 좋은 선택이<br>기다리고 있어요.`:'내 고민에 맞는<br>시술을<br>찾아볼까요?';const support=c?`${esc(c.name)} 고민을 해결하고,<br>더 또렷한 나를 위한 맞춤 정보.<br>병원과 시술을 만나보세요.`:'중요하게 생각하는 기준을 바탕으로<br>나에게 맞는 시술과 병원을 찾아드려요.';shell(`<section class="home-editorial-hero">${header('')}<img class="home-hero-portrait" src="assets/home-hero-portrait.webp" alt="볼에 크림을 바른 인물" width="1024" height="1536" fetchpriority="high"><div class="hero-copy"><span class="hero-eyebrow">YOUR SKIN, YOUR CHOICE</span><h1>${headline}</h1><p>${support}</p>${button('나에게 맞는 병원·시술 보기','personalized-home','','primary')}</div><span class="image-label">이미지 예시</span></section><div class="home-info-surface">${c?`${section(esc(c.name)+' 고민이라면?',button('전체보기','navigate','explore','text-button'))}<p class="section-caption">${x.prefs.region} · 해당 시술의 후기와 가격으로 비교해요</p><div class="home-card-rail">${x.hospitals.slice(0,4).map(({h,t})=>HospitalRecommendationCard(h,t.id,x.prefs,true)).join('')||'<p class="soft-empty">선택 지역에 등록된 병원이 없어요. 탐색에서 다른 지역을 확인해보세요.</p>'}</div>${section('피부 지식')}${KnowledgeCard(c)}${section('이런 시술은 어때요?')}<div class="related-treatment-list">${x.treatments.slice(0,3).map(t=>`<article class="mini-treatment">${treatmentImage(t,c.id)}<div><h3>${button(t.name,'treatment',t.id,'text-button')}</h3><p>${t.summary}</p>${button('병원 보기','decision-hospitals',t.id,'text-button')}</div></article>`).join('')||'<p class="soft-empty">이 고민의 관련 시술 정보는 준비 중이에요.</p>'}</div>${section('Q&A')}<div class="home-qa"><details><summary>${esc(k[2])}</summary><p>${esc(k[3])}</p></details><details><summary>${esc(c.name)} 상담 비용은 어떻게 비교하나요?</summary><p>같은 부위·횟수·구성을 기준으로 비교하고 마취·사후 관리 비용도 확인하세요.</p></details></div>`:`<div class="generic-home"><h2>아직 선택한 고민이 없어요.</h2><p>위의 맞춤 버튼에서 지금 궁금한 고민을 알려주세요.</p></div>`}${x.events.length?`${section('관련 이벤트')}<div class="home-card-rail">${x.events.map(promotionCard).join('')}</div>`:''}${state.saved.length?`${section('찜한 병원 다시보기',button('전체보기','navigate','saved','text-button'))}<div class="home-card-rail">${state.saved.slice(0,4).map(id=>HospitalRecommendationCard(hospital(id),state.savedTreatments[id]||hospital(id).treatments[0],x.prefs,true)).join('')}</div>`:''}${mockNote()}<p class="photo-credits">사진: <a href="https://unsplash.com/photos/zg30dYawyo4">Cherrydeck / Unsplash</a> · 관련 사진과 일러스트는 예시입니다.</p></div>`);}
function promotionCard(p){const t=treatment(p.treatmentId);return `<article class="promotion-card connected-promotion">${treatmentImage(t)}<div class="promotion-body"><span class="ad-label">이벤트 · 가상 광고</span><h3>${button(esc(p.title),'event',p.id,'text-button')}</h3><p>${hospital(p.hospitalId).name} · ${p.region}</p>${offerPrice(p)}${button(icon('bookmark')+(state.savedEvents.includes(p.id)?' 저장됨':' 이벤트 저장'),'save-event',p.id,'text-button',`aria-pressed="${state.savedEvents.includes(p.id)}"`)}</div></article>`;}
function renderExplore(){const region=exploreRegion||state.profile.region,cat=D.concerns.find(c=>c.id===exploreCategory),q=exploreQuery.trim().toLowerCase();const list=D.treatments.filter(t=>(!cat||t.categoryIds.includes(cat.id))&&(exploreSub==='all'||t.concerns.includes(exploreSub))).map(t=>({t,hs:D.hospitals.filter(h=>L.getOffer(h.id,t.id)&&(region==='전체'||h.location===region)&&[h.name,t.name,...t.concerns,...t.aliases].join(' ').toLowerCase().includes(q))})).filter(x=>x.hs.length);shell(`<div class="explore-intro"><h1>내 기준으로 둘러보기</h1><form class="explore-search" id="explore-search">${icon('search')}<input name="query" type="search" value="${esc(exploreQuery)}" placeholder="시술·병원·고민 검색" aria-label="탐색 검색"><button type="submit">검색</button></form></div><section class="clinic-ad"><img src="assets/promise-logo.png" alt="프라미스 피부과 광고 시안"><span>광고 시안</span></section><div class="category-tabs">${button('전체','decision-explore-category','all','chip '+(!cat?'active':''))}${D.concerns.map(c=>button(c.name,'decision-explore-category',c.id,'chip '+(cat?.id===c.id?'active':''))).join('')}</div>${cat?`<div class="horizontal-chips sub-tabs">${['all',...cat.items].map(n=>button(n==='all'?'전체':n,'decision-explore-sub',n,'chip '+(exploreSub===n?'active':''))).join('')}</div>`:''}<div class="explore-results">${list.slice(0,exploreLimit).map(({t,hs})=>`${section(t.name,button('시술 정보','treatment',t.id,'text-button'))}<div class="home-card-rail">${hs.map(h=>HospitalRecommendationCard(h,t.id,{...state.draft,category:cat?.id||t.category,concern:exploreSub==='all'?'':exploreSub,region},true)).join('')}</div>${D.promotions.filter(p=>p.treatmentId===t.id&&hs.some(h=>h.id===p.hospitalId)).map(promotionCard).join('')}`).join('')||'<div class="soft-empty">일치하는 시술·병원이 없어요. 지역이나 검색어를 바꿔보세요.</div>'}${list.length>exploreLimit?button('시술 목록 더보기','explore-more','','secondary load-more'):''}</div>${mockNote()}`,{active:'explore'});}
function renderCommunity(){const c=activeConcernRecord(),q=communityQuery.trim().toLowerCase();let rs=D.reviews.filter(r=>[r.content,treatment(r.treatmentId).name,hospital(r.hospitalId).name,r.concern].join(' ').toLowerCase().includes(q));if(!q&&c)rs=rs.filter(r=>treatment(r.treatmentId).concernIds.includes(c.id));const posts=(D.boards[communityTab]||[]).filter(p=>(p.title+p.body).includes(communityQuery));shell(`${heading('','커뮤니티',c?esc(c.name)+' 관련 메이트들의 이야기':'메이트들의 피부 이야기')}<form class="explore-search" id="community-search"><input name="query" type="search" value="${esc(communityQuery)}" placeholder="고민, 시술, 게시글 검색" aria-label="커뮤니티 검색"><button type="submit">검색</button></form><div class="community-tabs" role="tablist">${[['reviews','관심 후기'],['qa','Q&A'],['free','자유게시판']].map(([v,l])=>button(l,'story-tab',v,communityTab===v?'active':'',`role="tab" aria-selected="${communityTab===v}"`)).join('')}</div>${communityTab==='reviews'?rs.slice(0,reviewLimit).map(ReviewCard).join('')+(rs.length>reviewLimit?button('후기 더보기','reviews-more','','secondary load-more'):''):posts.map(boardCard).join('')}${(communityTab==='reviews'?!rs.length:!posts.length)?'<p class="soft-empty">검색 결과가 없어요.</p>':''}${mockNote()}`,{active:'community'});}
function renderDecisionScreen(){
 const prefs=state.draft,c=L.resolveConcern(prefs),cat=D.concerns.find(x=>x.id===prefs.category);
 if(screen==='concern'){shell(`${heading('','어떤 고민을 먼저<br>해결하고 싶나요?','관심 있는 분야를 선택해주세요.')}<div class="decision-category-grid">${D.concerns.map(ConcernCategoryCard).join('')}</div>`,{title:'고민 선택'});return true;}
 if(screen==='subconcern'){if(!cat){screen='concern';return renderDecisionScreen();}shell(`<p class="concern-path">${cat.name}</p>${heading('','어떤 부분이<br>신경 쓰이나요?','지금 먼저 알아볼 고민 하나를 골라주세요.')}<div class="subconcern-grid">${cat.concernIds.map(id=>SubConcernCard(concernById(id))).join('')}</div>${c?`<p class="concern-path">${concernPath(c)}</p>`:''}`,{title:'세부 고민',footer:foot('선택 기준 정하기','to-priority',!c)});return true;}
 if(screen==='priority'){if(!c){screen='concern';return renderDecisionScreen();}shell(`<p class="concern-path">${concernPath(c)}</p>${heading('','어떤 기준이<br>가장 중요하세요?','중요한 순서대로 최대 3개를 골라주세요.')}<div class="priority-list">${D.criteria.map(PriorityCard).join('')}</div><p class="priority-caption">선택 기준: ${prefs.priorities.map(k=>criterion(k).name).join(' · ')||'아직 선택하지 않았어요'}</p><label class="field" for="budget">예산 · 1회</label><select id="budget">${D.budgets.map(b=>`<option value="${b.id}" ${prefs.budget===b.id?'selected':''}>${b.label}</option>`).join('')}</select><label class="field" for="region">방문 지역</label><select id="region">${D.regions.map(r=>`<option ${prefs.region===r?'selected':''}>${r}</option>`).join('')}</select>`,{title:'선택 기준',footer:foot('관련 시술 보기','find',!prefs.priorities.length)});return true;}
 if(screen==='treatments'){if(!c){shell(`${heading('','먼저 고민을 알려주세요')}${button('고민 선택하기','start','','primary')}`);return true;}const ts=L.rankTreatments(D.treatments,D.hospitals,prefs);shell(`<div class="decision-intro"><p class="concern-path">${concernPath(c)}</p>${heading('',esc(c.name)+'에 추천하는 맞춤 시술','회원님의 고민과 우선순위를 분석해<br>관련 시술을 추천드려요.')}<div class="criteria-inline"><span>${prefs.priorities.map(k=>criterion(k).name).join(' · ')||'관련 시술'}</span>${button('조건 수정','navigate','priority','edit-conditions')}</div></div>${ts.slice(0,treatmentLimit).map(TreatmentRecommendationCard).join('')||'<p class="soft-empty">관련 시술 정보가 아직 준비되지 않았어요. 상담에서 가능한 방법을 확인해보세요.</p>'}${ts.length>treatmentLimit?button('다른 관련 시술 더보기','treatments-more','','secondary load-more'):''}${mockNote()}`,{title:'맞춤 시술'});return true;}
 if(screen==='treatment'){const [hospitalId,treatmentId]=routeId.includes(':')?routeId.split(':'):[null,routeId],h=hospital(hospitalId),t=treatment(treatmentId),connected=!!(h&&t&&L.getOffer(h.id,t.id));if(!t){shell('<p class="soft-empty">시술 정보를 찾지 못했어요.</p>',{title:'시술 정보'});return true;}shell(`<div class="treatment-detail-image">${treatmentImage(t,c?.id)}</div><div class="light-panel">${heading('',esc(t.name),esc(t.summary))}${tags(t.tags)}${section('어떤 시술인가요?')}<p>${esc(t.description)}</p>${section('진행 방식')}<p>${esc(t.modality)} 방식이에요. 현재 상태를 확인하고 부위·강도·구성을 상담한 뒤 진행 여부를 결정해요.</p><div class="data-row"><span>일반 가격 범위</span><b>${money(t.priceRange)} · 예시</b></div><div class="data-row"><span>통증</span><b>${t.painLevel}</b></div><div class="data-row"><span>회복시간</span><b>${t.downtime}</b></div><div class="data-row"><span>시술 시간</span><b>${t.treatmentTime}</b></div>${section('알아둘 점')}<ul>${t.cautions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="tiny">실제 시술 적합성·구성·시간은 진료에서 확인하세요.</p><a class="source-link" href="${t.sourceUrl}" target="_blank" rel="noopener noreferrer">관련 학회·제조사 정보 보기</a></div>${connected?`${section('이 병원에서 받는 시술')}<article class="treatment-hospital-panel"><h2>${esc(h.name)}</h2><p>${distance(h)} · ${esc(h.doctor)}</p><p>${offerPrice(L.getOffer(h.id,t.id))} · ${reviewRating(L.aggregateReviews(h.id,t.id))}</p>${button('병원 상세 보기','detail',h.id,'text-button')}</article>${section('이 병원의 '+esc(t.name)+' 후기',button('전체 후기 보기','decision-reviews',h.id+':'+t.id,'text-button'))}<div class="hospital-review-list">${L.aggregateReviews(h.id,t.id).rows.slice(0,3).map(r=>`<article class="hospital-review-compact"><div><b>${esc(r.userId||'메이트')}</b><span>★ ${Number(r.overallRating).toFixed(1)}</span></div><p>${esc(r.content)}</p></article>`).join('')||'<p class="soft-empty">아직 후기가 없어요.</p>'}</div>${section('이 병원의 '+esc(t.name)+' 소식')}${D.promotions.some(p=>p.hospitalId===h.id&&p.treatmentId===t.id)?`<div class="hospital-event-rail">${D.promotions.filter(p=>p.hospitalId===h.id&&p.treatmentId===t.id).map(promotionCard).join('')}</div>`:`<article class="treatment-promo-fallback"><span class="ad-label">병원 홍보 · 가상 정보</span><h3>${esc(h.name)} ${esc(t.name)} 안내</h3><p>시술 구성과 예상 비용을 확인하고 상담에서 적합한 방법을 알아보세요.</p>${button('병원 상세 보기','detail',h.id,'text-button')}</article>`}`:''}`,{title:'시술 정보',footer:connected?`<div class="footer-action hospital-detail-actions">${button('상담 예약하기','hospital-book',h.id+':'+t.id,'secondary')}${button('결제하기','hospital-pay',h.id+':'+t.id,'primary')}</div>`:foot('이 시술 병원 보기','select-current-treatment')});return true;}
 if(screen==='hospitals'){const t=selected();if(!t){screen='treatments';return renderDecisionScreen();}const all=L.rankHospitals(D.hospitals,t.id,prefs),hs=showAllHospitalRegions?all:all.filter(h=>h.location===prefs.region);shell(`${heading('',esc(t.name)+'<br>병원 보기')}<p class="section-caption">${showAllHospitalRegions?'전체 지역':prefs.region} · ${prefs.priorities.map(k=>criterion(k).name).join(' · ')||'해당 시술 후기 기준'}</p>${button('시술 다시 선택','navigate','treatments','text-button')}${button(showAllHospitalRegions?'선택 지역만 보기':'다른 지역도 보기','hospital-region-toggle','','text-button')}<div class="hospital-result-list">${hs.map(h=>HospitalRecommendationCard(h,t.id,prefs)).join('')||'<p class="soft-empty">이 지역에 등록된 병원이 없어요. 다른 지역도 살펴보세요.</p>'}</div>${mockNote()}`,{title:'병원 추천'});return true;}
 if(screen==='detail'){const h=hospital(routeId);if(!h){shell('<p class="soft-empty">병원을 찾지 못했어요.</p>',{title:'병원 정보'});return true;}const tid=h.treatments.includes(state.selectedTreatment)?state.selectedTreatment:h.treatments[0],t=treatment(tid),g=L.aggregateReviews(h.id,tid),rs=[...g.rows].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),events=D.promotions.filter(p=>p.hospitalId===h.id);shell(`<figure class="hospital-photo-panel is-detail"><img src="assets/photos/clinic.webp" alt="병원 대기 공간 분위기 예시" width="720" height="480"><figcaption>Unsplash · 실제 병원 사진 아님</figcaption></figure><section class="clinic-summary light-panel"><span class="demo-label">가상 병원</span><h1>${h.name}</h1><p class="rating-line">${reviewRating(g)}</p><small>${t.name} 관련 후기</small><p>${distance(h)} · 역 기준</p><p class="muted">${h.doctor}</p>${button('<i></i>왜 추천됐나요?','decision-reason',h.id+':'+tid,'reason-link')}</section>${section('제공하는 시술')}<div class="hospital-treatment-list">${[t,...h.treatments.filter(id=>id!==tid).map(treatment)].slice(0,hospitalTreatmentLimit).map(t=>HospitalTreatmentRow(h,t)).join('')}</div>${h.treatments.length>hospitalTreatmentLimit?button('제공 시술 더보기','hospital-treatments-more','','secondary load-more'):''}${section('최근 후기',button('전체 후기 보기','decision-reviews',h.id+':'+tid,'text-button'))}<div class="hospital-review-list">${rs.slice(0,3).map(r=>`<article class="hospital-review-compact"><div><b>${esc(r.userId||'메이트')}</b><span>★ ${Number(r.overallRating).toFixed(1)} · ${esc(t.name)}</span></div><p>${esc(r.content)}</p><small>${esc(r.createdAt||r.date||'')} · 체험 후기</small></article>`).join('')||'<p class="soft-empty">해당 시술의 후기가 아직 없어요.</p>'}</div>${events.length?`${section('병원 이벤트')}<div class="hospital-event-rail" aria-label="병원 이벤트 카드">${events.map(promotionCard).join('')}</div>`:''}${mockNote()}`,{footer:`<div class="footer-action hospital-detail-actions">${button('상담 예약하기','hospital-book',h.id,'secondary')}${button('온라인 상담하기','hospital-online',h.id,'primary')}</div>`});return true;}
 if(screen==='hospital-reviews'){const [hid,tid]=routeId.split(':'),h=hospital(hid),t=treatment(tid);if(!h||!t||!L.getOffer(hid,tid)){shell('<p>후기를 찾지 못했어요.</p>',{title:'후기'});return true;}const rs=[...L.aggregateReviews(hid,tid).rows].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));shell(`${heading('',esc(h.name),esc(t.name)+' · '+reviewRating(L.aggregateReviews(hid,tid)))}${button('체험 후기 작성','write-review',routeId,'primary')}<p class="tiny">실제 경험이 아닌 포트폴리오용 평가를 입력해요. 이 기기에 저장되며 추천 순서에 반영됩니다.</p>${rs.slice(0,reviewLimit).map(ReviewCard).join('')||'<p class="soft-empty">첫 체험 후기를 남겨보세요.</p>'}${rs.length>reviewLimit?button('후기 더보기','reviews-more','','secondary load-more'):''}`,{title:'시술 후기'});return true;}
 if(screen==='article'){const ac=concernById(routeId)||D.subConcerns.find(c=>c.categoryId===routeId)||activeConcernRecord();if(!ac)return false;const k=knowledgeFor(ac),ts=D.treatments.filter(t=>t.concernIds.includes(ac.id));shell(`${heading('',esc(k[0]))}<div class="light-panel"><p>${esc(k[1])}</p><h2>${esc(k[2])}</h2><p>${esc(k[3])}</p><p>현재 복용 중인 약과 이전 시술 이력, 가능한 회복 일정을 함께 알려주세요.</p>${ts[0]?`<a href="${ts[0].sourceUrl}" target="_blank" rel="noopener noreferrer">관련 학회·제조사 안내</a>`:''}</div>${section('관련 시술')}${ts.slice(0,4).map(TreatmentRecommendationCard).join('')}`,{title:'피부지식'});return true;}
 if(screen==='completion'){const booking=routeId==='booking',record=(booking?state.bookings:state.payments)?.[0],h=hospital(record?.hospitalId),t=treatment(record?.treatmentId);if(!h||!t){go('home');return true;}shell(`<section class="action-completion"><span class="completion-mark">${icon('check')}</span><h1>${booking?'예약이 완료되었습니다.':'결제가 완료되었습니다.'}</h1><p>${esc(h.name)} · ${esc(t.name)}</p>${booking?`<p>${record.type==='online'?'온라인 상담 신청':`상담 희망 일정 · ${esc(record.date)} ${esc(record.time)}`}</p>`:`<p>${offerPrice(L.getOffer(h.id,t.id))}</p>`}<small>포트폴리오 체험입니다. 실제 병원 예약이나 결제는 진행되지 않았어요.</small></section>`,{title:booking?'예약 완료':'결제 완료',bottom:false,footer:`<div class="footer-action">${button('홈으로 이동','navigate','home','primary')}${button(booking?'예정된 예약 보기':'결제 내역 보기','activity',booking?'예정된 예약':'결제 내역','secondary')}</div>`});return true;}
 if(screen==='activity'&&routeId==='작성한 후기'){shell(heading('','내가 쓴 후기')+((state.userReviews||[]).map(ReviewCard).join('')||'<p class="soft-empty">아직 작성한 체험 후기가 없어요.</p>'),{title:'내가 쓴 후기',active:'my'});return true;}
 if(screen==='compare'){renderReviewComparison();return true;}
 return false;
}
function renderReviewComparison(){const t=selected();if(!t){shell('<p>비교할 시술을 선택해주세요.</p>');return;}const hs=state.compare.map(hospital).filter(Boolean),common=D.treatments.filter(t=>hs.every(h=>L.getOffer(h.id,t.id))),result=L.compareHospitals(D.hospitals,state.compare,t.id,state.draft);shell(`${heading('','같은 시술로 비교해요.')}<label class="field" for="compare-treatment">비교 시술</label><select id="compare-treatment">${[...new Set([t,...common])].map(x=>`<option value="${x.id}" ${x.id===t.id?'selected':''}>${x.name}</option>`).join('')}</select><div class="compare-scroll"><table class="compare-table"><caption>${t.name} · 해당 시술의 가상 후기 평가</caption><thead><tr><th>비교 항목</th>${result.candidates.map(h=>`<th>${h.name}${button('빼기','compare-toggle',h.id,'text-button')}</th>`).join('')}</tr></thead><tbody><tr><th>1회 가격</th>${result.candidates.map(h=>`<td>${h.offer?offerPrice(h.offer):'미제공'}</td>`).join('')}</tr><tr><th>별점·후기</th>${result.candidates.map(h=>`<td>${reviewRating(h.aggregate)}</td>`).join('')}</tr>${result.rows.map(({key})=>`<tr><th>${criterion(key).name}</th>${result.candidates.map(h=>`<td>${h.comparable&&h.aggregate.means[key]!==null?h.aggregate.means[key].toFixed(1)+' / 5':'평가 없음'}</td>`).join('')}</tr>`).join('')}<tr><th>자세히</th>${result.candidates.map(h=>`<td>${button('병원 보기','detail',h.id,'text-button')}</td>`).join('')}</tr></tbody></table></div>${mockNote()}`,{title:'병원 비교',active:'saved'});}
function openReviewForm(hid,tid){const d=document.createElement('dialog');d.className='review-form-sheet';d.innerHTML=`<h2>체험 후기 작성</h2><p>${hospital(hid).name} · ${treatment(tid).name}</p><form id="decision-review-form" data-hospital="${hid}" data-treatment="${tid}"><label>전체 별점<select name="overallRating" required><option value="">선택</option>${[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')}</select></label>${D.criteria.map(c=>`<label>${c.name}<select name="${L.fields[c.id]}" required><option value="">선택</option>${[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')}</select></label>`).join('')}<p class="tiny">5점에 가까울수록 만족도가 높고 부담이 적다는 의미예요.</p><label>후기 내용<textarea name="content" required minlength="5" maxlength="1500" placeholder="체험용 평가 내용을 작성해주세요."></textarea></label><button class="primary" type="submit">평가 저장</button><button type="button" data-close>취소</button></form>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();}
function saveReviewRecord(hid,tid,values){if(!L.getOffer(hid,tid)||(state.userReviews||[]).length>=300)return false;const keys=['overallRating',...Object.values(L.fields)];if(!keys.every(k=>Number.isFinite(Number(values[k]))&&Number(values[k])>=1&&Number(values[k])<=5)||String(values.content||'').trim().length<5)return false;const o=L.getOffer(hid,tid),t=treatment(tid),id='local-'+Date.now()+'-'+(state.userReviews?.length||0),content=String(values.content).trim().slice(0,1500);const r={id,reviewId:id,hospitalId:hid,treatmentId:tid,userId:'Skinmate1',...Object.fromEntries(keys.map(k=>[k,Number(values[k])])),content,text:content,createdAt:new Date().toISOString(),date:new Date().toLocaleDateString('ko-KR'),price:o.price,satisfaction:Number(values.overallRating),pain:'직접 입력한 평가',recovery:t.downtime,category:t.category,concern:t.concerns[0],mock:true};if(!update(()=>{state.userReviews=[r,...(state.userReviews||[])];}))return false;D.reviews.push(r);return true;}
const decisionActions=new Set(['hospital-treatments-more','decision-category','decision-concern','personalized-home','treatments-more','explore-more','reviews-more','decision-hospitals','decision-reason','decision-reviews','write-review','hospital-region-toggle','decision-explore-category','decision-explore-sub']);
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,v=el.dataset.value;if(!decisionActions.has(a)){if(a==='find'||a==='start')treatmentLimit=4;if(a==='offer-detail'||a==='detail')hospitalTreatmentLimit=5;return;}e.preventDefault();e.stopImmediatePropagation();
 if(a==='decision-category'){if(!D.concerns.some(c=>c.id===v))return;if(update(()=>{state.draft.category=v;state.draft.concern='';delete state.draft.concernId;state.selectedTreatment='';}))go('subconcern');}
 if(a==='decision-concern'){const c=concernById(v);if(!c||c.categoryId!==state.draft.category)return;if(update(()=>{state.draft.concern=c.name;state.draft.concernId=c.id;state.selectedTreatment='';}))repaint();}
 if(a==='personalized-home'){if(update(()=>{state.draft={...structuredClone(SkinmateStorage.initial.draft),region:state.profile.region};state.selectedTreatment='';state.compare=[];}))go('concern');}
 if(a==='hospital-treatments-more'){hospitalTreatmentLimit+=5;repaint();}
 if(a==='treatments-more'){treatmentLimit+=4;repaint();}
 if(a==='explore-more'){exploreLimit+=5;repaint();}
 if(a==='reviews-more'){reviewLimit+=8;repaint();}
 if(a==='decision-hospitals'){showAllHospitalRegions=false;if(screen==='home'&&!update(()=>{state.draft=activePreferences();}))return;chooseTreatment(v);}
 if(a==='hospital-region-toggle'){showAllHospitalRegions=!showAllHospitalRegions;repaint();}
 if(a==='decision-reason'){const [hid,tid]=v.split(':');openReasonSheet(hid,tid);}
 if(a==='decision-reviews'){document.querySelector('dialog')?.close();reviewLimit=8;go('hospital-reviews',v);}
 if(a==='write-review'){const [hid,tid]=v.split(':');openReviewForm(hid,tid);}
 if(a==='decision-explore-category'){exploreCategory=v;exploreSub='all';exploreLimit=5;repaint();}
 if(a==='decision-explore-sub'){exploreSub=v;exploreLimit=5;repaint();}
},true);
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.connected-hospital[role="link"]')){e.preventDefault();e.target.click();}});
document.addEventListener('submit',e=>{if(e.target.id!=='decision-review-form')return;e.preventDefault();const values=Object.fromEntries(new FormData(e.target));if(saveReviewRecord(e.target.dataset.hospital,e.target.dataset.treatment,values)){e.target.closest('dialog').close();repaint();toast('평가를 저장했어요. 추천에 반영됩니다.');}else toast('모든 평가와 5자 이상의 내용을 확인해주세요.');});
