paths.compass='M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM16 8l-3 5-5 3 3-5 5-3Z';
/* View layer: keeps the existing catalog, scoring, comparison and storage services. */
let onboardingStep=0, exploreSub='all', exploreRegion='', communityTab='reviews', storyTag='all', communityQuery='';
const portrait=i=>'assets/skinmate-portrait.webp';
const brand=()=>'<span class="brand-image"><img src="assets/logo.jpg" alt="Skinmate"></span>';
paths.chat='M21 11a9 9 0 0 1-9 9H4l-3 2 1-6a9 9 0 1 1 19-5ZM7 11h.01M12 11h.01M17 11h.01';
paths.gear='M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1ZM16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0';
function header(title){const region=`<label class="region-control">${icon('pin')}<span class="sr-only">탐색 지역</span><select id="explore-region">${['전체',...D.regions].map(r=>`<option ${r===(exploreRegion||state.profile.region)?'selected':''}>${r}</option>`).join('')}</select></label>`;return `<header class="app-header">${title?`<div class="header-back">${button(icon('back'),'back','','icon-button','aria-label="뒤로 가기"')}<span class="header-title">${esc(title)}</span></div>`:screen==='explore'?region:screen==='my'?'<span></span>':screen==='saved'?'<strong class="header-title">찜</strong>':brand()}<div class="header-actions">${screen==='my'?button('<span class="settings-image"><img src="assets/settings-gear.png" alt=""></span>','settings','전체','icon-button','aria-label="설정"'):button(icon('bell'),'notifications','','icon-button','aria-label="알림"')}</div></header>`;}

function nav(active){return `<nav class="bottom-nav" aria-label="주요 메뉴">${[['home','home','홈'],['explore','compass','탐색'],['community','chat','커뮤니티'],['saved','bookmark','찜'],['my','user','마이']].map(([s,i,l])=>button(`${icon(i)}<span>${l}</span>`,'navigate',s,`nav-item ${active===s?'active':''}`,active===s?'aria-current="page"':'')).join('')}</nav>`;}
function photo(i,cls=''){return `<img class="${cls}" src="${portrait(i)}" alt="뷰티 분위기 이미지 예시" loading="lazy">`;}
const homeFilters={};
const homePhotoSources=[
'https://images.unsplash.com/photo-1761718210089-ba3bb5ccb54f?auto=format&fit=crop&w=600&q=80',
'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80'];
const homeCopy={contour:['얼굴선부터 턱선까지, 윤곽 시술 모음','내 고민에 맞는 방법과 병원을 비교해요.'],aging:['탄력부터 잔주름까지, 리프팅 시술 모음','내가 중요하게 생각하는 기준으로 살펴봐요.'],trouble:['트러블부터 여드름 흉터까지, 피부 시술 모음','현재 피부 고민에 맞는 상담부터 시작해요.'],texture:['모공부터 피부결까지, 피부 관리 모음','피지와 블랙헤드, 관심 있는 고민부터 살펴봐요.'],tone:['잡티부터 피부톤까지, 색소 시술 모음','궁금한 부위와 고민에 맞춰 비교해요.'],hair:['얼굴부터 바디까지, 제모 시술 모음','원하는 부위와 방법을 선택해 시작해요.'],other:['아직 이름 붙이기 어려운 고민도 함께','궁금한 점부터 피부 상담을 시작해요.']};
function homeCard(h,t,i){const saved=state.saved.includes(h.id)&&state.savedTreatments[h.id]===t.id;return `<article class="home-treatment-card"><div class="home-card-image"><img src="${homePhotoSources[i%homePhotoSources.length]}" alt="피부 관리 분위기 예시" loading="lazy" referrerpolicy="no-referrer"><small>이미지 예시</small>${button(icon('bookmark'),'save-offer',h.id+':'+t.id,'bookmark-button '+(saved?'is-saved':''),`aria-label="${h.name} ${t.name} 저장" aria-pressed="${saved}"`)}</div><p class="home-clinic-name">${h.name} · ${h.location}</p><h3>${button(t.name,'offer-detail',h.id+':'+t.id,'text-button')}</h3>${offerPrice(h.exactOffers[t.id])}<small class="home-rating">★ ${h.rating} <span>(${h.reviewCount}) · 가상 후기</span></small></article>`;}
function homeInterestSection(c){const choices=c.id==='hair'?['전체','턱','인중','겨드랑이','팔','다리','브라질리언왁싱','얼굴','기타']:['전체',...c.items];const active=homeFilters[c.id]||state.profile.concerns.find(x=>c.items.includes(x))||'전체';const ts=D.treatments.filter(t=>t.category===c.id&&(active==='전체'||t.concerns.includes(active)));const cards=ts.flatMap(t=>D.hospitals.filter(h=>h.location===state.profile.region&&h.treatments.includes(t.id)).map(h=>({h,t})));return `<section class="home-interest-section"><h2>${homeCopy[c.id][0]}</h2><p class="home-section-description">${homeCopy[c.id][1]}</p><div class="horizontal-chips home-filter-row">${choices.map(x=>button(x,'home-filter',c.id+':'+x,'chip '+(active===x?'active':''),`aria-pressed="${active===x}"`)).join('')}</div><div class="home-card-rail">${cards.map(({h,t},i)=>homeCard(h,t,i)).join('')||`<div class="soft-empty"><p>${esc(state.profile.region)}에 등록된 ${esc(active==='전체'?c.name:active)} 시술 정보가 아직 없어요.</p>${button('다른 지역 둘러보기','navigate','explore','text-button')}</div>`}</div></section>`;}
function homeGuide(c){const selected=state.profile.concerns.filter(x=>c.items.includes(x));if(selected.includes('여드름 흉터'))return `<article class="home-guide"><small>피부 지식 · 여드름 흉터</small><h3>패인 여드름 흉터란?</h3><p>피부 표면이 움푹 들어간 형태의 흉터예요. 모양과 깊이가 다양해, 어떤 유형인지 확인하는 것이 상담의 출발점이에요.</p><a href="https://www.aad.org/public/diseases/acne/derm-treat/scars/symptoms" target="_blank" rel="noopener noreferrer">미국피부과학회 설명 읽기</a></article>`;return `<article class="home-guide"><small>피부 가이드 · ${c.name}</small><h3>${esc(selected[0]||c.name)}, 상담 전에 정리할 것</h3><p>고민이 시작된 시기, 이전에 받은 시술, 현재 사용하는 제품을 메모해보세요. 원하는 변화와 회복에 쓸 수 있는 시간도 함께 정리하면 비교하기 쉬워요.</p>${button('관련 가이드 보기','article',c.id,'text-button')}</article>`;}
function renderHome(){const categories=D.concerns.filter(c=>c.items.some(x=>state.profile.concerns.includes(x))||D.treatments.some(t=>t.category===c.id&&state.profile.fields.includes(t.id)));shell(`<section class="beauty-hero home-new-hero">${photo(0)}<div class="hero-copy"><h1>내 고민에 맞는 시술을<br>찾아볼까요?</h1><p>중요하게 생각하는 기준을 바탕으로<br>나에게 맞는 시술과 병원을 찾아드려요.</p>${button('맞춤 시술 추천받기','start','','primary')}</div><span class="image-label">이미지 예시</span></section>${categories.map(homeInterestSection).join('')||`<div class="soft-empty"><h2>어떤 피부 고민이 궁금하세요?</h2>${button('관심 분야 설정하기','edit-profile','','primary')}</div>`}${section('찜한 병원 다시보기',button('전체보기','navigate','saved','text-button'))}<div class="home-card-rail">${state.saved.map((id,i)=>{const h=hospital(id);const t=treatment(state.savedTreatments[id]||h.treatments[0]);return homeCard(h,t,i);}).join('')||`<div class="soft-empty">${icon('bookmark')}<p>마음에 드는 병원을 저장하면<br>여기서 다시 만나볼 수 있어요.</p>${button('병원 둘러보기','navigate','explore','text-button')}</div>`}</div>${section('내 관심 분야 피부 지식')}<div class="home-guide-list">${categories.map(homeGuide).join('')||'<p class="tiny">관심 분야를 선택하면 관련 가이드를 모아드려요.</p>'}</div>${section('Q&A')}<div class="home-qa"><details><summary>상담 전 챙겨야 할 것은 무엇인가요?</summary><p>복용 중인 약, 알레르기, 이전 시술 내역과 궁금한 질문을 정리해보세요.</p></details><details><summary>시술 받기 전 알기 좋은 게 있을까요?</summary><p>총비용과 포함 항목, 회복 일정, 주의사항, 추가 방문 여부를 상담에서 확인해보세요.</p></details><details><summary>병원별 가격은 어떻게 비교하나요?</summary><p>같은 부위·횟수·구성인지 먼저 확인하고 마취·부가세·사후 관리 포함 여부를 함께 물어보세요.</p></details></div><p class="tiny home-photo-credit">사진: <a href="https://unsplash.com/photos/a-person-receiving-a-facial-treatment-RbIcMsh0NSk" target="_blank" rel="noopener noreferrer">Unsplash</a> · 실제 병원이나 시술 결과 사진이 아닌 분위기 예시입니다.</p>${mockNote()}`);}

function beautyEvent(p,i=0){const saved=state.savedEvents.includes(p.id);return `<article class="beauty-event"><span class="ad-label">이벤트 · 가상 광고</span>${button(icon('bookmark'),'save-event',p.id,`bookmark-button ${saved?'is-saved':''}`,`aria-label="${p.title} 저장" aria-pressed="${saved}"`)}<div class="event-copy"><h3>${button(treatment(p.treatmentId).name,'event',p.id,'text-button')}</h3><p>${hospital(p.hospitalId).name}</p>${offerPrice(p)}<small>${distance(hospital(p.hospitalId))}</small></div></article>`;}
function promotionCard(p){return beautyEvent(p,D.promotions.indexOf(p));}
let onboardCategories=[];
function onboardingReady(){return onboardingStep===1?onboardCategories.length>0:onboardingStep===2?profileDraft.concerns.length>0:onboardingStep===3?D.regions.includes(profileDraft.region):true;}
function renderOnboarding(){if(!profileDraft){profileDraft={...structuredClone(state.profile),concerns:[],fields:[],region:''};onboardCategories=[];}let body='';
if(onboardingStep===0)body=`<div class="onboard-logo"><img src="assets/logo.jpg" alt="Skinmate"></div>${heading('','나를 알아가는<br>피부 여정, 함께해요.','관심 있는 고민과 지역을 알려주세요.<br>나에게 가까운 정보부터 보여드릴게요.')}`;
if(onboardingStep===1)body=`${heading('','관심 분야를 선택해주세요','궁금한 분야를 여러 개 선택할 수 있어요.')}<div class="onboard-categories">${D.concerns.map(c=>button(`<span class="category-illustration">${icon(c.icon)}</span><b>${c.name}</b>`,'onboard-category',c.id,`onboard-category ${onboardCategories.includes(c.id)?'selected':''}`,`aria-pressed="${onboardCategories.includes(c.id)}"`)).join('')}</div>`;
if(onboardingStep===2)body=`${heading('','어떤 고민을 하고 있나요?','중복 선택할 수 있어요.')}<div class="onboard-details">${D.concerns.filter(c=>onboardCategories.includes(c.id)).map(c=>`<section><h2>${icon(c.icon)} ${c.name}</h2><div class="chip-row">${c.items.map(x=>button(x,'onboard-concern',x,`chip ${profileDraft.concerns.includes(x)?'active':''}`,`aria-pressed="${profileDraft.concerns.includes(x)}"`)).join('')}</div></section>`).join('')}</div>`;
if(onboardingStep===3)body=`${heading('','편한 지역이 어디예요?','선택한 지역의 병원을 보여드릴게요.')}<div class="chip-row">${profileDraft.region?`<span class="chip active">서울 · ${profileDraft.region}</span>`:''}</div><div class="onboard-location"><div class="city-column"><span aria-current="true">서울</span></div><div class="district-column">${D.regions.map(r=>button(r,'onboard-region',r,`district-option ${profileDraft.region===r?'active':''}`,`aria-pressed="${profileDraft.region===r}"`)).join('')}</div></div><p class="tiny">현재 체험 가능한 지역은 서울 강남·잠실·홍대·성수예요.</p>`;
if(onboardingStep===4)body=`<div class="complete-mark">${icon('check')}</div>${heading('','나만의 피부 여정이<br>준비됐어요.','선택한 고민과 지역에 맞춰 정보를 모아드릴게요.')}<div class="profile-card">${tags(profileDraft.concerns)}<p>${icon('pin')} 서울 · ${profileDraft.region}</p></div>`;
shell(`<div class="onboarding-progress" aria-label="${onboardingStep+1}/5 단계">${[0,1,2,3,4].map(n=>`<span class="${n<=onboardingStep?'on':''}"></span>`).join('')}<small>${onboardingStep+1}/5</small></div>${body}`,{bottom:false,footer:`<div class="footer-action onboarding-actions">${onboardingStep?button('이전','onboard-back','','secondary'):''}${button(onboardingStep===4?'시작하기':onboardingStep===0?'나의 관심사 알아보기':'다음','onboard-next','','primary',onboardingReady()?'':'disabled')}</div>`});}

function clinicOffer(h,t,i){const p=D.promotions.find(p=>p.hospitalId===h.id&&p.treatmentId===t.id),saved=state.saved.includes(h.id)&&state.savedTreatments[h.id]===t.id;return `<article class="offer-card"><div class="offer-photo"><span class="ad-label">${p?'이벤트 · 가상 광고':'예시 정보'}</span>${button(icon('bookmark'),'save-offer',`${h.id}:${t.id}`,`bookmark-button ${saved?'is-saved':''}`,`aria-label="${h.name} ${t.name} 저장" aria-pressed="${saved}"`)}</div><div class="offer-copy"><p>${h.name}</p><h3>${button(t.name,'offer-detail',`${h.id}:${t.id}`,'text-button')}</h3>${offerPrice(h.exactOffers[t.id])}<p>${icon('pin')}${distance(h)}</p><small>★ ${h.rating} (${h.reviewCount}) · 1회 예시</small>${tags(t.concerns.slice(0,2))}</div></article>`;}
function renderExplore(){const region=exploreRegion||state.profile.region;const cat=D.concerns.find(c=>c.id===exploreCategory);const q=exploreQuery.toLocaleLowerCase();const list=D.treatments.filter(t=>(!cat||t.category===cat.id)&&(exploreSub==='all'||t.concerns.includes(exploreSub))).map(t=>({t,hs:D.hospitals.filter(h=>h.treatments.includes(t.id)&&(region==='전체'||h.location===region)&&[h.name,t.name,...t.concerns,...D.promotions.filter(p=>p.hospitalId===h.id&&p.treatmentId===t.id).map(p=>p.title)].join(' ').toLocaleLowerCase().includes(q))})).filter(x=>x.hs.length).sort((a,b)=>Number(b.t.concerns.some(c=>state.profile.concerns.includes(c))||state.profile.fields.includes(b.t.id))-Number(a.t.concerns.some(c=>state.profile.concerns.includes(c))||state.profile.fields.includes(a.t.id)));shell(`<form class="explore-search" id="explore-search">${icon('search')}<input name="query" type="search" value="${esc(exploreQuery)}" placeholder="시술, 병원, 이벤트 검색" aria-label="시술, 병원, 이벤트 검색"><button type="submit">검색</button></form><section class="clinic-ad" aria-label="프라미스 피부과 광고 시안"><img src="assets/promise-logo.png" alt="프라미스 피부과 · PROMISE DERMATOLOGY"><span>광고 시안</span></section><div class="category-tabs explore-icon-categories">${button(icon('list')+'<span>전체</span>','beauty-category','all',`chip ${exploreCategory==='all'?'active':''}`)}${D.concerns.map(c=>button(icon(c.icon)+`<span>${c.name}</span>`,'beauty-category',c.id,`chip ${exploreCategory===c.id?'active':''}`)).join('')}</div>${cat?`<div class="horizontal-chips sub-tabs">${['all',...cat.items].map(x=>button(x==='all'?'전체':x,'beauty-sub',x,`chip ${exploreSub===x?'active':''}`)).join('')}</div>`:''}${list.map(({t,hs})=>`${section(t.name,button('시술 정보 ›','treatment',t.id,'text-button'))}<div class="offer-rail">${hs.map((h,i)=>clinicOffer(h,t,i)).join('')}</div>`).join('')||`<div class="soft-empty"><h2>일치하는 결과가 없어요.</h2><p>다른 지역이나 고민으로 찾아보세요.</p>${button('필터 초기화','beauty-clear','','primary')}</div>`}${mockNote()}`,{active:'explore'});}
function storyCard(r,i){const liked=state.community.likes.includes(r.id),helpful=state.community.helpful.includes(r.id);return `<article class="story-card"><div class="story-author">${photo(i)}<div><b>${['하루메이트','피부일기','모모'][i%3]}</b><small>${r.date} · 가상 후기</small></div><span>•••</span></div><h3>${treatment(r.treatmentId).name}, 상담에서 알게 된 것들</h3><p>${r.text}</p>${tags([r.concern,treatment(r.treatmentId).name,hospital(r.hospitalId).location])}<div class="story-metrics"><span>가격<b>${r.price}만원</b></span><span>통증<b>${r.pain.length>12?'개인차 있음':r.pain}</b></span><span>회복<b>${r.recovery}</b></span><span>만족도<b>★ ${r.satisfaction}.0</b></span></div><div class="pros-cons"><div><b>좋았던 점</b><p>상담 전에 정리한 질문으로 비용과 일정을 비교하기 편했어요.</p></div><div><b>아쉬웠던 점</b><p>추가 비용과 회복 중 주의사항은 따로 확인해야 했어요.</p></div></div><div class="story-actions">${button(icon('chat')+' '+(state.community.comments[r.id]?.length||0),'story-comments',r.id,'text-button','aria-label="댓글 보기"')}${button(icon('heart')+' '+(liked?'1':'0'),'story-like',r.id,`text-button ${liked?'coral':''}`,`aria-pressed="${liked}" aria-label="좋아요"`)}${button('도움돼요 '+icon('check'),'story-help',r.id,`text-button ${helpful?'active':''}`,`aria-pressed="${helpful}"`)}</div></article>`;}
function boardCard(p){return `<article class="board-card"><small>${esc(p.author)} · 예시 게시글</small><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p>${button(icon('chat')+' 댓글 '+(state.community.comments[p.id]?.length||0),'story-comments',p.id,'text-button')}</article>`;}
function renderCommunity(){const tagsList=['all',...new Set(D.reviews.map(r=>r.concern))];const q=communityQuery.trim().toLocaleLowerCase();const matches=values=>values.join(' ').toLocaleLowerCase().includes(q);const rs=D.reviews.filter(r=>matches([r.text,r.concern,treatment(r.treatmentId).name,hospital(r.hospitalId).name]));shell(`<div class="community-heading"><span class="eyebrow">TOGETHER, BETTER</span><h1>커뮤니티</h1><p>같은 고민을 하는 메이트들의 이야기</p></div><form class="explore-search" id="community-search">${icon('search')}<input name="query" type="search" value="${esc(communityQuery)}" placeholder="고민, 시술, 게시글 검색" aria-label="커뮤니티 검색"><button type="submit">검색</button></form><div class="community-tabs" role="tablist">${[['reviews','관심 후기'],['qa','Q&A'],['free','자유게시판']].map(([v,l])=>button(l,'story-tab',v,communityTab===v?'active':'',`role="tab" aria-selected="${communityTab===v}"`)).join('')}</div>${communityTab==='reviews'?`<p class="tiny">모든 후기는 가상 예시이며 실제 시술 경험이 아닙니다.</p>${rs.slice(0,8).map(storyCard).join('')||'<p class="info-box">검색 결과가 없어요.</p>'}${section('함께 묻는 Q&A',button('더보기 ›','story-tab','qa','text-button'))}${D.boards.qa.filter(p=>matches([p.title,p.body,p.author])).slice(0,2).map(boardCard).join('')}`:D.boards[communityTab].filter(p=>matches([p.title,p.body,p.author])).map(boardCard).join('')||'<p class="info-box">검색 결과가 없어요.</p>'}`,{active:'community'});}
function openStoryComments(id){dialog('메이트의 댓글',`<p class="tiny">이 기기에만 저장되는 댓글 체험입니다.</p><div class="comment-list">${(state.community.comments[id]||[]).map(c=>`<p><b>나의 댓글</b><br>${esc(c)}</p>`).join('')||'<p>첫 번째 이야기를 남겨보세요.</p>'}</div><form id="story-comment-form" data-id="${esc(id)}"><label class="field">댓글<textarea name="comment" maxlength="500" required placeholder="메이트에게 한마디"></textarea></label><button type="submit" class="primary">댓글 저장</button></form>`);}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,v=el.dataset.value;if(a==='onboard-next'){if(!onboardingReady())return;if(onboardingStep<4){onboardingStep++;render();}else if(update(()=>{state.profile=structuredClone(profileDraft);state.draft.region=profileDraft.region;state.onboarded=true;exploreRegion='';})){profileDraft=null;go('home');}}else if(a==='onboard-back'){onboardingStep=Math.max(0,onboardingStep-1);render();}else if(a==='onboard-category'){onboardCategories=onboardCategories.includes(v)?onboardCategories.filter(x=>x!==v):[...onboardCategories,v];const valid=D.concerns.filter(c=>onboardCategories.includes(c.id)).flatMap(c=>c.items);profileDraft.concerns=profileDraft.concerns.filter(x=>valid.includes(x));repaint();}else if(a==='onboard-concern'){profileDraft.concerns=profileDraft.concerns.includes(v)?profileDraft.concerns.filter(x=>x!==v):[...profileDraft.concerns,v];repaint();}else if(a==='onboard-region'){profileDraft.region=v;repaint();}else if(a==='beauty-category'){const offset=el.closest('.category-tabs').scrollLeft;exploreCategory=v;exploreSub='all';repaint();document.querySelector('.category-tabs').scrollLeft=offset;}else if(a==='beauty-sub'){exploreSub=v;repaint();}else if(a==='beauty-clear'){exploreCategory='all';exploreSub='all';exploreQuery='';exploreRegion='전체';repaint();}else if(a==='save-offer'){const [hid,tid]=v.split(':');if(!hospital(hid)?.treatments.includes(tid))return;const isSame=state.saved.includes(hid)&&state.savedTreatments[hid]===tid;if(update(()=>{state.saved=isSame?state.saved.filter(x=>x!==hid):[...new Set([...state.saved,hid])];state.savedTreatments[hid]=tid;})){repaint();toast(isSame?'저장을 취소했어요.':'선택한 시술 가격과 함께 저장했어요.');}}else if(a==='offer-detail'){const [hid,tid]=v.split(':');if(update(()=>{state.selectedTreatment=tid;state.recentHospitals=[hid,...state.recentHospitals.filter(x=>x!==hid)].slice(0,20);} ))go('detail',hid);}else if(a==='story-tab'){communityTab=v;repaint();}else if(a==='story-tag'){storyTag=v;repaint();}else if(a==='story-like'||a==='story-help'){const k=a==='story-like'?'likes':'helpful';if(update(()=>{state.community[k]=state.community[k].includes(v)?state.community[k].filter(x=>x!==v):[...state.community[k],v];}))repaint();}else if(a==='story-comments')openStoryComments(v);});
document.addEventListener('change',e=>{if(e.target.id==='explore-region'){exploreRegion=e.target.value;repaint();}});
document.addEventListener('submit',e=>{if(e.target.id!=='story-comment-form')return;e.preventDefault();const text=String(new FormData(e.target).get('comment')||'').trim().slice(0,500),id=e.target.dataset.id;if(!text)return;const old=state.community.comments[id]||[];if(old.length>=100)return toast('댓글은 최대 100개까지 저장할 수 있어요.');if(update(()=>{state.community.comments[id]=[...old,text];})){e.target.closest('dialog').close();repaint();openStoryComments(id);}});

// Touch scroll stays native; mouse drag uses a threshold to preserve chip clicks.
let categoryDrag=null,categoryClickBlockedUntil=0;
document.addEventListener('pointerdown',e=>{
 const rail=e.target.closest('.category-tabs');
 if(!rail||rail.scrollWidth<=rail.clientWidth||e.pointerType!=='mouse'||e.button!==0)return;
 categoryClickBlockedUntil=0;
 categoryDrag={rail,id:e.pointerId,x:e.clientX,left:rail.scrollLeft,moved:false};
});
document.addEventListener('pointermove',e=>{
 const d=categoryDrag;if(!d||d.id!==e.pointerId)return;
 const dx=e.clientX-d.x;
 if(!d.moved&&Math.abs(dx)>5){d.moved=true;d.rail.setPointerCapture(e.pointerId);d.rail.classList.add('dragging');}
 if(d.moved){e.preventDefault();d.rail.scrollLeft=d.left-dx;}
});
function finishCategoryDrag(e){
 const d=categoryDrag;if(!d||d.id!==e.pointerId)return;
 if(d.moved)categoryClickBlockedUntil=Date.now()+400;
 d.rail.classList.remove('dragging');
 if(d.rail.hasPointerCapture(e.pointerId))d.rail.releasePointerCapture(e.pointerId);
 categoryDrag=null;
}
document.addEventListener('pointerup',finishCategoryDrag);
document.addEventListener('pointercancel',finishCategoryDrag);
document.addEventListener('click',e=>{
 if(e.detail!==0&&Date.now()<categoryClickBlockedUntil&&e.target.closest('.category-tabs')){e.preventDefault();e.stopImmediatePropagation();}
},true);

document.addEventListener('submit',e=>{if(e.target.id!=='community-search')return;e.preventDefault();communityQuery=String(new FormData(e.target).get('query')||'');repaint();});
document.addEventListener('click',e=>{if(!e.target.closest('[data-action="open-menu"]'))return;dialog('전체 메뉴',`<div class="menu-links">${[['home','홈'],['explore','탐색'],['community','커뮤니티'],['saved','찜'],['my','마이']].map(([route,label])=>`<button class="secondary" data-menu-route="${route}">${label}</button>`).join('')}</div>`);});
document.addEventListener('click',e=>{const b=e.target.closest('[data-menu-route]');if(!b)return;b.closest('dialog').close();go(b.dataset.menuRoute);});

Object.assign(paths,{receipt:'M6 3h12v18l-3-2-3 2-3-2-3 2V3ZM9 7h6M9 11h6',gift:'M3 8h18v4H3zM5 12v9h14v-9M12 8v13M12 8C4 8 5 1 9 3l3 5c8 0 7-7 3-5z',calendar:'M4 5h16v16H4zM8 3v4M16 3v4M4 10h16M8 14h3',coin:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM10 17V7h3a3 3 0 0 1 0 6h-3',ticket:'M3 5h18v5a2 2 0 0 0 0 4v5H3v-5a2 2 0 0 0 0-4V5ZM15 5v3M15 11v2M15 16v3',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7v5l3 2',write:'M4 16l-1 5 5-1L20 8l-4-4L4 16ZM13 7l4 4',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z',headset:'M4 13v-1a8 8 0 0 1 16 0v6l-4 3h-4M4 12h3v6H4zM17 12h3v6h-3z'});
function myRow(label,key,action,value=label,amount=''){return button(`<span class="my-row-label">${icon(key)}<span>${label}</span></span><span class="my-row-end">${amount?`<b>${amount}</b>`:''}</span>`,action,value,'my-row');}
function myGroup(title,rows){return `<section class="my-group"><h2>${title}</h2>${rows}</section>`;}
function renderMy(){shell(`<section class="my-profile"><div class="my-avatar"><img src="assets/symbol.png" alt="기본 프로필 사진"></div><div><h1>Skinmate1님</h1><p>${esc(state.profile.region)}</p></div></section>${button('프로필 수정','edit-profile','','secondary my-edit')}<div class="my-shortcuts">${[['결제 내역','receipt','결제 내역'],['선물함','gift','선물함'],['내가 쓴 글','write','작성한 후기'],['상담 목록','chat','상담 기록']].map(([label,key,value])=>button(`<span>${icon(key)}</span><b>${label}</b>`,'activity',value,'my-shortcut')).join('')}</div><section class="my-group my-wallet">${myRow('포인트','coin','activity','포인트','0P')}${myRow('쿠폰','ticket','activity','쿠폰','0장')}${myRow('시술권','ticket','activity','시술권','0장')}</section>${myGroup('예약',myRow('예정된 예약','calendar','activity')+myRow('지난 예약','clock','activity'))}${myGroup('내 활동',myRow('작성한 후기','write','activity')+myRow('최근 본 병원','clinic','activity')+myRow('최근 본 시술','clock','activity')+myRow('상담 기록','chat','activity'))}<p class="sample-note">포트폴리오 체험 · 실제 결제와 예약은 연결되어 있지 않아요.</p>`,{active:'my'});}

let comparedEvents=[];
function savedEventCard(p){const chosen=comparedEvents.includes(p.id);return `<div class="saved-event-item">${promotionCard(p)}${button(chosen?'비교 선택됨':'비교 선택','compare-event-toggle',p.id,'secondary',`aria-pressed="${chosen}"`)}</div>`;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='compare-event-toggle'){const id=b.dataset.value;if(!comparedEvents.includes(id)&&comparedEvents.length>=3)return toast('최대 3개까지 비교할 수 있어요.');comparedEvents=comparedEvents.includes(id)?comparedEvents.filter(x=>x!==id):[...comparedEvents,id];repaint();}if(b.dataset.action==='compare-events'){const list=D.promotions.filter(p=>state.savedEvents.includes(p.id)&&comparedEvents.includes(p.id));if(list.length<2)return;dialog('선택한 이벤트 비교',`<div class="event-comparison">${list.map(p=>`<article><h3>${esc(treatment(p.treatmentId).name)}</h3><p>${esc(hospital(p.hospitalId).name)} · ${esc(p.region)}</p>${offerPrice(p)}<p>${esc(p.detail)}</p><small>${esc(p.ends)}까지 · 가상 이벤트</small></article>`).join('')}</div>`);}});

document.addEventListener('click',e=>{const b=e.target.closest('[data-action="home-filter"]');if(!b)return;const [category,...parts]=b.dataset.value.split(':');const row=b.closest('.home-filter-row'),left=row.scrollLeft;homeFilters[category]=parts.join(':');repaint();const selected=document.querySelector(`[data-action="home-filter"][data-value="${CSS.escape(b.dataset.value)}"]`);if(selected)selected.closest('.home-filter-row').scrollLeft=left;});

const treatmentNotes={
onda:['윤곽 고민을 상담할 때 확인할 장비 시술 후보예요.','지방·근육·피부 처짐 중 어떤 요인이 주된 고민인지 먼저 확인해요.','적용 부위, 장비 모드, 조사량과 추가 비용은 어떻게 되나요?'],
inmode:['같은 장비 이름이라도 사용하는 핸드피스와 구성에 따라 상담 내용이 달라져요.','FX 등 정확한 구성과 다른 윤곽 시술과의 차이를 비교해요.','제 고민에 사용하는 구성, 회복 중 관리와 멍 발생 가능성을 설명해 주세요.'],
botox:['보툴리눔 톡신은 특정 근육의 움직임을 줄이는 주사 시술이에요.','턱선 고민은 근육·지방·골격 등에 따라 접근이 달라져요.','근육과 관련된 고민인가요? 제품·용량·비대칭 등 주의사항은 무엇인가요?'],
ultrasound:['초음파 에너지를 이용하는 피부 탄력 시술 방식이에요.','고주파 방식과 적용 범위, 회복 계획을 비교해요.','사용 장비와 적용 깊이·샷 수, 피부 상태에 따른 주의사항은 무엇인가요?'],
rf:['고주파 에너지를 이용하는 탄력 시술 방식이에요.','장비별 구성과 부위, 시술 계획을 확인해요.','어떤 장비를 사용하나요? 마취·팁·사후 관리가 비용에 포함되나요?'],
care:['트러블은 현재 상태를 확인하고 관리와 치료 계획을 구분하는 것이 먼저예요.','관리만 받는 구성인지 진료와 약물 상담도 포함되는지 확인해요.','염증 상태에서 가능한 관리와 피해야 할 자극, 추가 진료가 필요한가요?'],
fractional:['피부에 분할된 형태로 레이저를 조사하는 방식으로, 흉터 상담에서 비교하는 후보예요.','흉터의 모양·깊이에 따라 다른 방법을 함께 상담할 수 있어요.','제 흉터 유형에 맞나요? 필요한 횟수와 색소 변화·회복 관리는 어떻게 되나요?'],
potenza:['장비 이름만으로 시술 구성이 같다고 판단하지 않고 사용 방식과 팁을 확인해요.','모공·피부결 중 원하는 변화와 현재 피부 상태를 함께 상담해요.','어떤 팁과 모드를 사용하나요? 마취·추가 제품 비용과 회복 계획은 무엇인가요?'],
aqua:['클렌징 관리의 범위와 구성은 병원마다 다를 수 있어요.','피지·블랙헤드 관리와 별도의 치료가 필요한 상태인지 구분해요.','압출이 포함되나요? 민감한 피부에 가능한 구성과 관리 간격은 어떻게 되나요?'],
toning:['색소 고민에서 비교하는 레이저 시술 후보예요. 기미와 다른 색소 문제는 구분이 필요해요.','기미는 약물·자외선 관리 등을 포함한 계획에서 레이저 여부를 상담해요.','색소의 원인은 무엇인가요? 레이저 외 방법과 색소 악화 가능성도 알려주세요.'],
vascular:['붉음의 원인과 혈관 상태를 살펴본 뒤 레이저·광 치료 여부를 상담해요.','홍조라는 증상만으로 장비나 횟수를 결정하지 않아요.','제 홍조의 원인은 무엇인가요? 약물이나 생활 관리도 필요한가요?'],
hairlaser:['레이저를 이용해 원치 않는 털을 줄이는 시술이에요.','피부색·모질·부위에 따라 계획이 달라지고 여러 차례 방문할 수 있어요.','부위 범위와 회차별 비용, 면도 시점과 피부 자극 관리는 어떻게 되나요?'],
consult:['고민의 원인과 가능한 선택지를 정리하는 진료 상담이에요.','시술이 꼭 필요한지, 관리나 다른 치료 방법은 없는지 함께 물어보세요.','어떤 평가가 필요하고 다음 단계는 무엇인가요?']
};
const treatmentSources={botox:'https://www.aad.org/public/cosmetic/wrinkles/botulinum-toxin-faqs',ultrasound:'https://www.aad.org/public/cosmetic/younger-looking/firm-sagging-skin',rf:'https://www.aad.org/public/cosmetic/younger-looking/firm-sagging-skin',fractional:'https://www.aad.org/public/diseases/acne/derm-treat/scars/treatment',toning:'https://www.aad.org/public/diseases/a-z/melasma-treatment',vascular:'https://www.aad.org/public/diseases/a-z/skin-conditions-lasers-treat',hairlaser:'https://www.aad.org/public/cosmetic/hair-removal/laser-hair-removal-faqs'};
function treatmentEducation(t,full=true){const n=treatmentNotes[t.id];if(!n)return '';return `<div class="treatment-education"><p><b>어떤 시술인가요?</b>${n[0]}</p>${full?`<p><b>비교할 점</b>${n[1]}</p>`:''}<p><b>상담에서 물어보세요</b>${n[2]}</p>${full&&treatmentSources[t.id]?`<a href="${treatmentSources[t.id]}" target="_blank" rel="noopener noreferrer">미국피부과학회 관련 정보</a>`:''}</div>`;}
function concernTreatmentIntro(){const ts=D.treatments.filter(t=>t.category===state.draft.category&&t.concerns.includes(state.draft.concern));return `<section class="concern-treatment-intro">${section(esc(state.draft.concern)+' · 상담에서 알아볼 시술')}<p class="tiny">고민과 연결된 정보예요. 실제 적합성은 피부 상태를 확인한 뒤 판단해요.</p>${ts.map(t=>`<article><h3>${esc(t.name)}</h3>${treatmentEducation(t)}${button('시술 상세 보기','treatment',t.id,'text-button')}</article>`).join('')||'<p class="info-box">등록된 시술 정보가 아직 없어요. 피부과 상담에서 가능한 방법을 확인해보세요.</p>'}</section>`;}
