/* View layer: keeps the existing catalog, scoring, comparison and storage services. */
let onboardingStep=0, exploreSub='all', exploreRegion='', communityTab='reviews', storyTag='all', communityQuery='';
const portrait=i=>'assets/skinmate-portrait.webp';
const brand=()=>'<span class="brand-image"><img src="assets/logo.jpg" alt="Skinmate"></span>';
paths.chat='M21 11a9 9 0 0 1-9 9H4l-3 2 1-6a9 9 0 1 1 19-5ZM7 11h.01M12 11h.01M17 11h.01';
paths.gear='M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1ZM16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0';
function header(title){const region=`<label class="region-control">${icon('pin')}<span class="sr-only">탐색 지역</span><select id="explore-region">${['전체',...D.regions].map(r=>`<option ${r===(exploreRegion||state.profile.region)?'selected':''}>${r}</option>`).join('')}</select></label>`;return `<header class="app-header">${title?`<div class="header-back">${button(icon('back'),'back','','icon-button','aria-label="뒤로 가기"')}<span class="header-title">${esc(title)}</span></div>`:screen==='explore'?region:brand()}<div class="header-actions">${button('<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg>','open-menu','','icon-button','aria-label="전체 메뉴"')}${screen==='my'?button('<span class="settings-image"><img src="assets/settings-gear.png" alt=""></span>','settings','전체','icon-button','aria-label="설정"'):button(icon('bell'),'notifications','','icon-button','aria-label="알림"')}</div></header>`;}

function nav(active){return `<nav class="bottom-nav" aria-label="주요 메뉴">${[['home','home','홈'],['explore','search','탐색'],['community','chat','커뮤니티'],['saved','bookmark','찜'],['my','user','마이']].map(([s,i,l])=>button(`${icon(i)}<span>${l}</span>`,'navigate',s,`nav-item ${active===s?'active':''}`,active===s?'aria-current="page"':'')).join('')}</nav>`;}
function photo(i,cls=''){return `<img class="${cls}" src="${portrait(i)}" alt="뷰티 분위기 이미지 예시" loading="lazy">`;}
function renderHome(){const concern=state.draft.concern||state.profile.concerns[0];const ps=[...D.promotions].sort((a,b)=>Number(interests().includes(b.category))-Number(interests().includes(a.category)));shell(`<section class="beauty-hero">${photo(0)}<span class="image-label">이미지 예시</span><div class="hero-copy"><span class="eyebrow">YOUR SKIN, YOUR MATE</span><h1>${concern?`${esc(concern)} 고민을<br>이어서 알아볼까요?`:'내 피부를 위한<br>선택의 시작'}</h1><p>고민을 나누고, 기준을 세우고.<br>나에게 맞는 선택을 함께해요.</p>${button((state.draft.concern?'추천 이어보기':'맞춤 추천 시작')+icon('arrow'),state.draft.concern?'resume':'start','','primary')}</div><span class="hero-note">나를 알아가는<br>작은 시작 ♡</span></section>${section('내 관심사',button('관리 ›','edit-profile','','text-button'))}<div class="horizontal-chips">${(state.profile.concerns.length?state.profile.concerns:['볼살','넓은 모공','피부톤','잔주름']).map((x,i)=>button(icon(['wave','pore','spark','sun'][i%4])+esc(x),'quick',x,'interest-chip')).join('')}</div>${section('내 관심사 이벤트 <span class="coral">✦</span>',button('전체보기 ›','navigate','explore','text-button'))}<div class="event-rail">${ps.map((p,i)=>beautyEvent(p,i)).join('')}</div>${section('찜한 병원 다시보기',button('전체보기 ›','navigate','saved','text-button'))}${state.saved.length?state.saved.slice(0,2).map(id=>`<article class="saved-preview">${icon('clinic')}<div><h3>${hospital(id).name}</h3><p>★ ${hospital(id).rating} · ${distance(hospital(id))}</p>${state.savedTreatments[id]?`<small>${treatment(state.savedTreatments[id]).name}</small>`:''}</div>${button(icon('arrow'),'detail',id,'icon-button',`aria-label="${hospital(id).name} 상세 보기"`)}</article>`).join(''):`<div class="soft-empty">${icon('bookmark')}<p>마음에 드는 병원을 저장하면<br>여기서 다시 만나볼 수 있어요.</p>${button('병원 둘러보기','navigate','explore','text-button')}</div>`}${section('피부 고민 노트')}${homeJournal()}${mockNote()}`);}
function beautyEvent(p,i=0){const saved=state.savedEvents.includes(p.id);return `<article class="beauty-event"><span class="ad-label">이벤트 · 가상 광고</span>${button(icon('bookmark'),'save-event',p.id,`bookmark-button ${saved?'is-saved':''}`,`aria-label="${p.title} 저장" aria-pressed="${saved}"`)}<div class="event-copy"><h3>${button(treatment(p.treatmentId).name,'event',p.id,'text-button')}</h3><p>${hospital(p.hospitalId).name}</p>${offerPrice(p)}<small>${distance(hospital(p.hospitalId))}</small></div></article>`;}
function promotionCard(p){return beautyEvent(p,D.promotions.indexOf(p));}
function renderOnboarding(){if(!profileDraft)profileDraft=structuredClone(state.profile);let body='';if(onboardingStep===0)body=`<div class="welcome-photo">${photo(0)}<span class="image-label">이미지 예시</span><span class="welcome-sticker">Hello,<br>Skinmate ♡</span></div>${heading('MEET YOUR SKINMATE','나를 알아가는<br>피부 여정, 함께해요.','몇 가지 관심사만 알려주세요.<br>나에게 가까운 정보부터 보여드릴게요.')}`;if(onboardingStep===1){body=profilePage(false);body=body.slice(0,body.indexOf('<label class="field" for="profile-region">'));body=body.replace('MY SKIN PROFILE','STEP 02 · MY INTERESTS').replace('나를 알아가는<br>피부 프로필','어떤 피부 고민이<br>궁금하세요?');}if(onboardingStep===2)body=`${heading('STEP 03 · MY NEIGHBORHOOD','어느 지역에서<br>만나볼까요?','가까운 지역의 병원과 이벤트를 먼저 모아드려요.')}<div class="region-grid">${D.regions.map(r=>button(icon('pin')+r,'onboard-region',r,`region-tile ${profileDraft.region===r?'active':''}`,`aria-pressed="${profileDraft.region===r}"`)).join('')}</div><div class="info-box">위치 권한 없이 선택한 지역만 사용해요.<br>설정은 마이페이지에서 바꿀 수 있어요.</div>`;if(onboardingStep===3)body=`<div class="complete-mark">${icon('check')}</div>${heading('READY, SKINMATE','나만의 피부 여정이<br>준비됐어요.','관심사에 맞는 정보부터 천천히 살펴보세요.')}<div class="profile-card">${tags(profileDraft.concerns.length?profileDraft.concerns:['자유롭게 둘러보기'])}<p>${icon('pin')} ${profileDraft.region}</p><p>관심 시술 ${profileDraft.fields.length}개</p></div>`;shell(`<div class="onboarding-progress" aria-label="${onboardingStep+1}/4 단계">${[0,1,2,3].map(n=>`<span class="${n<=onboardingStep?'on':''}"></span>`).join('')}<small>${onboardingStep+1}/4</small></div>${body}`,{bottom:false,footer:`<div class="footer-action onboarding-actions">${onboardingStep?button('이전','onboard-back','','secondary'):''}${button(onboardingStep===3?'시작하기':onboardingStep===0?'나의 관심사 알아보기':'다음','onboard-next','','primary')}</div>`});}
function clinicOffer(h,t,i){const p=D.promotions.find(p=>p.hospitalId===h.id&&p.treatmentId===t.id),saved=state.saved.includes(h.id)&&state.savedTreatments[h.id]===t.id;return `<article class="offer-card"><div class="offer-photo"><span class="ad-label">${p?'이벤트 · 가상 광고':'예시 정보'}</span>${button(icon('bookmark'),'save-offer',`${h.id}:${t.id}`,`bookmark-button ${saved?'is-saved':''}`,`aria-label="${h.name} ${t.name} 저장" aria-pressed="${saved}"`)}</div><div class="offer-copy"><p>${h.name}</p><h3>${button(t.name,'offer-detail',`${h.id}:${t.id}`,'text-button')}</h3>${offerPrice(h.exactOffers[t.id])}<p>${icon('pin')}${distance(h)}</p><small>★ ${h.rating} (${h.reviewCount}) · 1회 예시</small>${tags(t.concerns.slice(0,2))}</div></article>`;}
function renderExplore(){const region=exploreRegion||state.profile.region;const cat=D.concerns.find(c=>c.id===exploreCategory);const q=exploreQuery.toLocaleLowerCase();const list=D.treatments.filter(t=>(!cat||t.category===cat.id)&&(exploreSub==='all'||t.concerns.includes(exploreSub))).map(t=>({t,hs:D.hospitals.filter(h=>h.treatments.includes(t.id)&&(region==='전체'||h.location===region)&&[h.name,t.name,...t.concerns,...D.promotions.filter(p=>p.hospitalId===h.id&&p.treatmentId===t.id).map(p=>p.title)].join(' ').toLocaleLowerCase().includes(q))})).filter(x=>x.hs.length);shell(`<form class="explore-search" id="explore-search">${icon('search')}<input name="query" type="search" value="${esc(exploreQuery)}" placeholder="시술, 병원, 이벤트 검색" aria-label="시술, 병원, 이벤트 검색"><button type="submit">검색</button></form><div class="horizontal-chips category-tabs">${button('전체','beauty-category','all',`chip ${exploreCategory==='all'?'active':''}`)}${D.concerns.map(c=>button(icon(c.icon)+c.name,'beauty-category',c.id,`chip ${exploreCategory===c.id?'active':''}`)).join('')}</div><div class="horizontal-chips sub-tabs">${['all',...(cat?cat.items:[])].map(x=>button(x==='all'?'전체':x,'beauty-sub',x,`chip ${exploreSub===x?'active':''}`)).join('')}</div><section class="explore-banner">${photo(2)}<span class="image-label">이미지 예시</span><h2>${region==='전체'?'나의 기준으로':esc(region)+'에서'} 만나는<br>나를 위한 피부 선택</h2><p>시술별 가격을 한눈에 비교해요.</p></section>${list.map(({t,hs})=>`${section(t.name,button('시술 정보 ›','treatment',t.id,'text-button'))}<div class="offer-rail">${hs.map((h,i)=>clinicOffer(h,t,i)).join('')}</div>`).join('')||`<div class="soft-empty"><h2>일치하는 결과가 없어요.</h2><p>다른 지역이나 고민으로 찾아보세요.</p>${button('필터 초기화','beauty-clear','','primary')}</div>`}${mockNote()}`,{active:'explore'});}
function storyCard(r,i){const liked=state.community.likes.includes(r.id),helpful=state.community.helpful.includes(r.id);return `<article class="story-card"><div class="story-author">${photo(i)}<div><b>${['하루메이트','피부일기','모모'][i%3]}</b><small>${r.date} · 가상 후기</small></div><span>•••</span></div><h3>${treatment(r.treatmentId).name}, 상담에서 알게 된 것들</h3><p>${r.text}</p>${tags([r.concern,treatment(r.treatmentId).name,hospital(r.hospitalId).location])}<div class="story-metrics"><span>가격<b>${r.price}만원</b></span><span>통증<b>${r.pain.length>12?'개인차 있음':r.pain}</b></span><span>회복<b>${r.recovery}</b></span><span>만족도<b>★ ${r.satisfaction}.0</b></span></div><div class="pros-cons"><div><b>좋았던 점</b><p>상담 전에 정리한 질문으로 비용과 일정을 비교하기 편했어요.</p></div><div><b>아쉬웠던 점</b><p>추가 비용과 회복 중 주의사항은 따로 확인해야 했어요.</p></div></div><div class="story-actions">${button(icon('chat')+' '+(state.community.comments[r.id]?.length||0),'story-comments',r.id,'text-button','aria-label="댓글 보기"')}${button(icon('heart')+' '+(liked?'1':'0'),'story-like',r.id,`text-button ${liked?'coral':''}`,`aria-pressed="${liked}" aria-label="좋아요"`)}${button('도움돼요 '+icon('check'),'story-help',r.id,`text-button ${helpful?'active':''}`,`aria-pressed="${helpful}"`)}</div></article>`;}
function boardCard(p){return `<article class="board-card"><small>${esc(p.author)} · 예시 게시글</small><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p>${button(icon('chat')+' 댓글 '+(state.community.comments[p.id]?.length||0),'story-comments',p.id,'text-button')}</article>`;}
function renderCommunity(){const tagsList=['all',...new Set(D.reviews.map(r=>r.concern))];const q=communityQuery.trim().toLocaleLowerCase();const matches=values=>values.join(' ').toLocaleLowerCase().includes(q);const rs=D.reviews.filter(r=>matches([r.text,r.concern,treatment(r.treatmentId).name,hospital(r.hospitalId).name]));shell(`<div class="community-heading"><span class="eyebrow">TOGETHER, BETTER</span><h1>커뮤니티</h1><p>같은 고민을 하는 메이트들의 이야기</p></div><form class="explore-search" id="community-search">${icon('search')}<input name="query" type="search" value="${esc(communityQuery)}" placeholder="고민, 시술, 게시글 검색" aria-label="커뮤니티 검색"><button type="submit">검색</button></form><div class="community-tabs" role="tablist">${[['reviews','관심 후기'],['qa','Q&A'],['free','자유게시판']].map(([v,l])=>button(l,'story-tab',v,communityTab===v?'active':'',`role="tab" aria-selected="${communityTab===v}"`)).join('')}</div>${communityTab==='reviews'?`<p class="tiny">모든 후기는 가상 예시이며 실제 시술 경험이 아닙니다.</p>${rs.slice(0,8).map(storyCard).join('')||'<p class="info-box">검색 결과가 없어요.</p>'}${section('함께 묻는 Q&A',button('더보기 ›','story-tab','qa','text-button'))}${D.boards.qa.filter(p=>matches([p.title,p.body,p.author])).slice(0,2).map(boardCard).join('')}`:D.boards[communityTab].filter(p=>matches([p.title,p.body,p.author])).map(boardCard).join('')||'<p class="info-box">검색 결과가 없어요.</p>'}`,{active:'community'});}
function openStoryComments(id){dialog('메이트의 댓글',`<p class="tiny">이 기기에만 저장되는 댓글 체험입니다.</p><div class="comment-list">${(state.community.comments[id]||[]).map(c=>`<p><b>나의 댓글</b><br>${esc(c)}</p>`).join('')||'<p>첫 번째 이야기를 남겨보세요.</p>'}</div><form id="story-comment-form" data-id="${esc(id)}"><label class="field">댓글<textarea name="comment" maxlength="500" required placeholder="메이트에게 한마디"></textarea></label><button type="submit" class="primary">댓글 저장</button></form>`);}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,v=el.dataset.value;if(a==='onboard-next'){if(onboardingStep<3){onboardingStep++;render();}else if(update(()=>{state.profile=structuredClone(profileDraft);state.onboarded=true;})){profileDraft=null;go('home');}}else if(a==='onboard-back'){onboardingStep=Math.max(0,onboardingStep-1);render();}else if(a==='onboard-region'){profileDraft.region=v;repaint();}else if(a==='beauty-category'){const offset=el.closest('.category-tabs').scrollLeft;exploreCategory=v;exploreSub='all';repaint();document.querySelector('.category-tabs').scrollLeft=offset;}else if(a==='beauty-sub'){exploreSub=v;repaint();}else if(a==='beauty-clear'){exploreCategory='all';exploreSub='all';exploreQuery='';exploreRegion='전체';repaint();}else if(a==='save-offer'){const [hid,tid]=v.split(':');if(!hospital(hid)?.treatments.includes(tid))return;const isSame=state.saved.includes(hid)&&state.savedTreatments[hid]===tid;if(update(()=>{state.saved=isSame?state.saved.filter(x=>x!==hid):[...new Set([...state.saved,hid])];state.savedTreatments[hid]=tid;})){repaint();toast(isSame?'저장을 취소했어요.':'선택한 시술 가격과 함께 저장했어요.');}}else if(a==='offer-detail'){const [hid,tid]=v.split(':');if(update(()=>{state.selectedTreatment=tid;state.recentHospitals=[hid,...state.recentHospitals.filter(x=>x!==hid)].slice(0,20);} ))go('detail',hid);}else if(a==='story-tab'){communityTab=v;repaint();}else if(a==='story-tag'){storyTag=v;repaint();}else if(a==='story-like'||a==='story-help'){const k=a==='story-like'?'likes':'helpful';if(update(()=>{state.community[k]=state.community[k].includes(v)?state.community[k].filter(x=>x!==v):[...state.community[k],v];}))repaint();}else if(a==='story-comments')openStoryComments(v);});
document.addEventListener('change',e=>{if(e.target.id==='explore-region'){exploreRegion=e.target.value;repaint();}});
document.addEventListener('submit',e=>{if(e.target.id!=='story-comment-form')return;e.preventDefault();const text=String(new FormData(e.target).get('comment')||'').trim().slice(0,500),id=e.target.dataset.id;if(!text)return;const old=state.community.comments[id]||[];if(old.length>=100)return toast('댓글은 최대 100개까지 저장할 수 있어요.');if(update(()=>{state.community.comments[id]=[...old,text];})){e.target.closest('dialog').close();repaint();openStoryComments(id);}});

// Touch scroll stays native; mouse drag uses a threshold to preserve chip clicks.
let categoryDrag=null,categoryClickBlockedUntil=0;
document.addEventListener('pointerdown',e=>{
 const rail=e.target.closest('.category-tabs');
 if(!rail||e.pointerType!=='mouse'||e.button!==0)return;
 categoryClickBlockedUntil=0;
 categoryDrag={rail,id:e.pointerId,x:e.clientX,left:rail.scrollLeft,moved:false};
});
document.addEventListener('pointermove',e=>{
 const d=categoryDrag;if(!d||d.id!==e.pointerId)return;
 const dx=e.clientX-d.x;
 if(!d.moved&&Math.abs(dx)>5){d.moved=true;d.rail.setPointerCapture(e.pointerId);d.rail.classList.add('dragging');}
 if(d.moved){e.preventDefault();d.rail.scrollLeft=d.left-dx;}
});
function finishCategoryDrag(e){
 const d=categoryDrag;if(!d||d.id!==e.pointerId)return;
 if(d.moved)categoryClickBlockedUntil=Date.now()+400;
 d.rail.classList.remove('dragging');
 if(d.rail.hasPointerCapture(e.pointerId))d.rail.releasePointerCapture(e.pointerId);
 categoryDrag=null;
}
document.addEventListener('pointerup',finishCategoryDrag);
document.addEventListener('pointercancel',finishCategoryDrag);
document.addEventListener('click',e=>{
 if(e.detail!==0&&Date.now()<categoryClickBlockedUntil&&e.target.closest('.category-tabs')){e.preventDefault();e.stopImmediatePropagation();}
},true);

document.addEventListener('submit',e=>{if(e.target.id!=='community-search')return;e.preventDefault();communityQuery=String(new FormData(e.target).get('query')||'');repaint();});
document.addEventListener('click',e=>{if(!e.target.closest('[data-action="open-menu"]'))return;dialog('전체 메뉴',`<div class="menu-links">${[['home','홈'],['explore','탐색'],['community','커뮤니티'],['saved','찜'],['my','마이']].map(([route,label])=>`<button class="secondary" data-menu-route="${route}">${label}</button>`).join('')}</div>`);});
document.addEventListener('click',e=>{const b=e.target.closest('[data-menu-route]');if(!b)return;b.closest('dialog').close();go(b.dataset.menuRoute);});
