/* Layout matching the supplied six-screen Skinmate board. Data and ranking stay shared. */
const connectedDecisionScreen=renderDecisionScreen;
let hospitalSort='recommended';
function referenceProgress(){return '<ol class="reference-progress"><li class="active"><b>1</b>고민 선택</li><li><b>2</b>맞춤 분석</li><li><b>3</b>결과 보기</li></ol>';}
renderDecisionScreen=function(){
 if(['concern','subconcern','priority'].includes(screen)){
  const cat=D.concerns.find(c=>c.id===state.draft.category),c=L.resolveConcern(state.draft);
  shell(`${referenceProgress()}<section class="selection-section"><h1>어떤 고민이 있으신가요?</h1><p class="subtitle">가장 고민되는 유형을 선택해주세요.</p><div class="reference-categories decision-category-grid">${D.concerns.map(x=>button(`<span class="category-illustration">${icon(x.icon)}</span><b>${x.name}</b>`,'reference-category',x.id,'decision-category '+(cat?.id===x.id?'selected':''),`aria-pressed="${cat?.id===x.id}"`)).join('')}</div></section>${cat?`<section class="selection-section" id="sub-concerns"><h2>세부 고민을 선택해주세요.</h2><p class="subtitle">더 정확한 맞춤 추천을 위해 세부 고민을 선택해주세요.</p><div class="subconcern-grid">${cat.concernIds.map(id=>{const x=concernById(id);return button(x.name,'reference-concern',id,'subconcern-card '+(c?.id===id?'selected':''),`aria-pressed="${c?.id===id}"`);}).join('')}</div></section>`:''}${c?`<section class="selection-section"><h2>가장 중요하게 생각하는 요소는 무엇인가요?</h2><p class="subtitle">중요한 순서대로 최대 3개까지 선택할 수 있어요.</p><div class="priority-list">${D.criteria.map(PriorityCard).join('')}</div></section>`:''}${c&&state.draft.priorities.length?`<div class="selection-fields"><label class="field">예산 · 1회<select id="budget">${D.budgets.map(b=>`<option value="${b.id}" ${state.draft.budget===b.id?'selected':''}>${b.label}</option>`).join('')}</select></label><label class="field">방문 지역<select id="region">${D.regions.map(r=>`<option ${state.draft.region===r?'selected':''}>${r}</option>`).join('')}</select></label></div>`:''}`,{title:'',bottom:false,footer:c&&state.draft.priorities.length?foot('맞춤 추천 결과 보기','find'):''});return true;
 }
 if(screen==='hospitals'){
  const t=selected();if(!t)return connectedDecisionScreen();const ranked=L.rankHospitals(D.hospitals,t.id,state.draft),nearby=ranked.filter(h=>h.location===state.draft.region);let hs=showAllHospitalRegions?ranked:nearby.length>=4?nearby:[...nearby,...ranked.filter(h=>h.location!==state.draft.region)].slice(0,4);
  if(hospitalSort==='price')hs.sort((a,b)=>L.getOffer(a.id,t.id,L.resolveConcern(state.draft)?.id).price-L.getOffer(b.id,t.id,L.resolveConcern(state.draft)?.id).price);
  if(hospitalSort==='reviews')hs.sort((a,b)=>L.aggregateReviews(b.id,t.id).count-L.aggregateReviews(a.id,t.id).count);
  if(hospitalSort==='distance')hs.sort((a,b)=>a.distance-b.distance);
  shell(`<div class="hospital-sorts">${[['recommended','추천순'],['price','가격순'],['reviews','후기 많은 순'],['distance','거리순']].map(([v,l])=>button(l,'reference-sort',v,'chip '+(hospitalSort===v?'active':''),`aria-pressed="${hospitalSort===v}"`)).join('')}</div><div class="hospital-result-list">${hs.map(h=>HospitalRecommendationCard(h,t.id,state.draft)).join('')||'<p class="soft-empty">선택 지역에 등록된 병원이 없어요.</p>'}</div>${button(showAllHospitalRegions?'선택 지역만 보기':'다른 지역도 보기','hospital-region-toggle','','text-button')}${mockNote()}`,{title:t.name+' 병원 보기'});return true;
 }
 return connectedDecisionScreen();
};
function KnowledgeCard(c){const k=knowledgeFor(c),t=D.treatments.find(t=>t.concernIds.includes(c.id));return `<article class="knowledge-card">${treatmentImage(t,c.id)}<div><h3>${button(esc(k[0]),'article',c.id,'text-button')}</h3><p>${esc(k[1])}</p></div></article>`;}
const exploreIcons={onda:'wave',inmode:'wave',botox:'dots',ultrasound:'spark',rf:'bolt',care:'dots',fractional:'pore',potenza:'pore',aqua:'wave',toning:'sun',vascular:'heart',hairlaser:'bolt',consult:'chat'};
function exploreTreatmentPlaceholder(t){const category=D.concerns.find(c=>c.id===t.category);const pictogram=exploreIcons[t.id]||category?.icon||'spark';return `<div class="explore-image-placeholder" role="img" aria-label="${esc(t.name)} 이미지 준비 중">${icon(pictogram)}<span>이미지 준비 중</span></div>`;}
function exploreHospitalCandidates(t,region){const all=D.hospitals.filter(h=>L.getOffer(h.id,t.id));const local=all.filter(h=>region==='전체'||h.location===region);return local.length?local:all;}
function exploreHospitalPromo(h,t,compact=false){const o=L.getOffer(h.id,t.id),g=L.aggregateReviews(h.id,t.id),p=D.promotions.find(p=>p.hospitalId===h.id&&p.treatmentId===t.id);return button(`<span class="explore-promo-label">${p?'이벤트 · 가상 광고':'병원 홍보 · 가상 정보'}</span><b>${esc(h.name)}</b><small>${esc(h.location)} · ${g.count?`★ ${g.rating.toFixed(1)} · 후기 ${g.count}개`:'후기 준비 중'}</small>${p?`<span class="explore-promo-title">${esc(p.title)}</span>`:''}<strong>${(o.price*10000).toLocaleString('ko-KR')}원 <small>· 1회 예시</small></strong>`,'offer-detail',h.id+':'+t.id,'explore-hospital-promo'+(compact?' compact':''),`aria-label="${esc(h.name)} ${esc(t.name)} 병원 상세 보기"`);}
function exploreRelatedRail(title,items,region){return items.length?`<section class="explore-recommendations"><h2>${title}</h2><p class="tiny">연관 고민과 가상 후기 기준의 예시예요.</p><div class="explore-treatment-rail" aria-label="${title}">${items.slice(0,8).map(t=>`<article class="explore-related-card">${exploreTreatmentPlaceholder(t)}<strong>${esc(t.name)}</strong><small>후기 ${D.reviews.filter(r=>r.treatmentId===t.id).length}개 · 예시</small>${exploreHospitalCandidates(t,region).slice(0,1).map(h=>exploreHospitalPromo(h,t,true)).join('')}</article>`).join('')}</div></section>`:'';}
function renderExplore(){
 const region=exploreRegion||state.profile.region,cat=D.concerns.find(c=>c.id===exploreCategory),q=exploreQuery.trim().toLowerCase();
 const list=D.treatments.filter(t=>(!cat||t.categoryIds.includes(cat.id))&&(exploreSub==='all'||t.concerns.includes(exploreSub))).map(t=>({t,hs:D.hospitals.filter(h=>L.getOffer(h.id,t.id)&&(region==='전체'||h.location===region)&&[h.name,t.name,...t.concerns,...t.aliases].join(' ').toLowerCase().includes(q))})).filter(x=>x.hs.length);
 const related=cat?D.treatments.filter(t=>t.categoryIds.includes(cat.id)):[];const primary=related.find(t=>exploreSub!=='all'&&t.concerns.includes(exploreSub))||related[0],paired=related.filter(t=>t.id!==primary?.id).sort((a,b)=>((b.concernIds||[]).filter(id=>primary?.concernIds.includes(id)).length)-((a.concernIds||[]).filter(id=>primary?.concernIds.includes(id)).length));const reviewed=[...related].sort((a,b)=>D.reviews.filter(r=>r.treatmentId===b.id).length-D.reviews.filter(r=>r.treatmentId===a.id).length);
 shell(`<div class="explore-intro"><form class="explore-search" id="explore-search">${icon('search')}<input name="query" type="search" value="${esc(exploreQuery)}" placeholder="시술, 병원, 고민을 검색해보세요." aria-label="탐색 검색"><button type="submit">검색</button></form></div><div class="explore-paper"><div class="reference-categories explore-category-rail" aria-label="관심 분야">${button('전체','decision-explore-category','all','decision-category '+(!cat?'selected':''),`aria-pressed="${!cat}"`)}${D.concerns.map(c=>button(`<span class="category-illustration">${icon(c.icon)}</span><b>${c.name}</b>`,'decision-explore-category',c.id,'decision-category '+(cat?.id===c.id?'selected':''),`aria-pressed="${cat?.id===c.id}"`)).join('')}</div>${section(cat?cat.name+' 시술':'인기 시술')}${cat?`<div class="horizontal-chips sub-tabs">${button('전체','decision-explore-sub','all','chip '+(exploreSub==='all'?'active':''))}${cat.items.map(n=>button(n,'decision-explore-sub',n,'chip '+(exploreSub===n?'active':''))).join('')}</div>`:''}<div class="explore-results">${list.slice(0,exploreLimit).map(({t,hs})=>`<article class="explore-treatment"><div class="explore-treatment-main">${exploreTreatmentPlaceholder(t)}<div><h2>${esc(t.name)}</h2><p>${hs.length}곳의 병원에서 상담 가능한 시술 · 예시</p></div></div><div class="explore-hospital-rail" aria-label="${esc(t.name)} 병원 홍보">${hs.slice(0,4).map(h=>exploreHospitalPromo(h,t)).join('')}</div></article>`).join('')||'<p class="soft-empty">일치하는 시술·병원이 없어요.</p>'}${list.length>exploreLimit?button('시술 목록 더보기','explore-more','','secondary load-more'):''}</div>${cat?exploreRelatedRail('함께 많이 받는 시술',paired.length?paired:related,region)+exploreRelatedRail('후기 많은 시술',reviewed,region):''}<section class="clinic-ad"><img src="assets/promise-logo.png" alt="프라미스 피부과 광고 시안"><span>광고 시안</span></section>${mockNote()}</div>`,{active:'explore'});
}
const baseReviewCard=ReviewCard;
ReviewCard=function(r){const t=treatment(r.treatmentId);return `<article class="reference-review"><div class="review-author"><span class="review-avatar">${icon('user')}</span><div><b>${esc(r.userId||'메이트')}</b><small>${esc(String(r.createdAt||r.date).slice(0,10))} · 체험 후기</small></div></div><h3>${button(esc(t.name)+' 후기','treatment',t.id,'text-button')}</h3><div class="review-photo">${treatmentImage(t)}</div><div class="review-metrics">${[['effectRating','효과'],['recoveryRating','회복'],['painRating','통증'],['doctorTrustRating','의료진 설명']].map(([key,label])=>`<span>${label}<b>${Number(r[key]).toFixed(1)} / 5</b></span>`).join('')}</div><p>${esc(r.content)}</p><details><summary>추천에 반영된 평가 보기</summary><p>가격 만족 ${r.priceRating}/5 · 거리 만족 ${r.distanceRating}/5</p><small>통증·회복은 부담이 적고 만족할수록 높은 점수예요.</small></details>${button('병원·시술 후기 보기','decision-reviews',r.hospitalId+':'+r.treatmentId,'text-button')}</article>`;};
function renderCommunity(){const c=activeConcernRecord(),q=communityQuery.trim().toLowerCase();let rs=D.reviews.filter(r=>[r.content,treatment(r.treatmentId).name,hospital(r.hospitalId).name,r.concern].join(' ').toLowerCase().includes(q));if(!q&&c)rs=rs.filter(r=>treatment(r.treatmentId).concernIds.includes(c.id));const posts=(D.boards[communityTab]||[]).filter(p=>(p.title+p.body).includes(communityQuery));shell(`<div class="community-tabs" role="tablist">${[['reviews','관심 후기'],['qa','Q&A'],['free','자유게시판']].map(([v,l])=>button(l,'story-tab',v,communityTab===v?'active':'',`role="tab" aria-selected="${communityTab===v}"`)).join('')}</div><div class="community-paper"><form class="community-search" id="community-search">${icon('search')}<input name="query" type="search" value="${esc(communityQuery)}" placeholder="고민, 시술, 게시글 검색" aria-label="커뮤니티 검색"><button type="submit">검색</button></form>${communityTab==='reviews'?rs.slice(0,reviewLimit).map(ReviewCard).join('')+(rs.length>reviewLimit?button('후기 더보기','reviews-more','','secondary load-more'):''):posts.map(boardCard).join('')}${(communityTab==='reviews'?!rs.length:!posts.length)?'<p class="soft-empty">검색 결과가 없어요.</p>':''}${communityTab==='reviews'?`${section('Q&A',button('전체보기','story-tab','qa','text-button'))}${(D.boards.qa||[]).slice(0,1).map(boardCard).join('')}${section('자유게시판',button('전체보기','story-tab','free','text-button'))}${(D.boards.free||[]).slice(0,1).map(boardCard).join('')}`:''}${mockNote()}</div>`,{active:'community'});}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,v=el.dataset.value;if(!['reference-category','reference-concern','reference-sort'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();
 if(a==='reference-category'&&D.concerns.some(c=>c.id===v)){if(update(()=>{state.draft.category=state.draft.category===v?'':v;state.draft.concern='';delete state.draft.concernId;state.draft.priorities=[];state.selectedTreatment='';}))repaint();}
 if(a==='reference-concern'){const c=concernById(v);if(c?.categoryId===state.draft.category&&update(()=>{const deselect=state.draft.concernId===c.id;state.draft.concern=deselect?'':c.name;if(deselect)delete state.draft.concernId;else state.draft.concernId=c.id;state.draft.priorities=[];state.selectedTreatment='';}))repaint();}
 if(a==='reference-sort'){hospitalSort=v;repaint();}
},true);

// Touch uses native horizontal scrolling; mouse users can drag the category rail.
let referenceCategoryDrag=null;
document.addEventListener('pointerdown',e=>{const rail=e.target.closest('.explore-category-rail,.sub-tabs,.explore-treatment-rail,.explore-hospital-rail,.hospital-event-rail');if(!rail||e.pointerType!=='mouse'||e.button!==0)return;referenceCategoryDrag={rail,x:e.clientX,left:rail.scrollLeft,moved:false};});
document.addEventListener('pointermove',e=>{if(!referenceCategoryDrag)return;const delta=e.clientX-referenceCategoryDrag.x;if(Math.abs(delta)>5){referenceCategoryDrag.moved=true;referenceCategoryDrag.rail.scrollLeft=referenceCategoryDrag.left-delta;e.preventDefault();}});
document.addEventListener('pointerup',()=>{const drag=referenceCategoryDrag;referenceCategoryDrag=null;if(drag?.moved){const cancel=e=>{if(drag.rail.contains(e.target)){e.preventDefault();e.stopImmediatePropagation();}};window.addEventListener('click',cancel,{capture:true,once:true});setTimeout(()=>window.removeEventListener('click',cancel,true),0);}});
document.addEventListener('pointercancel',()=>{referenceCategoryDrag=null;});
