/* Layout matching the supplied six-screen Skinmate board. Data and ranking stay shared. */
const connectedDecisionScreen=renderDecisionScreen;
let hospitalSort='recommended';
function referenceProgress(){return '<ol class="reference-progress"><li class="active"><b>1</b>고민 선택</li><li><b>2</b>맞춤 분석</li><li><b>3</b>결과 보기</li></ol>';}
renderDecisionScreen=function(){
 if(['concern','subconcern','priority'].includes(screen)){
  const cat=D.concerns.find(c=>c.id===state.draft.category),c=L.resolveConcern(state.draft);
  shell(`${referenceProgress()}<section class="selection-section"><h1>어떤 고민이 있으신가요?</h1><p class="subtitle">가장 고민되는 유형을 선택해주세요.</p><div class="reference-categories decision-category-grid">${D.concerns.map(x=>button(`<span class="category-illustration">${icon(x.icon)}</span><b>${x.name}</b>`,'reference-category',x.id,'decision-category '+(cat?.id===x.id?'selected':''),`aria-pressed="${cat?.id===x.id}"`)).join('')}</div></section><section class="selection-section"><h2>세부 고민을 선택해주세요.</h2><p class="subtitle">더 정확한 맞춤 추천을 위해 세부 고민을 선택해주세요.</p>${cat?`<div class="subconcern-grid">${cat.concernIds.map(id=>{const x=concernById(id);return button(x.name,'reference-concern',id,'subconcern-card '+(c?.id===id?'selected':''),`aria-pressed="${c?.id===id}"`);}).join('')}</div>`:'<p class="selection-hint">위에서 관심 분야를 먼저 선택해주세요.</p>'}</section><section class="selection-section"><h2>가장 중요하게 생각하는 요소는 무엇인가요?</h2><p class="subtitle">중요한 순서대로 최대 3개까지 선택할 수 있어요.</p><div class="priority-list">${D.criteria.map(PriorityCard).join('')}</div></section><div class="selection-fields"><label class="field">예산 · 1회<select id="budget">${D.budgets.map(b=>`<option value="${b.id}" ${state.draft.budget===b.id?'selected':''}>${b.label}</option>`).join('')}</select></label><label class="field">방문 지역<select id="region">${D.regions.map(r=>`<option ${state.draft.region===r?'selected':''}>${r}</option>`).join('')}</select></label></div>`,{title:'',bottom:false,footer:foot('맞춤 추천 결과 보기','find',!c||!state.draft.priorities.length)});return true;
 }
 if(screen==='hospitals'){
  const t=selected();if(!t)return connectedDecisionScreen();let hs=L.rankHospitals(D.hospitals,t.id,state.draft).filter(h=>showAllHospitalRegions||h.location===state.draft.region);
  if(hospitalSort==='price')hs.sort((a,b)=>L.getOffer(a.id,t.id,L.resolveConcern(state.draft)?.id).price-L.getOffer(b.id,t.id,L.resolveConcern(state.draft)?.id).price);
  if(hospitalSort==='reviews')hs.sort((a,b)=>L.aggregateReviews(b.id,t.id).count-L.aggregateReviews(a.id,t.id).count);
  if(hospitalSort==='distance')hs.sort((a,b)=>a.distance-b.distance);
  shell(`<div class="hospital-sorts">${[['recommended','추천순'],['price','가격순'],['reviews','후기 많은 순'],['distance','거리순']].map(([v,l])=>button(l,'reference-sort',v,'chip '+(hospitalSort===v?'active':''),`aria-pressed="${hospitalSort===v}"`)).join('')}</div><div class="hospital-result-list">${hs.map(h=>HospitalRecommendationCard(h,t.id,state.draft)).join('')||'<p class="soft-empty">선택 지역에 등록된 병원이 없어요.</p>'}</div>${button(showAllHospitalRegions?'선택 지역만 보기':'다른 지역도 보기','hospital-region-toggle','','text-button')}${mockNote()}`,{title:t.name+' 병원 보기'});return true;
 }
 return connectedDecisionScreen();
};
function KnowledgeCard(c){const k=knowledgeFor(c),t=D.treatments.find(t=>t.concernIds.includes(c.id));return `<article class="knowledge-card">${treatmentImage(t,c.id)}<div><h3>${button(esc(k[0]),'article',c.id,'text-button')}</h3><p>${esc(k[1])}</p></div></article>`;}
function renderExplore(){
 const region=exploreRegion||state.profile.region,cat=D.concerns.find(c=>c.id===exploreCategory),q=exploreQuery.trim().toLowerCase();
 const list=D.treatments.filter(t=>(!cat||t.categoryIds.includes(cat.id))&&(exploreSub==='all'||t.concerns.includes(exploreSub))).map(t=>({t,hs:D.hospitals.filter(h=>L.getOffer(h.id,t.id)&&(region==='전체'||h.location===region)&&[h.name,t.name,...t.concerns,...t.aliases].join(' ').toLowerCase().includes(q))})).filter(x=>x.hs.length);
 shell(`<div class="explore-intro"><form class="explore-search" id="explore-search">${icon('search')}<input name="query" type="search" value="${esc(exploreQuery)}" placeholder="시술, 병원, 고민을 검색해보세요." aria-label="탐색 검색"><button type="submit" aria-label="검색">검색</button></form></div><div class="explore-paper"><div class="reference-categories">${D.concerns.map(c=>button(`<span class="category-illustration">${icon(c.icon)}</span><b>${c.name}</b>`,'decision-explore-category',c.id,'decision-category '+(cat?.id===c.id?'selected':''),`aria-pressed="${cat?.id===c.id}"`)).join('')}</div>${section(cat?cat.name+' 시술':'인기 시술',button('전체보기','decision-explore-category','all','text-button'))}<div class="horizontal-chips sub-tabs">${button('전체','decision-explore-category','all','chip '+(!cat?'active':''))}${cat?cat.items.map(n=>button(n,'decision-explore-sub',n,'chip '+(exploreSub===n?'active':''))).join(''):D.concerns.slice(0,6).map(c=>button(c.name.split('·')[0],'decision-explore-category',c.id,'chip')).join('')}</div><div class="explore-results">${list.slice(0,exploreLimit).map(({t,hs})=>`<article class="explore-treatment"><div class="explore-treatment-main">${treatmentImage(t)}<div><h2>${button(t.name,'treatment',t.id,'text-button')}</h2><p>${esc(t.summary)}</p>${tags(t.tags.slice(0,3))}</div></div><div class="explore-offers">${hs.slice(0,2).map(h=>{const o=L.getOffer(h.id,t.id);return button(`<img src="assets/photos/clinic.webp" alt="병원 공간 예시" loading="lazy"><span><b>${h.name}</b><small>★ ${L.aggregateReviews(h.id,t.id).rating.toFixed(1)} · ${h.location}</small></span><strong>${(o.price*10000).toLocaleString('ko-KR')}원</strong>`,'offer-detail',h.id+':'+t.id,'explore-offer');}).join('')}</div></article>`).join('')||'<p class="soft-empty">일치하는 시술·병원이 없어요.</p>'}${list.length>exploreLimit?button('시술 목록 더보기','explore-more','','secondary load-more'):''}</div><section class="clinic-ad"><img src="assets/promise-logo.png" alt="프라미스 피부과 광고 시안"><span>광고 시안</span></section>${mockNote()}</div>`,{active:'explore'});
}
const baseReviewCard=ReviewCard;
ReviewCard=function(r){const t=treatment(r.treatmentId);return `<article class="reference-review"><div class="review-author"><span class="review-avatar">${icon('user')}</span><div><b>${esc(r.userId||'메이트')}</b><small>${esc(String(r.createdAt||r.date).slice(0,10))} · 체험 후기</small></div></div><h3>${button(esc(t.name)+' 후기','treatment',t.id,'text-button')}</h3><div class="review-photo">${treatmentImage(t)}</div><div class="review-metrics">${[['effectRating','효과'],['recoveryRating','회복'],['painRating','통증'],['doctorTrustRating','의료진 설명']].map(([key,label])=>`<span>${label}<b>${Number(r[key]).toFixed(1)} / 5</b></span>`).join('')}</div><p>${esc(r.content)}</p><details><summary>추천에 반영된 평가 보기</summary><p>가격 만족 ${r.priceRating}/5 · 거리 만족 ${r.distanceRating}/5</p><small>통증·회복은 부담이 적고 만족할수록 높은 점수예요.</small></details>${button('병원·시술 후기 보기','decision-reviews',r.hospitalId+':'+r.treatmentId,'text-button')}</article>`;};
function renderCommunity(){const c=activeConcernRecord(),q=communityQuery.trim().toLowerCase();let rs=D.reviews.filter(r=>[r.content,treatment(r.treatmentId).name,hospital(r.hospitalId).name,r.concern].join(' ').toLowerCase().includes(q));if(!q&&c)rs=rs.filter(r=>treatment(r.treatmentId).concernIds.includes(c.id));const posts=(D.boards[communityTab]||[]).filter(p=>(p.title+p.body).includes(communityQuery));shell(`<div class="community-tabs" role="tablist">${[['reviews','관심 후기'],['qa','Q&A'],['free','자유게시판']].map(([v,l])=>button(l,'story-tab',v,communityTab===v?'active':'',`role="tab" aria-selected="${communityTab===v}"`)).join('')}</div><div class="community-paper"><form class="community-search" id="community-search">${icon('search')}<input name="query" type="search" value="${esc(communityQuery)}" placeholder="고민, 시술, 게시글 검색" aria-label="커뮤니티 검색"><button type="submit">검색</button></form>${communityTab==='reviews'?rs.slice(0,reviewLimit).map(ReviewCard).join('')+(rs.length>reviewLimit?button('후기 더보기','reviews-more','','secondary load-more'):''):posts.map(boardCard).join('')}${(communityTab==='reviews'?!rs.length:!posts.length)?'<p class="soft-empty">검색 결과가 없어요.</p>':''}${communityTab==='reviews'?`${section('Q&A',button('전체보기','story-tab','qa','text-button'))}${(D.boards.qa||[]).slice(0,1).map(boardCard).join('')}${section('자유게시판',button('전체보기','story-tab','free','text-button'))}${(D.boards.free||[]).slice(0,1).map(boardCard).join('')}`:''}${mockNote()}</div>`,{active:'community'});}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,v=el.dataset.value;if(!['reference-category','reference-concern','reference-sort','replay-entry'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();
 if(a==='reference-category'&&D.concerns.some(c=>c.id===v)){if(update(()=>{state.draft.category=v;state.draft.concern='';delete state.draft.concernId;state.selectedTreatment='';}))repaint();}
 if(a==='reference-concern'){const c=concernById(v);if(c?.categoryId===state.draft.category&&update(()=>{state.draft.concern=c.name;state.draft.concernId=c.id;}))repaint();}
 if(a==='reference-sort'){hospitalSort=v;repaint();}
 if(a==='replay-entry'){if(update(()=>{state.auth={loggedIn:false,email:''};state.onboarded=false;state.activeConcern=null;state.activeConcernCategory=null;state.recommendation=null;state.draft=structuredClone(SkinmateStorage.initial.draft);state.history=[];})){profileDraft=null;onboardCategories=[];onboardingStep=0;go('login');}}
},true);
