function renderSecondary(){
 if(screen==='compare'){renderComparison();return;}
 if(screen==='explore'){renderExplore();return;}
 if(screen==='event'){const p=D.promotions.find(p=>p.id===routeId);if(!p){shell('이벤트 정보를 찾지 못했어요.',{active:'explore'});return;}shell(`<span class="ad-label">프로모션 · 가상 광고</span>${heading('',p.title,p.detail)}<div class="editorial-art ${p.category}"><span>A little care,<br>for yourself.</span><img src="assets/symbol.png" alt=""></div><div class="data-row"><span>병원</span><b>${hospital(p.hospitalId).name}</b></div><div class="data-row"><span>예시 가격</span><b>${offerPrice(p)}</b></div><div class="data-row"><span>예시 기간</span><b>${p.ends}까지</b></div><div class="info-box">예약이나 결제가 진행되지 않는 학습용 이벤트예요. 실제 조건·가격을 안내하는 광고가 아닙니다.</div>${button(state.savedEvents.includes(p.id)?'이벤트 찜 취소':'이벤트 찜','save-event',p.id)}${button('병원 상세 보기','detail',p.hospitalId)}${mockNote()}`,{title:'이벤트 상세',active:'explore'});return;}
 if(screen==='saved'){const ranked=L.rankHospitals(D.hospitals,state.selectedTreatment,state.draft);shell(`<div class="saved-content"><div class="chip-row" role="tablist" aria-label="찜 종류">${['병원','이벤트'].map(t=>button(t,'save-tab',t,`chip ${saveTab===t?'active':''}`,`role="tab" aria-selected="${saveTab===t}"`)).join('')}</div>${saveTab==='병원'?(state.saved.length?state.saved.map(id=>hospitalCard(ranked.find(h=>h.id===id)||hospital(id))).join(''):`<div class="empty"><img src="assets/symbol.png" alt=""><h2>마음에 드는 병원을 담아보세요.</h2><p>저장한 병원을 같은 기준으로 비교할 수 있어요.</p>${button('맞춤 추천 시작하기','start','','primary')}</div>`):(state.savedEvents.length?state.savedEvents.map(id=>savedEventCard(D.promotions.find(p=>p.id===id))).join(''):`<div class="empty"><h2>아직 찜한 이벤트가 없어요.</h2>${button('이벤트 둘러보기','navigate','explore')}</div>`)}</div>`,{active:'saved',footer:(saveTab==='병원'?state.saved.length:state.savedEvents.length)?`<div class="footer-action">${button(saveTab==='병원'?'선택한 병원 비교하기':'선택한 이벤트 비교하기',saveTab==='병원'?'compare':'compare-events','','primary',(saveTab==='병원'?state.compare.filter(id=>state.saved.includes(id)).length:comparedEvents.filter(id=>state.savedEvents.includes(id)).length)<2?'disabled':'')}</div>`:''});return;}
 if(screen==='my'){renderMy();return;}
 if(screen==='checklist'){renderChecklist();return;}
 if(screen==='activity'){let body='';if(routeId==='최근 본 병원')body=state.recentHospitals.map(id=>hospitalCard(hospital(id))).join('');if(routeId==='최근 본 시술')body=state.recentTreatments.map(id=>treatmentCard(treatment(id))).join('');if(routeId==='상담 기록')body=Object.entries(state.checklists).map(([id,l])=>button(`<span><b>${hospital(id).name}</b><small>${l.saved?'저장됨':'작성 중'} · 질문 ${l.questions.length}개</small></span>${icon('arrow')}`,'open-checklist',id,'saved-checklist')).join('');if(routeId==='예정된 예약')body=(state.bookings||[]).filter(x=>x.type==='online'||x.date>=new Date().toISOString().slice(0,10)).map(x=>`<article class="activity-record"><b>${esc(hospital(x.hospitalId).name)}</b><p>${esc(treatment(x.treatmentId).name)} · ${x.type==='online'?'온라인 상담':`${esc(x.date)} ${esc(x.time)}`}</p><small>상담 예약 체험 · 실제 예약 아님</small>${button('병원 보기','detail',x.hospitalId,'text-button')}</article>`).join('');if(routeId==='결제 내역')body=(state.payments||[]).map(x=>`<article class="activity-record"><b>${esc(hospital(x.hospitalId).name)}</b><p>${esc(treatment(x.treatmentId).name)} · ${(x.price*10000).toLocaleString('ko-KR')}원</p><small>${esc(x.createdAt.slice(0,10))} · 체험 결제 · 실제 청구 없음</small>${button('병원 보기','detail',x.hospitalId,'text-button')}</article>`).join('');shell(`${heading('',esc(routeId))}${body||`<div class="empty"><img src="assets/symbol.png" alt=""><h2>아직 ${esc(routeId)} 내역이 없어요.</h2><p>실제 예약·결제·회원 활동은 연결되어 있지 않아요.</p>${button('탐색으로 이동','navigate','explore')}</div>`}`,{title:routeId,active:'my'});return;}
 if(screen==='settings'){let body=routeId==='전체'?`<div class="settings-card">${['알림','개인정보','고객센터'].map(x=>setting(x,'settings',x)).join('')}${setting('로그인·온보딩 다시 체험하기','replay-entry','')}${state.auth?.loggedIn?setting('로그아웃','logout',''):setting('로그인','login','')}</div>`:routeId==='알림'?`<label class="checkbox-label"><input id="notifications" type="checkbox" ${state.notifications?'checked':''}> 관심 콘텐츠 알림 설정</label><p class="info-box">설정값만 이 기기에 보관하며 실제 알림은 발송되지 않아요.</p>`:routeId==='개인정보'?`<p class="subtitle">관심사·찜·상담 질문은 이 브라우저에만 저장돼요. 서버로 전송하지 않습니다.</p>${button('이 기기 데이터 삭제','reset','','secondary')}`:routeId==='로그아웃'?'<p class="info-box">현재 게스트 체험 중이에요. 연결된 계정이 없어 로그아웃할 필요가 없습니다.</p>':'<div class="info-box"><b>자주 묻는 질문</b><p>실제 예약이 가능한가요?<br>학습용 프로젝트로 예약·결제는 제공하지 않아요.</p><p>추천은 어떻게 정렬하나요?<br>받은 시술의 후기 평가를 선택 기준 순서대로 비교해요. 후기가 적으면 근거가 제한적임을 표시해요.</p><p>저장은 어디에 되나요?<br>현재 브라우저에 보관됩니다.</p></div>';shell((routeId==='전체'?'':heading('',esc(routeId)))+body,{title:routeId==='전체'?'설정':routeId,active:'my'});return;}
}
function renderComparison(){renderReviewComparison();}
function getList(){return state.checklists[routeId]||{saved:false,questions:['기대하는 변화와 고려할 수 있는 대안은 무엇인가요?','총비용에 마취와 사후 관리가 포함되나요?','회복기간과 주의사항은 무엇인가요?'].map(text=>({text,done:false}))};}
function renderChecklist(){const h=hospital(routeId);if(!h){shell('병원을 먼저 선택해주세요.');return;}const l=getList();shell(`${heading('READY FOR YOUR VISIT','궁금한 점을,<br>미리 챙겨볼까요?',h.name+' 상담 질문')}<div class="questions">${l.questions.map((q,i)=>`<div class="question ${q.done?'done':''}"><label><input type="checkbox" data-question="${i}" ${q.done?'checked':''}><span>${esc(q.text)}</span></label>${button(icon('close'),'delete-question',i,'icon-button','aria-label="질문 삭제"')}</div>`).join('')}</div><form class="question-form" id="question-form"><input name="question" type="text" maxlength="200" aria-label="직접 질문 추가" placeholder="궁금한 점을 적어보세요" required><button aria-label="질문 추가">${icon('plus')}</button></form><div class="info-box">작성한 질문은 마이 → 상담 기록에서 다시 볼 수 있어요. 질문 저장은 실제 상담 예약이 아니에요.</div>`,{title:'상담 체크리스트',active:'my',footer:foot('체크리스트 저장하기','save-checklist',!l.questions.length)});}
