const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const listeners={},els={app:{innerHTML:'',setAttribute(){}},main:{scrollTop:0,focus(){}},toast:{classList:{add(){},remove(){}}}},stored={},session={'skinmate-login-session':'active'};
const c={structuredClone,console,setTimeout(){},clearTimeout(){},sessionStorage:{getItem:k=>session[k]||null,setItem:(k,v)=>session[k]=v,removeItem:k=>delete session[k]},localStorage:{getItem:k=>stored[k]||null,setItem:(k,v)=>stored[k]=v},document:{getElementById:id=>els[id],addEventListener:(n,f,opt)=>(listeners[n]??=[]).push({f,capture:opt===true}),querySelector(){return null}},window:{addEventListener(){}},history:{state:null,replaceState(){},pushState(){}},location:{hash:''}};
stored['skinmate-v2']=JSON.stringify({auth:{loggedIn:true},onboarded:true});
vm.createContext(c);const run=s=>vm.runInContext(s,c);
const files=['data/catalog.js','data/relations.js','services/recommendations.js','services/storage.js','components.js','views.js','redesign.js','decision-ui.js','reference-ui.js','app.js'];for(const f of files)run(fs.readFileSync(f,'utf8'));
assert.equal(run('screen'),'home'); // a returning signed-in user stays on the saved route
const click=(a,v='')=>{let stop=false;const el={dataset:{action:a,value:v}};for(const {f} of [...listeners.click].sort((a,b)=>Number(b.capture)-Number(a.capture))){if(stop)break;f({target:{closest:selector=>selector==='[data-action]'?el:null},preventDefault(){},stopImmediatePropagation(){stop=true;}});}};
run("state.auth.loggedIn=true;state.onboarded=true;state.profile.concerns=['여드름 흉터'];state.profile.region='강남';screen='home';render()");
assert(els.app.innerHTML.includes('여드름 흉터,'));const fallback=els.app.innerHTML;
click('start');assert(els.app.innerHTML.includes('decision-category-grid'));assert(!els.app.innerHTML.includes('subconcern-grid'));
click('reference-category','contour');assert.equal(run('screen'),'concern');assert(els.app.innerHTML.includes('사각턱'));assert(!els.app.innerHTML.includes('여드름 흉터'));
click('reference-concern','squareJaw');click('to-priority');for(const k of ['trust','recovery','price'])click('priority',k);click('priority','effect');assert.equal(run('state.draft.priorities.length'),3);click('find');assert.equal(run('state.activeConcern'),'squareJaw');assert.equal(run('screen'),'treatments');assert(els.app.innerHTML.includes('사각턱 보톡스'));assert(!els.app.innerHTML.includes('프락셔널 레이저'));assert(!/일치도|50%|30%|20%/.test(els.app.innerHTML));
click('decision-hospitals','botox');assert.equal(run('screen'),'hospitals');assert.equal(run('state.selectedTreatment'),'botox');assert(els.app.innerHTML.includes('decision-reason'));assert((els.app.innerHTML.match(/connected-hospital/g)||[]).length>=4);
const before=run("L.aggregateReviews('h1','botox').count");const reason=run("ReasonSheetContent('h1','botox')");assert(reason.includes('8건 중'));assert.notEqual(reason,run("ReasonSheetContent('h2','botox')"));
click('save-offer','h1:botox');assert.equal(run('screen'),'hospitals');assert(run("state.saved.includes('h1')"));click('offer-detail','h1:botox');assert.equal(run('screen'),'treatment');assert.equal(run('routeId'),'h1:botox');assert(els.app.innerHTML.includes('이 병원의 사각턱 보톡스 후기'));assert(els.app.innerHTML.includes('메이트 피부과'));click('detail','h1');assert.equal(run('screen'),'detail');assert(els.app.innerHTML.includes('detail-header-name'));assert(els.app.innerHTML.includes('hospital-detail-tabs'));assert(els.app.innerHTML.includes('의료진 소개'));assert(els.app.innerHTML.includes('진료시간'));assert(els.app.innerHTML.includes('주차 가능'));assert(els.app.innerHTML.includes('02-0000-1001'));assert(!els.app.innerHTML.includes('진행하는 시술'));assert.equal((els.app.innerHTML.match(/class="hospital-treatment-row"/g)||[]).length,0);
click('hospital-detail-tab','treatments');assert.equal((els.app.innerHTML.match(/class="hospital-treatment-row"/g)||[]).length,3);click('hospital-detail-treatments-more');assert.equal((els.app.innerHTML.match(/class="hospital-treatment-row"/g)||[]).length,6);
assert(run("D.hospitals.every(h=>{const events=D.promotions.filter(p=>p.hospitalId===h.id);return events.length>=4&&new Set(events.map(p=>p.treatmentId)).size===events.length&&events.every(p=>L.getOffer(h.id,p.treatmentId))})"));
click('hospital-detail-tab','events');assert(els.app.innerHTML.includes('hospital-detail-event-list'));assert(!els.app.innerHTML.includes('hospital-event-rail'));assert.equal((els.app.innerHTML.match(/class="promotion-card connected-promotion"/g)||[]).length,3);assert(els.app.innerHTML.includes('이벤트 더보기'));click('hospital-detail-events-more');assert.equal((els.app.innerHTML.match(/class="promotion-card connected-promotion"/g)||[]).length,run("D.promotions.filter(p=>p.hospitalId==='h1').length"));
click('hospital-detail-tab','reviews');assert(els.app.innerHTML.includes('hospital-review-summary'));assert(!els.app.innerHTML.includes('hospital-rating-bars'));assert.equal((els.app.innerHTML.match(/hospital-review-summary-grid/g)||[]).length,1);assert(els.app.innerHTML.includes('의료진 신뢰'));assert.equal((els.app.innerHTML.match(/class="hospital-detail-review"/g)||[]).length,3);
const fiveStarCount=run("D.reviews.filter(r=>r.hospitalId==='h1'&&Math.round(Number(r.overallRating))===5).length");click('hospital-review-rating','5');assert(els.app.innerHTML.includes('hospital-rating-filter active'));assert.equal((els.app.innerHTML.match(/class="hospital-detail-review"/g)||[]).length,Math.min(3,fiveStarCount));click('hospital-review-rating','all');click('hospital-detail-reviews-more');assert.equal((els.app.innerHTML.match(/class="hospital-detail-review"/g)||[]).length,6);
assert(els.app.innerHTML.includes('상담 예약하기'));assert(els.app.innerHTML.includes('온라인 상담하기'));click('hospital-online','h1');assert.equal(run('screen'),'completion');assert(els.app.innerHTML.includes('예약이 완료되었습니다.'));assert.equal(run("SkinmateStorage.clean(state,D).bookings[0].type"),'online');run("screen='detail';routeId='h1';render()");click('hospital-detail-tab','treatments');click('hospital-treatment','h1:botox');assert.equal(run('screen'),'treatment');assert(els.app.innerHTML.includes('이 병원에서 받는 시술'));assert(els.app.innerHTML.includes('이 병원의 사각턱 보톡스 후기'));assert(els.app.innerHTML.includes('결제하기'));click('hospital-book','h1:botox');assert.equal(run('screen'),'completion');assert(els.app.innerHTML.includes('예약이 완료되었습니다.'));assert.equal(run('state.bookings[0].treatmentId'),'botox');assert.equal(run('state.bookings[0].type'),'online');click('back');run("screen='detail';routeId='h1';render()");assert(!els.app.innerHTML.includes('병원 상세</span>'));assert(!els.app.innerHTML.includes('회복 관련 후기'));click('hospital-detail-tab','reviews');assert(els.app.innerHTML.includes('hospital-detail-review'));click('decision-reviews','h1:botox');assert.equal(run('screen'),'hospital-reviews');assert(els.app.innerHTML.includes('추천에 반영된 평가 보기'));
assert(run("saveReviewRecord('h1','botox',{overallRating:5,effectRating:5,recoveryRating:5,priceRating:5,painRating:5,doctorTrustRating:5,distanceRating:5,content:'새로운 체험 후기입니다.'})"));assert.equal(run("L.aggregateReviews('h1','botox').count"),before+1);assert(run("SkinmateStorage.clean(JSON.parse(localStorage.getItem('skinmate-v2')),D).userReviews.length===1"));
click('navigate','home');const jaw=els.app.innerHTML;assert(jaw.includes('사각턱이 고민이라면?'));assert(jaw.includes('패인 여드름 흉터란?'));assert(jaw.includes('event-botox'));assert(jaw.includes('event-fractional'));
assert(jaw.includes('data-action="offer-detail"'));click('offer-detail','h1:botox');assert.equal(run('routeId'),'h1:botox');assert.equal(run('screen'),'treatment');click('navigate','explore');assert(els.app.innerHTML.includes('data-action="offer-detail"'));click('offer-detail','h2:fractional');assert.equal(run('screen'),'treatment');assert.equal(run('routeId'),'h2:fractional');assert(els.app.innerHTML.includes('온유 클리닉'));
click('start');click('reference-category','trouble');click('reference-concern','acneScar');click('navigate','home');assert(els.app.innerHTML.includes('사각턱이 고민이라면?')); // unfinished draft cannot change Home
click('personalized-home');assert.equal(run('screen'),'concern');assert.equal(run('state.draft.category'),'');assert.equal(run('state.draft.concern'),'');assert.equal(run('state.draft.priorities.length'),0);assert(!els.app.innerHTML.includes('subconcern-grid'));
click('start');click('reference-category','trouble');click('reference-concern','acneScar');click('to-priority');for(const k of ['recovery','trust','price'])click('priority',k);click('find');assert.equal(run('state.activeConcern'),'acneScar');assert.equal((els.app.innerHTML.match(/connected-treatment/g)||[]).length,4);click('treatments-more');assert((els.app.innerHTML.match(/connected-treatment/g)||[]).length>4);click('navigate','home');const scar=els.app.innerHTML;assert.notEqual(jaw,scar);assert(scar.includes('패인 여드름 흉터란?'));assert(!scar.split('찜한 병원 다시보기')[0].includes('사각턱 보톡스')); assert(scar.includes('프락셔널'));assert(scar.includes('흉터 치료는 한 가지'));
// State round trip, relational integrity and image completeness.
assert.equal(run('SkinmateStorage.clean(state,D).activeConcern'),'acneScar');assert.deepEqual([...run('SkinmateStorage.clean(state,D).recommendation.priorities')],['recovery','trust','price']);
assert(run("D.treatments.every(t=>t.concernIds.every(id=>D.subConcerns.some(c=>c.id===id))&&t.hospitalIds.length>0)"));assert(run("D.reviews.every(r=>D.hospitalTreatments.some(o=>o.hospitalId===r.hospitalId&&o.treatmentId===r.treatmentId))"));
for(const cat of run('D.concerns')){const count=run(`D.treatments.filter(t=>t.categoryIds.includes('${cat.id}')).length`);assert(count>=(cat.id==='other'?1:8),cat.id);}
for(const t of run('D.treatments'))assert(fs.existsSync(t.image),t.image);for(const f of ['skin','clinic','pigment','texture'])assert(fs.existsSync('assets/photos/'+f+'.webp'));
const prefs="{category:'contour',concern:'사각턱',priorities:['trust','recovery','price'],budget:'unknown',region:'강남'}";
const rank1=run(`L.rankHospitals(D.hospitals,'botox',${prefs}).map(h=>h.id)`);const rank2=run(`L.rankHospitals(D.hospitals,'botox',{...${prefs},priorities:['price','recovery','trust']}).map(h=>h.id)`);assert.notDeepEqual([...rank1],[...rank2]);assert.notEqual(rank1[0],'h6');
const rs=run('structuredClone(D.reviews)');for(const r of rs)if(r.hospitalId==='h2'&&r.treatmentId==='botox')r.doctorTrustRating=1;c.changedReviews=rs;
assert.notDeepEqual([...run(`L.rankHospitals(D.hospitals,'botox',${prefs},changedReviews).map(h=>h.id)`)], [...rank1]);
// Unrelated treatment reviews never affect a hospital/treatment aggregate.
assert.equal(run("L.aggregateReviews('h1','botox',D.reviews.filter(r=>r.treatmentId==='botox')).count"),run("L.aggregateReviews('h1','botox').count"));
run("exploreCategory='aging';screen='explore';render()");assert(els.app.innerHTML.includes('함께 많이 받는 시술'));assert(els.app.innerHTML.includes('후기 많은 시술'));assert(els.app.innerHTML.includes('explore-treatment-rail'));assert(!els.app.innerHTML.includes('전체보기'));
assert(els.app.innerHTML.indexOf('explore-results')<els.app.innerHTML.indexOf('함께 많이 받는 시술'));assert(els.app.innerHTML.includes('explore-hospital-rail'));assert(els.app.innerHTML.includes('explore-hospital-promo'));assert(els.app.innerHTML.includes('병원 홍보 · 가상 정보'));
assert(!els.app.innerHTML.includes('explore-image-placeholder'));assert(els.app.innerHTML.includes('explore-clinic-placeholder'));assert(els.app.innerHTML.includes('병원 이미지 준비 중'));assert(els.app.innerHTML.includes('상담 안내'));
const explorePair=run("(()=>{const t=D.treatments.find(t=>t.categoryIds.includes('aging'));return D.hospitals.filter(h=>L.getOffer(h.id,t.id)).map(h=>h.id+':'+t.id)[0]})()");assert(els.app.innerHTML.includes(`data-value="${explorePair}"`));
assert(run("D.treatments.every(t=>new Set(exploreHospitalCandidates(t,'강남').map(h=>h.id)).size>=4)"));
run("exploreCategory='all';exploreSub='all';exploreQuery='';exploreRegion='강남';screen='explore';render()");
const popular=els.app.innerHTML;assert(popular.indexOf('인기 시술')<popular.indexOf('explore-popular-caption')&&popular.indexOf('explore-popular-caption')<popular.indexOf('explore-results'));
const hospitalRails=[...popular.matchAll(/<div class="explore-hospital-rail"[^>]*>(.*?)<\/div><\/article>/g)];assert(hospitalRails.length>=4);for(const [,rail] of hospitalRails){const ids=[...rail.matchAll(/data-value="(h\d+):/g)].map(m=>m[1]);assert.equal(ids.length,4);assert.equal(new Set(ids).size,4);}
for(const cat of run('D.concerns')){run(`exploreCategory='${cat.id}';exploreSub=D.concerns.find(c=>c.id==='${cat.id}').items[0];screen='explore';render()`);assert(els.app.innerHTML.includes('함께 많이 받는 시술'),cat.id);assert(els.app.innerHTML.includes('후기 많은 시술'),cat.id);}
run("state.bookings=[{hospitalId:'h1',treatmentId:'botox',date:'2099-12-31',time:'10:00',createdAt:'2026-09-23'}];state.payments=[{hospitalId:'h1',treatmentId:'botox',price:19,createdAt:'2026-09-23'}];screen='activity';routeId='예정된 예약';render()");assert(els.app.innerHTML.includes('2099-12-31'));run("routeId='결제 내역';render()");assert(els.app.innerHTML.includes('190,000원'));assert.equal(run('SkinmateStorage.clean(state,D).bookings.length'),1);assert.equal(run('SkinmateStorage.clean(state,D).payments.length'),1);
run("routeId='예정된 예약';render()");assert(els.app.innerHTML.includes('예약 취소'));click('cancel-booking','0');assert(!els.app.innerHTML.includes('예약 취소'));assert.equal(run('SkinmateStorage.clean(state,D).bookings[0].status'),'canceled');run("routeId='지난 예약';render()");assert(els.app.innerHTML.includes('취소됨'));run("routeId='결제 내역';render()");assert(els.app.innerHTML.includes('결제 취소'));click('cancel-payment','0');assert(els.app.innerHTML.includes('결제 취소됨'));assert(!els.app.innerHTML.includes('data-action="cancel-payment"'));assert.equal(run('SkinmateStorage.clean(state,D).payments[0].status'),'canceled');
for(const screenName of ['home','explore','community','saved','my','settings','treatments','hospitals']){run(`screen='${screenName}';render()`);assert(!/선호 조건 일치도|Match Score|50%|30%|20%/.test(els.app.innerHTML),screenName);}
run("state.activeConcern=null;state.recommendation=null;state.profile.concerns=['색소침착','팔'];state.profile.region='강남';screen='home';render()");
assert(els.app.innerHTML.includes('색소침착이 고민이라면?'));assert(els.app.innerHTML.includes('팔 레이저 제모가 고민이라면?'));
const pigmentationSection=els.app.innerHTML.split('data-concern="pigmentation"')[1].split('data-concern="hairRemovalArms"')[0],armsSection=els.app.innerHTML.split('data-concern="hairRemovalArms"')[1].split('관련 이벤트')[0];
assert(pigmentationSection.includes('색소침착에 레이저를 바로 받아도 되나요?'));assert(armsSection.includes('팔 제모는 몇 회가 필요한가요?'));
for(const topic of [pigmentationSection,armsSection]){assert(topic.includes('home-concern-recommendations'));assert(topic.includes('home-concern-knowledge'));assert(topic.includes('home-concern-treatments'));assert(topic.includes('home-concern-questions'));}
assert(pigmentationSection.includes('related-treatment-list')&&armsSection.includes('related-treatment-list'));
assert(run("homeContent(concernById('pigmentation')).treatments.every(t=>t.concernIds.includes('pigmentation'))"));
assert(run("homeContent(concernById('hairRemovalArms')).treatments.every(t=>t.concernIds.includes('hairRemovalArms'))"));
const armTreatment=run("homeContent(concernById('hairRemovalArms')).treatments[0].id");click('decision-hospitals-for','hairRemovalArms:'+armTreatment);assert.equal(run('state.draft.concernId'),'hairRemovalArms');assert.equal(run('state.selectedTreatment'),armTreatment);
console.log('PASS: concern→treatment→hospital→review→recommendation→Home; priorities, counts, bookmarks, persistence, all pools and images');
console.log(JSON.stringify(run("({treatments:D.treatments.length,concerns:D.subConcerns.length,hospitalTreatments:D.hospitalTreatments.length,reviews:D.reviews.filter(r=>!r.id.startsWith('local-')).length,categoryCounts:Object.fromEntries(D.concerns.map(c=>[c.name,D.treatments.filter(t=>t.categoryIds.includes(c.id)).length]))})")));

// Entry replay keeps bookmarks/reviews and forces the full onboarding flow.
const savedBefore=JSON.stringify(run('state.saved')), reviewsBefore=run('state.userReviews.length');
click('logout');assert.equal(run('screen'),'login');assert(els.app.innerHTML.includes('로그인 · 회원가입'));assert.equal(JSON.stringify(run('state.saved')),savedBefore);assert.equal(run('state.userReviews.length'),reviewsBefore);
click('login-provider','이메일');assert.equal(run('screen'),'onboarding');assert.equal(run('onboardingStep'),0);
click('onboard-next');assert.equal(run('onboardCategories.length'),0);click('onboard-category','contour');click('onboard-next');click('onboard-concern','squareJaw');
// Onboarding values use display names.
run("profileDraft.concerns=['사각턱']");click('onboard-next');click('onboard-region','강남');click('onboard-next');click('onboard-next');assert.equal(run('screen'),'home');
run('restore()');assert.equal(run('screen'),'home');click('logout');assert.equal(run('screen'),'login');click('login-provider','이메일');assert.equal(run('screen'),'onboarding');
run("sessionStorage.removeItem('skinmate-login-session');state=SkinmateStorage.load(localStorage,D);restore()");assert.equal(run('screen'),'login');assert.equal(run('state.auth.loggedIn'),true);run("state=SkinmateStorage.load({getItem(){return null}},D);restore()");assert.equal(run('screen'),'login');assert(els.app.innerHTML.includes('로그인 · 회원가입'));
console.log('PASS: replay preserves saved data; signed-in refresh, onboarding, in-app navigation, logout/relogin');
