const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const listeners={},els={app:{innerHTML:''},main:{scrollTop:0,focus(){}},toast:{classList:{add(){},remove(){}}}},stored={};
const c={structuredClone,console,setTimeout(){},clearTimeout(){},localStorage:{getItem:k=>stored[k]||null,setItem:(k,v)=>stored[k]=v},document:{getElementById:id=>els[id],addEventListener:(n,f)=>(listeners[n]??=[]).push(f)},window:{addEventListener(){}},history:{state:null,replaceState(){},pushState(){}},location:{hash:''}};
vm.createContext(c);const run=s=>vm.runInContext(s,c);
for(const f of ['data/catalog.js','services/recommendations.js','services/storage.js','components.js','views.js','redesign.js','app.js'])run(fs.readFileSync(f,'utf8'));
run("state.auth.loggedIn=true;state.onboarded=true;screen='concern';state.draft.category='texture';state.draft.concern='피지';render()");
assert(els.app.innerHTML.includes('포텐자'));
assert(els.app.innerHTML.includes('상담에서 물어보세요'));
assert(!els.app.innerHTML.includes('STEP 01'));
assert(!els.app.innerHTML.includes('해결하고 싶은 고민을 선택해주세요'));
run("state.draft.priorities=['effect','price','pain'];screen='priority';render()");
assert(!els.app.innerHTML.includes('priority-summary'));
run("screen='treatments';render()");
assert(els.app.innerHTML.includes('edit-conditions'));
assert(els.app.innerHTML.includes('data-action="why-treatment"'));
assert(!els.app.innerHTML.includes('MY PREFERENCE'));
assert(!els.app.innerHTML.includes('reason-list'));
assert(!els.app.innerHTML.includes('중요하게 선택했어요'));
run("screen='treatment';routeId='potenza';render()");
assert(els.app.innerHTML.includes('비교할 점'));
assert(els.app.innerHTML.includes('상담에서 물어보세요'));
console.log('Recommendation UI checks passed');
