/* Deterministic review-based ordering. No percentage or fixed priority weights. */
const SkinmateLogic=(()=>{
 const fields={effect:'effectRating',recovery:'recoveryRating',price:'priceRating',pain:'painRating',trust:'doctorTrustRating',distance:'distanceRating'};
 const dataset=()=>typeof SkinmateData!=='undefined'?SkinmateData:null;
 const budgetMax=id=>({'10':10,'30':30,'50':50})[id]??null;
 function budgetInfo(range,budget){const max=budgetMax(budget);return {exceeded:max!==null&&range[0]>max,partial:max!==null&&range[0]<=max&&range[1]>max,minOver:max===null?0:Math.max(0,range[0]-max),maxOver:max===null?0:Math.max(0,range[1]-max)};}
 function resolveConcern(selection){const D=dataset();return D.subConcerns.find(c=>c.id===selection.concernId)||D.subConcerns.find(c=>c.categoryId===selection.category&&c.name===selection.concern);}
 function filterTreatmentsByConcern(treatments,selection){const c=resolveConcern(selection);return c?treatments.filter(t=>t.concernIds.includes(c.id)):[];}
 function aggregateReviews(hospitalId,treatmentId,reviews=dataset().reviews){const rows=reviews.filter(r=>r.hospitalId===hospitalId&&(!treatmentId||r.treatmentId===treatmentId));const means={},counts={},positive={},adjusted={};for(const [k,f] of Object.entries(fields)){const values=rows.map(r=>r[f]).filter(v=>Number.isFinite(v)&&v>=1&&v<=5);counts[k]=values.length;positive[k]=values.filter(v=>v>=4).length;means[k]=values.length?values.reduce((a,b)=>a+b,0)/values.length:null;/* Five neutral observations shrink tiny samples toward 3/5. */adjusted[k]=values.length?(values.reduce((a,b)=>a+b,0)+15)/(values.length+5):0;}
 const rating=rows.length?rows.reduce((s,r)=>s+r.overallRating,0)/rows.length:null;return {count:rows.length,rating,means,counts,positive,adjusted,confidence:rows.length<3?'limited':rows.length<8?'developing':'established',rows};}
 function getOffer(hospitalId,treatmentId,concernId){const o=dataset().hospitalTreatments.find(x=>x.hospitalId===hospitalId&&x.treatmentId===treatmentId&&x.isAvailable);if(!o)return null;const c=dataset().subConcerns.find(c=>c.id===concernId);const base=o.eventPrice??o.price;const area=c?.categoryId==='hair'&&o.areaPrices[c.name]!==undefined?c.name:null;const increment=area?o.areaPrices[area]-base:0;return {...o,originalPrice:o.price+increment,price:base+increment,unit:area?area+' · 1회 · VAT 포함 · 예시':o.unit};}
 function sortCandidates(a,b,prefs){const ag=a.aggregate,bg=b.aggregate;/* A lone five-star review must not dominate a supported sample. */const tier=g=>g.count===0?0:g.count<3?1:2;let delta=tier(bg)-tier(ag);if(delta)return delta;for(const k of [...new Set(prefs.priorities||[])].slice(0,3)){delta=Math.round(bg.adjusted[k]*4)-Math.round(ag.adjusted[k]*4);if(delta)return delta;}
 // Similar review evaluations: local availability, budget, sample size, overall rating, stable ID.
 delta=Number(b.location===prefs.region)-Number(a.location===prefs.region);if(delta)return delta;
 delta=Number(a.budget?.exceeded)-Number(b.budget?.exceeded);if(delta)return delta;
 return bg.count-ag.count||(bg.rating||0)-(ag.rating||0)||a.id.localeCompare(b.id);
 }
 function rankHospitals(hospitals,treatmentId,prefs,reviews=dataset().reviews){const concern=resolveConcern(prefs);return hospitals.map(h=>{const offer=getOffer(h.id,treatmentId,concern?.id);if(!offer)return null;const aggregate=aggregateReviews(h.id,treatmentId,reviews),range=[offer.price,offer.price];return {...h,treatmentId,offer,aggregate,rating:aggregate.rating,reviewCount:aggregate.count,priceRange:range,budget:budgetInfo(range,prefs.budget)};}).filter(Boolean).sort((a,b)=>sortCandidates(a,b,prefs));}
 function rankTreatments(treatments,hospitals,prefs){return filterTreatmentsByConcern(treatments,prefs).map(t=>{const hs=rankHospitals(hospitals,t.id,prefs);return {...t,budget:budgetInfo(t.priceRange,prefs.budget),bestHospital:hs[0],availableCount:hs.length};}).sort((a,b)=>{if(!a.bestHospital||!b.bestHospital)return b.availableCount-a.availableCount;return sortCandidates(a.bestHospital,b.bestHospital,prefs)||a.id.localeCompare(b.id);});}
 function compareHospitals(hospitals,ids,treatmentId,prefs){const candidates=ids.map(id=>{const h=hospitals.find(h=>h.id===id);if(!h)return null;const o=getOffer(id,treatmentId,resolveConcern(prefs)?.id);return {...h,comparable:!!o,offer:o,aggregate:aggregateReviews(id,treatmentId),priceRange:o?[o.price,o.price]:[]};}).filter(Boolean);return {candidates,rows:[...new Set([...(prefs.priorities||[]),...Object.keys(fields)])].map(key=>({key,bestIds:[]}))};}
 function reasonLines(hospitalId,treatmentId,prefs){const g=aggregateReviews(hospitalId,treatmentId);if(!g.count)return ['이 시술의 평가 후기가 아직 없어요. 제공 시술과 가격 정보를 확인해보세요.'];const labels={effect:'효과 체감',recovery:'회복 부담',price:'가격 만족',pain:'통증 부담',trust:'의료진 설명·신뢰',distance:'방문 편의'};const lines=(prefs.priorities?.length?prefs.priorities:['trust','recovery','price']).map(k=>{const count=g.counts[k],good=g.positive[k];return `${labels[k]}: ${count}건 중 ${good}건에서 4점 이상으로 평가했어요.${good*2<count?' 평가가 엇갈려 본문도 살펴보세요.':''}`;});if(g.count<3)lines.unshift('관련 후기가 '+g.count+'건으로 적어 추천 근거가 제한적이에요.');const o=getOffer(hospitalId,treatmentId,resolveConcern(prefs)?.id),h=dataset().hospitals.find(h=>h.id===hospitalId);lines.push(h.location===prefs.region?'선택한 '+prefs.region+' 지역에서 제공하는 시술이에요.':'선택한 지역 밖의 병원이에요. 이동 거리를 확인하세요.');if(o&&budgetMax(prefs.budget)!==null)lines.push(o.price<=budgetMax(prefs.budget)?'표시된 예시 가격은 설정한 예산 안에 있어요.':'표시된 예시 가격은 설정한 예산을 초과해요.');return lines;}
 return {fields,budgetMax,budgetInfo,resolveConcern,filterTreatmentsByConcern,aggregateReviews,getOffer,sortCandidates,rankTreatments,rankHospitals,compareHospitals,reasonLines};
})();
if(typeof module!=='undefined')module.exports=SkinmateLogic;
